

def build(bld):
    bld.DefineGem(
        # Add custom build options here
        includes    = [bld.Path('Code/CryEngine/CryAction'),
                        bld.Path('Gems/LmbrCentral/Code/include')
                      ],
    )
