########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):
    bld.DefineGem(
        # Add custom build options here
        use         = ['AzCore', 'AzFramework'],

        includes    = [ '.',
                        'Include',
                        bld.Path('Code/CryEngine/CryAction'),
                      ],

        editor = dict(
            platforms   = ['win', 'darwin'],

            defines     = ['MAESTRO_EDITOR',],

            includes    = [ '.',
                            'Include',
                            'Source',
                            bld.Path('Code/Sandbox/Editor'),
                            bld.Path('Code/Sandbox/Editor/Include'),
                            bld.Path('Code/Sandbox/Plugins/EditorCommon'),
                            bld.Path('Code/CryEngine/CryAction'),
                           ],
            use_required_gems    = True,

            win_x64_clang_cxxflags = ['-Wno-ignored-pragmas'],
        ),

        win_features        = ['crcfix'],

        use_required_gems    = True,

    )
