########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

import os

def build(bld):

    bld.CryLauncher(
        # Settings
        target              = 'AndroidLauncher',
        platforms           = ['android' ],
        configurations      = ['debug', 'profile', 'performance', 'release'],
        file_list           = 'android_launcher.waf_files',

        # Platform Specific
        android_use             = ['AzGameFramework', 'SDL2_Android', 'SDL2Ext' ],
        android_includes        = [bld.Path('Code/CryEngine/CryAction'),
                                   bld.Path('Code/CryEngine/CrySystem')],

        android_java_src_path   = [bld.Path('Code/Launcher/AndroidLauncher/java') ],
        android_java_libs       = bld.Path('Code/Launcher/AndroidLauncher/ProjectBuilder/android_libraries.json'),

        android_features        = [ 'find_android_api_libs' ]
    )

