
params = {
    'AppStream': {},
    'Auto-Scaling': { path_encoding_style: 'es' },
    'CloudFormation': { path_encoding_style: 'es' },
    'CloudFront': { path_encoding_style: 'es' },
    'CloudHSM': {},
    'CloudSearch': { path_encoding_style: 'es' },
    'CloudTrail': { path_encoding_style: 'es' },
    'CloudWatch (logs)': { path_encoding_style: 'es' },
    'CloudWatch (monitoring)': { path_encoding_style: 'es' },
    'CodeDeploy': { path_encoding_style: 'es' },
    'Cognito Identity': {},
    'Cognito Sync': {},
    'Config': { path_encoding_style: 'es' },
    'DataPipeline': { path_encoding_style: 'es' },
    'Direct Connect': { path_encoding_style: 'es' },
    'DynamoDB': { path_encoding_style: 'es' },
    'EC2': {},
    'EC2 Container Service': { path_encoding_style: 'es' },
    'ElastiCache': { path_encoding_style: 'es' },
    'Elastic Beanstalk': { path_encoding_style: 'es' },
    'Elastic Load Balancing': { path_encoding_style: 'es' },
    'Elastic MapReduce': { path_encoding_style: 'es' },
    'Elastic Transcoder': { path_encoding_style: 'es' },
    'Glacier': { path_encoding_style: 'es' },
    'Identity and Access Management (IAM)': { path_encoding_style: 'es' },
    'Key Management Service': { path_encoding_style: 'es' },
    'Kinesis': { path_encoding_style: 'es' },
    'Lambda': {},
    'Opsworks': { path_encoding_style: 'es' },
    'Redshift': { path_encoding_style: 'es' },
    'Relational Database Service (RDS)': { path_encoding_style: 'es' },
    'Route 53': { path_encoding_style: 'es' },
    'Security Token Service': { path_encoding_style: 'es' },
    'Simple Notification Service (SNS)': { path_encoding_style: 'es' },
    'Simple Queue Service (SQS)': {},
    'Simple Storage Service (S3)': { path_encoding_style: 's3' },
    'Storage Gateway': { path_encoding_style: 'es' },
}
