########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################


def build(bld):

    bld.CryPlugin(
        # Settings
        target          = 'ParticleEditorPlugin',
        vs_filter       = 'Sandbox/Plugins',
        file_list       = 'particleeditorplugin.waf_files',
        platforms       = ['win','darwin'],
        configurations  = ['debug', 'debug_test', 'profile', 'profile_test'],
        pch             = "stdafx.cpp",
        use             = ['EditorUI_QT',
                           'CryCommon'],
        uselib          = ['QTANGLE',
                           'QT5CORE',
                           'QT5GUI',
                           'QT5WIDGETS',
                           'BOOST'],
        features        = ['qt5'],
        includes        = [bld.Path('Code/Sandbox/Plugins/EditorUI_QT')],
        use_required_gems  = True,

        # Testing
        test_all_file_list = ['test.waf_files'],
    )

