########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################


def build(bld):

    # Build for EditorAudioControlsEditor
    bld.CryStandAlonePlugin(

        # Settings
        target              = 'EditorAudioControlsEditor',
        vs_filter           = 'Sandbox/Plugins/AudioControlsEditor',
        copyright_org       = 'Amazon-CryTek',
        file_list           = 'editoraudiocontrolseditor.waf_files',
        platforms           = ['win', 'darwin'],
        configurations      = ['debug', 'debug_test', 'profile', 'profile_test'],
        pch                 = "StdAfx.cpp",
        use                 = ['EditorCommon', 'CrySoundSystem'],
        uselib              = ['QT5CORE',
                               'QT5GUI',
                               'QT5WIDGETS'],
        features            = ['qt5'],
        includes            = ['common'],

        # Testing
        test_all_file_list = ['editoraudiocontrolseditor_test.waf_files'],
    )

    bld.recurse('common')
    bld.recurse('EditorNoSound')
    bld.recurse('EditorWwise')
