########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):
    bld.DefineGem(
        includes          = [ '.', 'Include' ],
        win_features      = ['crcfix'],
        use_required_gems = True,

        editor = dict(
            platforms   = ['win', 'darwin'],
            features    = ['qt5'],
            uselib      = [
			               'QT5CORE',
                           'QT5GUI',
                           'QT5WIDGETS',
                           'QT5NETWORK' # this lib depends on EditorLib, which depends on NewsShared, which depends on Qt5Network
                           ],
            defines     = ['GRADIENTSIGNAL_EDITOR'],
            includes    = ['.', 
                           'Include',
                           bld.Path('Code/Sandbox/Plugins/EditorCommon'),
                           bld.Path('Code/Sandbox/Editor'),
                           bld.Path('Code/Sandbox/Editor/Include'),
                           ],
            use         = ['EditorUI_QT',
                           'EditorCommon',
                           'EditorLib', 
                           'AssetBuilderSDK',
                           'AzToolsFramework', 
                           'AzQtComponents'],
            use_required_gems = True,
        ),
    )
