
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.20.0'
version_full = '9ee27e85786ac3b23d32c0e5d844f1157e69df37'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

