########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):

    bld.CryResourceCompilerModule(
        # Settings
        target                      = 'ResourceCompilerSlice',
        vs_filter                   = 'RC',
        file_list                   = 'resourcecompilerslice.waf_files',
        platforms                   = ['win','darwin'],
        client_only                 = True,
        exclude_monolithic          = True,
        use                         = ['AzToolsFramework',
                                       'AssetBuilderSDK'],
        uselib                      = ['QT5CORE',
                                       'QT5GUI',
                                       'QT5WIDGETS'],
        features                    = ['qt5'],
        includes                    = [ '.',
                                        bld.Path('Code/Tools'),
                                        bld.Path('Code/Tools/RC/ResourceCompiler'),
                                        bld.Path('Code/Tools/CryCommonTools')],

        darwin_uselib               = ['AWS_CPP_SDK_CORE',
                                       'AWS_CPP_SDK_COGNITO_IDENTITY_STATIC',
                                       'AWS_CPP_SDK_IDENTITY_MANAGEMENT',
                                       'AWS_CPP_SDK_MOBILEANALYTICS'],

        # Testing
        test_all_file_list = ['resourcecompilerslice_test.waf_files'],
    )
