

def build(bld):
    bld.DefineGem(
        includes     = [bld.Path('Code/CryEngine/CryAction')],
        win_features = ['crcfix'],
        editor = dict(
            platforms   = ['win', 'darwin'],
            defines    = ['CRY_ENTITY_REMOVAL_EDITOR',
                          'EDITOR_COMMON_IMPORTS'],
            uselib     = ['QT5CORE',
                          'QT5GUI',
                          'QT5WIDGETS'],
            use        = ['AzQtComponents',
                          'EditorUI_QT',
                          'EditorCommon',
                          'EditorCore'],
            features   = ['qt5'],
            includes   = ['Include',
                          'Source',
                          bld.Path('Code/CryEngine/CryAction'),
                          bld.Path('Code/Sandbox/Plugins/EditorCommon'),
                          bld.Path('Code/Sandbox/Editor'),
                          bld.Path('Code/Sandbox/Editor/Include')],
        ),
    )
