########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

import os

def build(bld):
    java_src_root = bld.path.make_node(os.path.join('Source', 'Android', 'java'))

    bld.DefineGem(
        # File lists
        android_file_list   = ['microphone_android.waf_files'],
        # appletv_file_list   = ['microphone_appletv.waf_files'],
        darwin_file_list    = ['microphone_darwin.waf_files'],
        #
        ios_file_list       = ['microphone_ios.waf_files'],
        # linux_file_list     = ['microphone_linux.waf_files'],
        #
        win_file_list       = ['microphone_win.waf_files'],

        # Add custom build options here
        includes            = [bld.Path('Code/CryEngine/CrySoundSystem/Common')],

        android_java_src_path = [ java_src_root.abspath() ],
        android_use           = ['SDL2_Android'],

        win_features        = ['crcfix'],
        win_lib             = ['ole32', 'libsamplerate'],

    )
