########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

import os

def build(bld):
    java_src_root = bld.path.make_node(os.path.join('Source', 'Platform', 'Android', 'java'))

    manifest_src_root = bld.path.make_node(os.path.join('Source', 'Android'))


    kw_dict = dict(
        file_list = ['microphone.waf_files'],
        includes            = [bld.Path('Code/CryEngine/CrySoundSystem/Common'),
                               bld.Path('Code/CryEngine/CryCommon')
                              ],

        android_java_src_path = [ java_src_root.abspath() ],
        android_manifest_path = [ manifest_src_root.abspath() ],

        win_features        = ['crcfix'],
        win_lib             = ['ole32', 'libsamplerate'],
        platform_roots      = [bld.PlatformRoot('Source/Platform', export_includes=False)]
    )

    bld.DefineGem(
        **kw_dict
    )
