/*
* All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
* its licensors.
*
* For complete copyright and license terms please see the LICENSE at the root of this
* distribution (the "License"). All use of this software is governed by the License,
* or, if provided, by the license below or the license accompanying this file. Do not
* remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*
*/

/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////
// THIS CODE IS AUTOGENERATED, DO NOT MODIFY
/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////

#pragma once
#include <AzCore/Component/Component.h>
#include <AzCore/Component/Entity.h>
#include <AzCore/Component/ComponentBus.h>
#include <AzCore/EBus/EBus.h>
#include <AzCore/Memory/SystemAllocator.h>
#include <AzCore/RTTI/BehaviorContext.h>
#include <AzCore/Serialization/EditContext.h>
#include <AzCore/Serialization/SerializeContext.h>
#include <AzCore/std/smart_ptr/make_shared.h>
#include <AzCore/std/smart_ptr/shared_ptr.h>
#include <AzCore/std/string/conversions.h>

#if defined (PLATFORM_SUPPORTS_AWS_NATIVE_SDK)
#include <aws/core/http/HttpRequest.h>
#include <aws/core/http/HttpResponse.h>
#endif // (PLATFORM_SUPPORTS_AWS_NATIVE_SDK)

#include <LmbrAWS/ILmbrAWS.h>

#include <CloudGemFramework/ServiceRequestJob.h>

#include "StdAfx.h"

namespace CloudGemPlayerAccount {
namespace ServiceAPI {
    
    const char* LmbrAWS_CodeGen_Component_UUID= "{944353e1-ed91-11e6-aa43-80a589661b03}";
    
    const char* LmbrAWS_CodeGen_ResponseHandler_UUID= "{944353e4-ed91-11e6-ac86-80a589661b03}";
    
    const char* LmbrAWS_CodeGen_NotificationBus1_UUID= "{944353e2-ed91-11e6-9752-80a589661b03}";
    
    const char* LmbrAWS_CodeGen_RequestBus1_UUID= "{944353e3-ed91-11e6-8933-80a589661b03}";
    
    const char* LmbrAWS_CodeGen_ServiceStatus_UUID= "{944353e5-ed91-11e6-b8b0-80a589661b03}";
    
    const char* LmbrAWS_CodeGen_AccountResponse_UUID= "{944353e6-ed91-11e6-a5af-80a589661b03}";
    
    const char* LmbrAWS_CodeGen_UpdateAccountRequest_UUID= "{944353e8-ed91-11e6-b986-80a589661b03}";
    

    // redefs
    

    bool WriteJson(CloudGemFramework::JsonWriter& writer, const int& item)
    {
        return writer.Int(item);
    }

    bool WriteJson(CloudGemFramework::JsonWriter& writer, const AZStd::string& item)
    {
        return writer.String(item);
    }

    bool WriteJson(CloudGemFramework::JsonWriter& writer, const double& item)
    {
        return writer.Double(item);
    }

    
    
    struct UpdateAccountRequest
    {

        AZ_TYPE_INFO(UpdateAccountRequest, LmbrAWS_CodeGen_UpdateAccountRequest_UUID)
        AZ_CLASS_ALLOCATOR(UpdateAccountRequest, AZ::SystemAllocator, 0)

        
        AZStd::string PlayerName;
        

        bool OnJsonKey(const char* key, CloudGemFramework::JsonReader& reader);

        static void Reflect(AZ::ReflectContext* reflection);
    };

    bool WriteJson(CloudGemFramework::JsonWriter& writer, const UpdateAccountRequest& item)
    {
            bool ok = true;
            ok = ok && writer.StartObject();
            
            ok = ok && writer.Key("PlayerName");
            ok = ok && WriteJson(writer, item.PlayerName);
            
            ok = ok && writer.EndObject();
            return ok;
    }
    
    
    
    struct AccountResponse
    {

        AZ_TYPE_INFO(AccountResponse, LmbrAWS_CodeGen_AccountResponse_UUID)
        AZ_CLASS_ALLOCATOR(AccountResponse, AZ::SystemAllocator, 0)

        
        AZStd::string PlayerName;
        
        AZStd::string AccountId;
        

        bool OnJsonKey(const char* key, CloudGemFramework::JsonReader& reader);

        static void Reflect(AZ::ReflectContext* reflection);
    };

    bool WriteJson(CloudGemFramework::JsonWriter& writer, const AccountResponse& item)
    {
            bool ok = true;
            ok = ok && writer.StartObject();
            
            ok = ok && writer.Key("PlayerName");
            ok = ok && WriteJson(writer, item.PlayerName);
            
            ok = ok && writer.Key("AccountId");
            ok = ok && WriteJson(writer, item.AccountId);
            
            ok = ok && writer.EndObject();
            return ok;
    }
    
    
    
    struct ServiceStatus
    {

        AZ_TYPE_INFO(ServiceStatus, LmbrAWS_CodeGen_ServiceStatus_UUID)
        AZ_CLASS_ALLOCATOR(ServiceStatus, AZ::SystemAllocator, 0)

        
        AZStd::string status;
        

        bool OnJsonKey(const char* key, CloudGemFramework::JsonReader& reader);

        static void Reflect(AZ::ReflectContext* reflection);
    };

    bool WriteJson(CloudGemFramework::JsonWriter& writer, const ServiceStatus& item)
    {
            bool ok = true;
            ok = ok && writer.StartObject();
            
            ok = ok && writer.Key("status");
            ok = ok && WriteJson(writer, item.status);
            
            ok = ok && writer.EndObject();
            return ok;
    }
    
    


    // Service RequestJobs
    CLOUD_GEM_SERVICE(CloudGemPlayerAccount);

    void Configure()
    {
        // Insert any necessary CloudGemFramework configuration here
    }
    
    class PutAccountRequest
        : public CloudGemFramework::ServiceRequest
    {
    public:
        SERVICE_REQUEST(CloudGemPlayerAccount, HttpMethod::HTTP_PUT, "/account");

        struct Parameters
        {
            
            UpdateAccountRequest UpdateAccountRequest;
            

            bool BuildRequest(CloudGemFramework::RequestBuilder& request)
            {
                bool ok = true;
                
                
                ok = ok && request.WriteJsonBodyParameter(*this);
                return ok;
            }

            bool WriteJson(CloudGemFramework::JsonWriter& writer) const
            {
                bool ok = true;
                
                ok = ok && CloudGemPlayerAccount::ServiceAPI::WriteJson(writer, UpdateAccountRequest);
                
                return ok;
            }
        };

        
        AccountResponse result;
        

        Parameters parameters;
    };


    using PutAccountRequestJob = CloudGemFramework::ServiceRequestJob<PutAccountRequest>;
    
    class GetAccountRequest
        : public CloudGemFramework::ServiceRequest
    {
    public:
        SERVICE_REQUEST(CloudGemPlayerAccount, HttpMethod::HTTP_GET, "/account");

        struct Parameters
        {
            

            bool BuildRequest(CloudGemFramework::RequestBuilder& request)
            {
                bool ok = true;
                
                
                ok = ok && request.WriteJsonBodyParameter(*this);
                return ok;
            }

            bool WriteJson(CloudGemFramework::JsonWriter& writer) const
            {
                bool ok = true;
                
                return ok;
            }
        };

        
        AccountResponse result;
        

        Parameters parameters;
    };


    using GetAccountRequestJob = CloudGemFramework::ServiceRequestJob<GetAccountRequest>;
    
    class GetServiceStatusRequest
        : public CloudGemFramework::ServiceRequest
    {
    public:
        SERVICE_REQUEST(CloudGemPlayerAccount, HttpMethod::HTTP_GET, "/service/status");

        struct Parameters
        {
            

            bool BuildRequest(CloudGemFramework::RequestBuilder& request)
            {
                bool ok = true;
                
                
                ok = ok && request.WriteJsonBodyParameter(*this);
                return ok;
            }

            bool WriteJson(CloudGemFramework::JsonWriter& writer) const
            {
                bool ok = true;
                
                return ok;
            }
        };

        
        ServiceStatus result;
        

        Parameters parameters;
    };


    using GetServiceStatusRequestJob = CloudGemFramework::ServiceRequestJob<GetServiceStatusRequest>;
    


    // Notification bus for this component
    class CloudGemPlayerAccountNotifications
        : public AZ::ComponentBus
    {
    public:
        // static const bool EnableEventQueue = true;
        
        /**
         * Sent when the request is a success
         *
         * Params:
         *    jsonOutput:       The output receieved from the lambda call
         *    request:          The AWS Lambda request object
         */
        
        virtual void OnPutAccountRequestSuccess(const AccountResponse response) { }
        

        /**
         * Sent when the request fails
         *
         * Params:
         *    error:           The output receieved from the lambda call,
         *                     could be function error or an issue with the request
         *    request:         The AWS Lambda request object
         */
        virtual void OnPutAccountRequestError(const CloudGemFramework::Error error) { }
        
        /**
         * Sent when the request is a success
         *
         * Params:
         *    jsonOutput:       The output receieved from the lambda call
         *    request:          The AWS Lambda request object
         */
        
        virtual void OnGetAccountRequestSuccess(const AccountResponse response) { }
        

        /**
         * Sent when the request fails
         *
         * Params:
         *    error:           The output receieved from the lambda call,
         *                     could be function error or an issue with the request
         *    request:         The AWS Lambda request object
         */
        virtual void OnGetAccountRequestError(const CloudGemFramework::Error error) { }
        
        /**
         * Sent when the request is a success
         *
         * Params:
         *    jsonOutput:       The output receieved from the lambda call
         *    request:          The AWS Lambda request object
         */
        
        virtual void OnGetServiceStatusRequestSuccess(const ServiceStatus response) { }
        

        /**
         * Sent when the request fails
         *
         * Params:
         *    error:           The output receieved from the lambda call,
         *                     could be function error or an issue with the request
         *    request:         The AWS Lambda request object
         */
        virtual void OnGetServiceStatusRequestError(const CloudGemFramework::Error error) { }
        
    };

    using CloudGemPlayerAccountNotificationBus = AZ::EBus<CloudGemPlayerAccountNotifications>;

    class BehaviorCloudGemPlayerAccountNotificationBusHandler
        : public CloudGemPlayerAccountNotificationBus::Handler, public AZ::BehaviorEBusHandler
    {
    public:
        AZ_EBUS_BEHAVIOR_BINDER(BehaviorCloudGemPlayerAccountNotificationBusHandler, LmbrAWS_CodeGen_NotificationBus1_UUID, AZ::SystemAllocator
        
        , OnPutAccountRequestSuccess
        , OnPutAccountRequestError
        
        , OnGetAccountRequestSuccess
        , OnGetAccountRequestError
        
        , OnGetServiceStatusRequestSuccess
        , OnGetServiceStatusRequestError
        
        );
        
        
        void OnPutAccountRequestSuccess(const AccountResponse response) override
        {
            Call(FN_OnPutAccountRequestSuccess, response);
        }
        
        void OnPutAccountRequestError(const CloudGemFramework::Error error) override
        {
            Call(FN_OnPutAccountRequestError, error);
        }
        
        
        void OnGetAccountRequestSuccess(const AccountResponse response) override
        {
            Call(FN_OnGetAccountRequestSuccess, response);
        }
        
        void OnGetAccountRequestError(const CloudGemFramework::Error error) override
        {
            Call(FN_OnGetAccountRequestError, error);
        }
        
        
        void OnGetServiceStatusRequestSuccess(const ServiceStatus response) override
        {
            Call(FN_OnGetServiceStatusRequestSuccess, response);
        }
        
        void OnGetServiceStatusRequestError(const CloudGemFramework::Error error) override
        {
            Call(FN_OnGetServiceStatusRequestError, error);
        }
        
    };
    class CloudGemPlayerAccountResponseHandler;

    // Request bus for this component
    class CloudGemPlayerAccountRequests
        : public AZ::ComponentBus
    {
    public:
        virtual ~CloudGemPlayerAccountRequests() {}
        
        
        virtual void PutAccount(const UpdateAccountRequest& UpdateAccountRequest, CloudGemPlayerAccountResponseHandler* responseHandler) { }
        
        
        
        virtual void GetAccount(CloudGemPlayerAccountResponseHandler* responseHandler) { }
        
        
        
        virtual void GetServiceStatus(CloudGemPlayerAccountResponseHandler* responseHandler) { }
        
        
    };

    using CloudGemPlayerAccountRequestBus = AZ::EBus<CloudGemPlayerAccountRequests>;

    // This class is used as a parameter for all requests and throws the response on the CloudGemPlayerAccountNotificationBus
    // Inherit from this to define custom behavior.
    class CloudGemPlayerAccountResponseHandler
    {
    public:
        AZ_TYPE_INFO(CloudGemPlayerAccountResponseHandler, LmbrAWS_CodeGen_ResponseHandler_UUID)
        AZ_CLASS_ALLOCATOR(CloudGemPlayerAccountResponseHandler, AZ::SystemAllocator, 0)

        virtual ~CloudGemPlayerAccountResponseHandler() {}
        
        virtual void HandlePutAccountSuccess(PutAccountRequestJob* job, AZ::EntityId entityId)
        {
            
            EBUS_EVENT_ID(entityId, CloudGemPlayerAccountNotificationBus, OnPutAccountRequestSuccess, job->result);
            
        }

        virtual void HandlePutAccountError(PutAccountRequestJob* job, AZ::EntityId entityId)
        {
            EBUS_EVENT_ID(entityId, CloudGemPlayerAccountNotificationBus, OnPutAccountRequestError, job->error);
        }
        
        virtual void HandleGetAccountSuccess(GetAccountRequestJob* job, AZ::EntityId entityId)
        {
            
            EBUS_EVENT_ID(entityId, CloudGemPlayerAccountNotificationBus, OnGetAccountRequestSuccess, job->result);
            
        }

        virtual void HandleGetAccountError(GetAccountRequestJob* job, AZ::EntityId entityId)
        {
            EBUS_EVENT_ID(entityId, CloudGemPlayerAccountNotificationBus, OnGetAccountRequestError, job->error);
        }
        
        virtual void HandleGetServiceStatusSuccess(GetServiceStatusRequestJob* job, AZ::EntityId entityId)
        {
            
            EBUS_EVENT_ID(entityId, CloudGemPlayerAccountNotificationBus, OnGetServiceStatusRequestSuccess, job->result);
            
        }

        virtual void HandleGetServiceStatusError(GetServiceStatusRequestJob* job, AZ::EntityId entityId)
        {
            EBUS_EVENT_ID(entityId, CloudGemPlayerAccountNotificationBus, OnGetServiceStatusRequestError, job->error);
        }
        
    };

    class CloudGemPlayerAccountClientComponent
        : public AZ::Component
        , public CloudGemPlayerAccountRequestBus::Handler
    {
    public:
        AZ_COMPONENT(CloudGemPlayerAccountClientComponent, LmbrAWS_CodeGen_Component_UUID);
        virtual ~CloudGemPlayerAccountClientComponent() = default;

        AZStd::shared_ptr<CloudGemPlayerAccountResponseHandler> m_defaultResponseHandler;

        void Init() override
        {
            m_defaultResponseHandler = AZStd::make_shared<CloudGemPlayerAccountResponseHandler>();
            CloudGemPlayerAccount::ServiceAPI::Configure();
        }

        void Activate() override
        {
            CloudGemPlayerAccountRequestBus::Handler::BusConnect(m_entity->GetId());
        }

        void Deactivate() override
        {
            CloudGemPlayerAccountRequestBus::Handler::BusDisconnect();
        }

        static void Reflect(AZ::ReflectContext* reflection)
        {
            
            
            UpdateAccountRequest::Reflect(reflection);
            
            
            
            AccountResponse::Reflect(reflection);
            
            
            
            ServiceStatus::Reflect(reflection);
            
            

            AZ::SerializeContext* serializeContext = azrtti_cast<AZ::SerializeContext*>(reflection);
            if (serializeContext)
            {
                // we must include any fields we want to expose to the editor or lua in the serialize context
                serializeContext->Class<CloudGemPlayerAccountClientComponent>()
                    ->Version(1);

                AZ::EditContext* editContext = serializeContext->GetEditContext();
                if (editContext)
                {
                    editContext->Class<CloudGemPlayerAccountClientComponent>("CloudGemPlayerAccountClientComponent", "CloudGemPlayerAccount Component")
                        ->ClassElement(AZ::Edit::ClassElements::EditorData, "")
                            ->Attribute(AZ::Edit::Attributes::Category, "Cloud Canvas Gems")
                            ->Attribute(AZ::Edit::Attributes::AppearsInAddComponentMenu, AZ_CRC("Game"));
                }
            }

            AZ::BehaviorContext* behaviorContext = azrtti_cast<AZ::BehaviorContext*>(reflection);
            if (behaviorContext)
            {
                behaviorContext->EBus<CloudGemPlayerAccountRequestBus>("CloudGemPlayerAccountRequestBus")
                    // one of these for each function
                    
                    ->Event("PutAccount", &CloudGemPlayerAccountRequestBus::Events::PutAccount)
                    
                    ->Event("GetAccount", &CloudGemPlayerAccountRequestBus::Events::GetAccount)
                    
                    ->Event("GetServiceStatus", &CloudGemPlayerAccountRequestBus::Events::GetServiceStatus)
                    
                    ;
                behaviorContext->EBus<CloudGemPlayerAccountNotificationBus>("CloudGemPlayerAccountNotificationBus")
                    ->Handler<BehaviorCloudGemPlayerAccountNotificationBusHandler>()
                ;
            }
        }

        // Functions from the swagger definitions
        
        
        void PutAccount(const UpdateAccountRequest& UpdateAccountRequest, CloudGemPlayerAccountResponseHandler* responseHandler) override
        
        {
            // Cache our entityId in case the entity goes away
            AZ::EntityId entityId;
            if (m_entity)
            {
                entityId = m_entity->GetId();
            }

            // Cache our default response handler in case this component goes away
            AZStd::shared_ptr < CloudGemPlayerAccountResponseHandler > defaultResponseHandler = m_defaultResponseHandler;

            // Create job
            PutAccountRequestJob* job = PutAccountRequestJob::Create(
                [responseHandler, defaultResponseHandler, entityId](PutAccountRequestJob* job)
                {
                    // handle success
                    CloudGemPlayerAccountResponseHandler* successHandler = responseHandler ? responseHandler : defaultResponseHandler.get();
                    if (successHandler)
                    {
                        successHandler->HandlePutAccountSuccess(job, entityId);
                    }
                },
                [responseHandler, defaultResponseHandler, entityId](PutAccountRequestJob* job)
                {
                    // handle error
                    CloudGemPlayerAccountResponseHandler* failureHandler = responseHandler ? responseHandler : defaultResponseHandler.get();
                    if (failureHandler)
                    {
                        failureHandler->HandlePutAccountError(job, entityId);
                    }
                }
            );
            
            job->parameters.UpdateAccountRequest = UpdateAccountRequest;
            
            
            
            job->Start();
        }
        
        
        void GetAccount(CloudGemPlayerAccountResponseHandler* responseHandler) override
        
        {
            // Cache our entityId in case the entity goes away
            AZ::EntityId entityId;
            if (m_entity)
            {
                entityId = m_entity->GetId();
            }

            // Cache our default response handler in case this component goes away
            AZStd::shared_ptr < CloudGemPlayerAccountResponseHandler > defaultResponseHandler = m_defaultResponseHandler;

            // Create job
            GetAccountRequestJob* job = GetAccountRequestJob::Create(
                [responseHandler, defaultResponseHandler, entityId](GetAccountRequestJob* job)
                {
                    // handle success
                    CloudGemPlayerAccountResponseHandler* successHandler = responseHandler ? responseHandler : defaultResponseHandler.get();
                    if (successHandler)
                    {
                        successHandler->HandleGetAccountSuccess(job, entityId);
                    }
                },
                [responseHandler, defaultResponseHandler, entityId](GetAccountRequestJob* job)
                {
                    // handle error
                    CloudGemPlayerAccountResponseHandler* failureHandler = responseHandler ? responseHandler : defaultResponseHandler.get();
                    if (failureHandler)
                    {
                        failureHandler->HandleGetAccountError(job, entityId);
                    }
                }
            );
            
            
            
            job->Start();
        }
        
        
        void GetServiceStatus(CloudGemPlayerAccountResponseHandler* responseHandler) override
        
        {
            // Cache our entityId in case the entity goes away
            AZ::EntityId entityId;
            if (m_entity)
            {
                entityId = m_entity->GetId();
            }

            // Cache our default response handler in case this component goes away
            AZStd::shared_ptr < CloudGemPlayerAccountResponseHandler > defaultResponseHandler = m_defaultResponseHandler;

            // Create job
            GetServiceStatusRequestJob* job = GetServiceStatusRequestJob::Create(
                [responseHandler, defaultResponseHandler, entityId](GetServiceStatusRequestJob* job)
                {
                    // handle success
                    CloudGemPlayerAccountResponseHandler* successHandler = responseHandler ? responseHandler : defaultResponseHandler.get();
                    if (successHandler)
                    {
                        successHandler->HandleGetServiceStatusSuccess(job, entityId);
                    }
                },
                [responseHandler, defaultResponseHandler, entityId](GetServiceStatusRequestJob* job)
                {
                    // handle error
                    CloudGemPlayerAccountResponseHandler* failureHandler = responseHandler ? responseHandler : defaultResponseHandler.get();
                    if (failureHandler)
                    {
                        failureHandler->HandleGetServiceStatusError(job, entityId);
                    }
                }
            );
            
            
            
            job->Start();
        }
        

    };

    
    
    bool UpdateAccountRequest::OnJsonKey(const char* key, CloudGemFramework::JsonReader& reader)
    {
        
        if (strcmp(key, "PlayerName") == 0) return reader.Accept(PlayerName);
        
        return reader.Ignore();
    }

    void UpdateAccountRequest::Reflect(AZ::ReflectContext* reflection)
    {
        AZ::SerializeContext* serializeContext = azrtti_cast<AZ::SerializeContext*>(reflection);

        if (serializeContext)
        {
            serializeContext->Class<UpdateAccountRequest>()
                ->Version(1);
        }

        AZ::BehaviorContext* behaviorContext = azrtti_cast<AZ::BehaviorContext*>(reflection);
        if (behaviorContext)
        {
            behaviorContext->Class<UpdateAccountRequest>("CloudGemPlayerAccount_UpdateAccountRequest")
                ->Attribute(AZ::Script::Attributes::Storage, AZ::Script::Attributes::StorageType::Value)
            
                ->Property("PlayerName", BehaviorValueProperty(&UpdateAccountRequest::PlayerName))
            
            ;
        }
    }
    
    
    
    bool AccountResponse::OnJsonKey(const char* key, CloudGemFramework::JsonReader& reader)
    {
        
        if (strcmp(key, "PlayerName") == 0) return reader.Accept(PlayerName);
        
        if (strcmp(key, "AccountId") == 0) return reader.Accept(AccountId);
        
        return reader.Ignore();
    }

    void AccountResponse::Reflect(AZ::ReflectContext* reflection)
    {
        AZ::SerializeContext* serializeContext = azrtti_cast<AZ::SerializeContext*>(reflection);

        if (serializeContext)
        {
            serializeContext->Class<AccountResponse>()
                ->Version(1);
        }

        AZ::BehaviorContext* behaviorContext = azrtti_cast<AZ::BehaviorContext*>(reflection);
        if (behaviorContext)
        {
            behaviorContext->Class<AccountResponse>("CloudGemPlayerAccount_AccountResponse")
                ->Attribute(AZ::Script::Attributes::Storage, AZ::Script::Attributes::StorageType::Value)
            
                ->Property("PlayerName", BehaviorValueProperty(&AccountResponse::PlayerName))
            
                ->Property("AccountId", BehaviorValueProperty(&AccountResponse::AccountId))
            
            ;
        }
    }
    
    
    
    bool ServiceStatus::OnJsonKey(const char* key, CloudGemFramework::JsonReader& reader)
    {
        
        if (strcmp(key, "status") == 0) return reader.Accept(status);
        
        return reader.Ignore();
    }

    void ServiceStatus::Reflect(AZ::ReflectContext* reflection)
    {
        AZ::SerializeContext* serializeContext = azrtti_cast<AZ::SerializeContext*>(reflection);

        if (serializeContext)
        {
            serializeContext->Class<ServiceStatus>()
                ->Version(1);
        }

        AZ::BehaviorContext* behaviorContext = azrtti_cast<AZ::BehaviorContext*>(reflection);
        if (behaviorContext)
        {
            behaviorContext->Class<ServiceStatus>("CloudGemPlayerAccount_ServiceStatus")
                ->Attribute(AZ::Script::Attributes::Storage, AZ::Script::Attributes::StorageType::Value)
            
                ->Property("status", BehaviorValueProperty(&ServiceStatus::status))
            
            ;
        }
    }
    
    
} // ServiceAPI
} // CloudGemPlayerAccount