########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.CryEngineModule(
        # Settings
        target          = 'LyShine',
        vs_filter       = 'CryEngine/LyShine',
        file_list       = 'lyshine.waf_files',
        platforms       = ['all'],
        configurations  = ['all'],
        pch             = 'StdAfx.cpp',
        
        use             = ['AzFramework'],
        uselib          = ['BOOST'],
        includes        = [ '.' ],

        win_features        = ['crcfix'],

        # Testing
        test_all_file_list = ['lyshine_test.waf_files'],
    )