########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################
def build(bld):

########################################################################################
# We need to build a /dev relative path, otherwise we will get a gem/code relative path
########################################################################################
    import os
    driver_node = bld.path.find_or_declare('Gems/ScriptCanvas/Code/Include/ScriptCanvas/')
    gem_node = bld.path.find_or_declare('Gems/StartingPointInput/Code/')
    script_canvas_dir = driver_node.path_from(gem_node)
########################################################################################

    AZ_CODEGEN_ARGS = az_code_gen = [{
                'files'   : ['Source/InputNode.h',],
                'scripts' : [os.path.join(script_canvas_dir, 'CodeGen/Drivers/ScriptCanvasNode.py')],
                'arguments' : [
                                #'-OnlyRunDiagnosticsOnMainFile=true',
                                #'-SuppressDiagnostics=false',
                                #'-SuppressErrorsAsWarnings=false',
                                #'-output-redirection=file',
                                '-SuppressIncludeNotFoundError=false',
                            ],
                'options' : ['PrintOutputRedirectionFile']
            }]

    bld.DefineGem(
        use    = [ 'AzFramework', 'ScriptCanvas' ],
        includes = [ bld.Path('Code/CryEngine/CryAction'),
                     bld.Path('Code/CryEngine')
                      ],
        export_includes = [bld.Path('Code/CryEngine')],

        # Suppressing level 1 warning C4351 on windows
        # new behavior: elements of array 'array' will be default initialized
        # https://msdn.microsoft.com/en-us/library/1ywe7hcy.aspx
        msvc_cxxflags = ['/wd4351'],
        features        = ['az_code_gen'],
        win_defines = [],

        file_list = [ 'startingpointinput.waf_files' ],
        test_all_file_list  = ['startingpointinput_tests.waf_files'],

        az_code_gen = AZ_CODEGEN_ARGS,

        ########################################
        # Editor Gem configuration
        editor = dict(

            az_code_gen = AZ_CODEGEN_ARGS,
            file_list = [ 'startingpointinput_editor.waf_files' ],

        )


        ########################################
    )