########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################
def build(bld):

########################################################################################
# We need to build a /dev relative path, otherwise we will get a gem/code relative path
########################################################################################
    import os
    driver_node = bld.path.find_or_declare('Gems/ScriptCanvas/Code/Include/ScriptCanvas/')
    gem_node = bld.path.find_or_declare('Gems/StartingPointInput/Code/')
    script_canvas_dir = driver_node.path_from(gem_node)
########################################################################################

    bld.DefineGem(
        use    = [ 'AzFramework', 'ScriptCanvasGem' ],
        includes = [ bld.Path('Code/CryEngine/CryAction') ],
        # Suppressing level 1 warning C4351 on windows
        # new behavior: elements of array 'array' will be default initialized
        # https://msdn.microsoft.com/en-us/library/1ywe7hcy.aspx
        win_cxxflags = ['/wd4351'],
        features        = ['az_code_gen'],
        win_defines = [],

        az_code_gen = [
            {
                'files'   : [
                               #'Source/InputNode.h',
                            ],
                'scripts' : [os.path.join(script_canvas_dir, 'CodeGen/Drivers/ScriptCanvasNode.py')],
                'arguments' : [
                                '-OnlyRunDiagnosticsOnMainFile=true',
                                '-SuppressDiagnostics=false',
                                '-SuppressErrorsAsWarnings=false',
                                '-output-redirection=file',
                            ],
                'options' : ['PrintOutputRedirectionFile']
            }
        ],
    )