########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.DefineGem(
        includes        = [ bld.Path('Code/CryEngine/CryAction') ],
        disable_tests   = (bld.env['PLATFORM'] != 'project_generator') and ('darwin' in bld.env['PLATFORM']),

        editor = dict(
            features    = ['qt5'],
            uselib      = ['QT5CORE','QT5GUI','QT5WIDGETS', 'QT5NETWORK'], # this lib depends on EditorLib, which depends on NewsShared, which depends on Qt5Network
            defines     = ['CAMERA_EDITOR',],
            includes    = [bld.Path('Code/CryEngine/CryAction'),
                           bld.Path('Code/Sandbox/Plugins/EditorCommon'),
                           bld.Path('Code/Sandbox/Editor'),
                           bld.Path('Code/Sandbox/Editor/Include'),
                           ],
            use         = ['EditorUI_QT','EditorCommon','EditorCore','EditorLib'],

            # AWS dependency is coming from EditorLib, which depends on LyMetrics, which uses AWS. Need to include the AWS libraries otherwise we get linker errors (undefined symbol)
            darwin_uselib = ['AWS_CPP_SDK_CORE',
                             'AWS_CPP_SDK_COGNITO_IDENTITY',
                             'AWS_CPP_SDK_MOBILEANALYTICS',
                             'AWS_CPP_SDK_IDENTITY_MANAGEMENT']
        ),

        win_features        = ['crcfix'],
    )
