########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.LumberyardApp(
        # Settings
        target              = 'crcfix',
        vs_filter           = 'Tools',
        file_list           = 'crcfix.waf_files',
        platforms           = ['win'],
        configurations      = ['all'],
        use                 = ['AzCore'],
        defines             = ['_CRT_SECURE_NO_WARNINGS'],

        ndebug_output_file_name      = 'crcfix',
        debug_output_file_name       = 'crcfixD',

        # Platform Specific
        win_x64_vs2013_output_folder = ['Tools/crcfix/bin/vc120/'],
        win_x64_vs2015_output_folder = ['Tools/crcfix/bin/vc140/'],
        win_x64_vs2017_output_folder = ['Tools/crcfix/bin/vc141/'],
        win_x64_clang_output_folder  = ['Tools/crcfix/bin/clang/'],

        win_x64_clang_cxxflags       = ['-Wno-int-to-void-pointer-cast',
                                        '-Wno-unknown-pragmas'],
    )
