########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

import os

def build(bld):

    defines     = [ 'ENGINE_EXPORTS' ]
    libpath     = [ bld.Path('Code/SDKs') ]
    includes    = [ ]
    win_lib     = [ 'dinput8', 'dxguid' ]

    bld.CryEngineModule(

        # Settings
        target             = 'CryInput',
        vs_filter          = 'CryEngine',
        copyright_org      = 'Amazon-CryTek',
        file_list          = 'cryinput.waf_files',
        platforms          = ['all'],
        configurations     = ['all'],
        pch                = 'StdAfx.cpp',
        defines            = defines,
        libpath            = libpath,
        use                = ['AzFramework'],
        includes           = includes,

        # Testing
        test_all_file_list = ['cryinput_test.waf_files'],
    )
