

def build(bld):
    import lumberyard_sdks

    file_list = []
    if bld.env['PLATFORM'] == 'project_generator':
        file_list.append('cloudgemspeechrecognition.waf_files')
        file_list.append('lmbraws_unsupported.waf_files')
    else:
        if lumberyard_sdks.does_platform_support_aws_native_sdk(bld):
            file_list.append('cloudgemspeechrecognition.waf_files')
        else:
            file_list.append('lmbraws_unsupported.waf_files')
            
    bld.DefineGem(
        file_list = file_list,
        ios_file_list = ['cloudgemspeechrecognition_cocoa.waf_files'],
        darwin_file_list = ['cloudgemspeechrecognition_cocoa.waf_files'],
        includes    = [
            bld.Path('Code/CryEngine/CryAction')
        ],
        uselib = ['AWS_CPP_SDK_CORE', 'AWS_CPP_SDK_LAMBDA'],
        use = ['CloudGemFrameworkStaticLibrary', 'Microphone'],

        darwin_framework    = ['AVFoundation'],
        ios_framework  = ['AVFoundation']

    )
