########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.CryEngineModule(
        target              = 'SceneCore',
        vs_filter           = 'Tools/SceneAPI',
        file_list           = 'scenecore.waf_files',
        platforms           = ['win', 'darwin'],
        configurations      = ['debug', 'debug_test', 'profile', 'profile_test'],
        disable_pch         = True,
        includes            = [ bld.Path('Code/Tools') ],
        use                 = [ 'AzCore', 'AzFramework', 'AzToolsFramework', 'GFxFramework' ],
        defines             = [ 'SCENE_CORE_EXPORTS', '_HAS_EXCEPTIONS=0' ],
        features            = [ 'crcfix', 'link_running_program' ],

        output_sub_folder_copy = 'rc',

        #==============================
        # Testing
        #==============================
        test_all_file_list = 'scenecore_testing.waf_files',
    )
