########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    COMMON_DEFINES = ['SCRIPTCANVASDEVELOPER', 'NOT_USE_CRY_MEMORY_MANAGER', 'AZCORE_ENABLE_MEMORY_TRACKING']

    bld.DefineGem(

        includes            = [ 'Include' ],
        export_includes     = [ 'Include' ],

        defines             = COMMON_DEFINES,

        platforms           = ['all'],
        configurations      = ['all'],

        vs_filter           = 'Gems/ScriptCanvas',

        pch                 = 'Source/precompiled.cpp',
        win_features        = ['crcfix'],

        file_list           = ['scriptcanvasdeveloper_gem_game.waf_files', 'scriptcanvasdeveloper_gem_common.waf_files'],
        test_all_file_list  = ['scriptcanvasdeveloper_gem_tests.waf_files'],


        ########################################
        # Editor Gem configuration
        editor = dict(
            defines         = ['SCRIPTCANVASDEVELOPER_EDITOR'] + COMMON_DEFINES,

            features        = ['qt5'],
            platforms       = ['win','darwin'],
            configurations  = ['debug', 'profile'],
            vs_filter       = 'Gems/ScriptCanvas',

            file_list   = ['scriptcanvasdeveloper_gem_editor.waf_files', 'scriptcanvasdeveloper_gem_common.waf_files'],
            includes        = [ 'Include',
                                'Editor/Include',
                                'Editor/Source',
                                'Source'
                                ],

            use = ['GraphCanvasWidgets', 'ScriptCanvasEditor'] + bld.make_aws_library_task_list(['LyMetricsProducer', 'LyMetricsShared', 'LyIdentity']),
            uselib     = ['AWS_CPP_SDK_CORE',
                          'AWS_CPP_SDK_COGNITO_IDENTITY',
                          'AWS_CPP_SDK_MOBILEANALYTICS',
                          'AWS_CPP_SDK_IDENTITY_MANAGEMENT'],

            export_includes  = [ 'Editor/Include' ],

            pch                 = 'Source/precompiled.cpp',

            # Platform Specific
            win_features    = ['crcfix'],

        )
        ########################################
    )

