/*
* All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
* its licensors.
*
* For complete copyright and license terms please see the LICENSE at the root of this
* distribution (the "License"). All use of this software is governed by the License,
* or, if provided, by the license below or the license accompanying this file. Do not
* remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*
*/
#pragma once

#include <AzCore/Component/Entity.h>

#include <gmock/gmock.h>
#include <LyShine/Bus/UiDynamicScrollBoxBus.h>

// the following was generated using google's python script to autogenerate mocks.
// however, it needed some hand-editing to make it work, so if you add functions to IRenderer,
// it will probably be better to just manually add them here than try to run the script again
// hand-edits are marked with 'hand-edit'.  Everything else was autogenerated.

#if defined(AZ_COMPILER_MSVC) 
// 4373 is generated by google mock on VS2015 only.  It warns that this code is not going to compile
// on VS2013 and earlier.  Because VS2015 was a transitionary VS, MS added a bunch of warnings like this, 
// warning developers when they were writing code that would not be backwards compatible with the non-standard
// VS2013 and earlier.  Google mock generates code that falls in this category but this is something we can
// safely ignore, as our software is for versions later than that.
#pragma warning(push)
#pragma warning(disable:4373) 
#endif // AZ_COMPILER_MSVC

using ::testing::_;

class UiDynamicScrollBoxDataBusHandlerMock
    : public AZ::Component
    , public UiDynamicScrollBoxDataBus::Handler

{
public:
    AZ_COMPONENT(UiDynamicScrollBoxDataBusHandlerMock, "{5CBD9592-FD20-492B-BC24-4AEA8935AEA4}")

    // Just a mock object, no reflection necessary
    static void Reflect(AZ::ReflectContext*) {}

    void Activate() override
    {
        UiDynamicScrollBoxDataBus::Handler::BusConnect(GetEntityId());
    }

    void Deactivate() override
    {
        UiDynamicScrollBoxDataBus::Handler::BusDisconnect();
    }


    MOCK_METHOD0(GetNumElements, int ());
    MOCK_METHOD1(GetElementWidth, float (int));
    MOCK_METHOD1(GetElementHeight, float (int));
    MOCK_METHOD0(GetNumSections, int ());
};

#if defined(AZ_COMPILER_MSVC) 
#pragma warning(pop)
#endif // AZ_COMPILER MSVC
