########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    import os

    driver_node = bld.path.find_or_declare('Gems/ScriptCanvas/Code/Include/ScriptCanvas/')
    gem_node = bld.path.find_or_declare('Gems/GraphicsReflectContext/Code')
    script_canvas_dir = driver_node.path_from(gem_node)

    CODEGEN_FILE_LIST = [
        'Source/SetColorChartNode.h',
        'Source/ScreenFaderNode.h',
    ]
                
    bld.DefineGem(
        # Add custom build options here
        includes    = [bld.Path('Code/CryEngine/CryCommon'),
                       bld.Path('Code/CryEngine/CryAction')
                      ],
        pch         = 'Source/Precompiled.cpp', 

        features        = ['az_code_gen'],
        
        win_features    = ['crcfix'],
        
        az_code_gen = [
            {
                'files'   : CODEGEN_FILE_LIST,
                'scripts' : [os.path.join(script_canvas_dir, 'CodeGen/Drivers/ScriptCanvasNode.py')],
            }
        ],
    )
