/*
* All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
* its licensors.
*
* For complete copyright and license terms please see the LICENSE at the root of this
* distribution (the "License"). All use of this software is governed by the License,
* or, if provided, by the license below or the license accompanying this file. Do not
* remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*
*/
/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////
// THIS CODE IS AUTOGENERATED, DO NOT MODIFY
/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////
#pragma once
#include <AzCore/Component/Component.h>
#include <AzCore/Component/Entity.h>
#include <AzCore/Component/ComponentBus.h>
#include <AzCore/EBus/EBus.h>
#include <AzCore/Memory/SystemAllocator.h>
#include <AzCore/RTTI/BehaviorContext.h>
#include <AzCore/Serialization/EditContext.h>
#include <AzCore/Serialization/SerializeContext.h>
#include <AzCore/std/smart_ptr/make_shared.h>
#include <AzCore/std/smart_ptr/shared_ptr.h>
#include <AzCore/std/string/conversions.h>

#if defined (PLATFORM_SUPPORTS_AWS_NATIVE_SDK)
#include <aws/core/http/HttpRequest.h>
#include <aws/core/http/HttpResponse.h>
#endif // (PLATFORM_SUPPORTS_AWS_NATIVE_SDK)

#include <CloudGemFramework/ServiceRequestJob.h>

#include "CloudGemSpeechRecognition_precompiled.h"

namespace CloudGemSpeechRecognition {
namespace ServiceAPI {
    
    extern const char* LmbrAWS_CodeGen_PostAudioResponse_UUID;
    
    extern const char* LmbrAWS_CodeGen_Component_UUID;
    
    extern const char* LmbrAWS_CodeGen_ResponseHandler_UUID;
    
    extern const char* LmbrAWS_CodeGen_PostTextRequest_UUID;
    
    extern const char* LmbrAWS_CodeGen_NotificationBus1_UUID;
    
    extern const char* LmbrAWS_CodeGen_RequestBus1_UUID;
    
    extern const char* LmbrAWS_CodeGen_ServiceStatus_UUID;
    
    extern const char* LmbrAWS_CodeGen_PostAudioRequest_UUID;
    

    // redefs
    

    bool WriteJson(CloudGemFramework::JsonWriter& writer, const int& item);

    bool WriteJson(CloudGemFramework::JsonWriter& writer, const AZStd::string& item);

    bool WriteJson(CloudGemFramework::JsonWriter& writer, const double& item);

    
    
    struct PostTextRequest
    {

        AZ_TYPE_INFO(PostTextRequest, LmbrAWS_CodeGen_PostTextRequest_UUID)
        AZ_CLASS_ALLOCATOR(PostTextRequest, AZ::SystemAllocator, 0)

        
        AZStd::string text;
        
        AZStd::string session_attributes;
        
        AZStd::string user_id;
        
        AZStd::string name;
        
        AZStd::string bot_alias;
        

        bool OnJsonKey(const char* key, CloudGemFramework::JsonReader& reader);

        static void Reflect(AZ::ReflectContext* reflection);
    };

    bool WriteJson(CloudGemFramework::JsonWriter& writer, const PostTextRequest& item);
    
    
    
    struct PostAudioResponse
    {

        AZ_TYPE_INFO(PostAudioResponse, LmbrAWS_CodeGen_PostAudioResponse_UUID)
        AZ_CLASS_ALLOCATOR(PostAudioResponse, AZ::SystemAllocator, 0)

        
        AZStd::string slot_to_elicit;
        
        AZStd::string session_attributes;
        
        AZStd::string intent;
        
        AZStd::string input_transcript;
        
        AZStd::string dialog_state;
        
        AZStd::string slots;
        
        AZStd::string message;
        

        bool OnJsonKey(const char* key, CloudGemFramework::JsonReader& reader);

        static void Reflect(AZ::ReflectContext* reflection);
    };

    bool WriteJson(CloudGemFramework::JsonWriter& writer, const PostAudioResponse& item);
    
    
    
    struct ServiceStatus
    {

        AZ_TYPE_INFO(ServiceStatus, LmbrAWS_CodeGen_ServiceStatus_UUID)
        AZ_CLASS_ALLOCATOR(ServiceStatus, AZ::SystemAllocator, 0)

        
        AZStd::string status;
        

        bool OnJsonKey(const char* key, CloudGemFramework::JsonReader& reader);

        static void Reflect(AZ::ReflectContext* reflection);
    };

    bool WriteJson(CloudGemFramework::JsonWriter& writer, const ServiceStatus& item);
    
    
    
    struct PostAudioRequest
    {

        AZ_TYPE_INFO(PostAudioRequest, LmbrAWS_CodeGen_PostAudioRequest_UUID)
        AZ_CLASS_ALLOCATOR(PostAudioRequest, AZ::SystemAllocator, 0)

        
        AZStd::string session_attributes;
        
        AZStd::string audio;
        
        AZStd::string user_id;
        
        AZStd::string name;
        
        AZStd::string bot_alias;
        

        bool OnJsonKey(const char* key, CloudGemFramework::JsonReader& reader);

        static void Reflect(AZ::ReflectContext* reflection);
    };

    bool WriteJson(CloudGemFramework::JsonWriter& writer, const PostAudioRequest& item);
    
    


    // Service RequestJobs
    CLOUD_GEM_SERVICE(CloudGemSpeechRecognition);


    
    class PostServicePosttextRequest
        : public CloudGemFramework::ServiceRequest
    {
    public:
        SERVICE_REQUEST(CloudGemSpeechRecognition, HttpMethod::HTTP_POST, "/service/posttext");

        struct Parameters
        {
            
            PostTextRequest post_text;
            

            bool BuildRequest(CloudGemFramework::RequestBuilder& request);

            bool WriteJson(CloudGemFramework::JsonWriter& writer) const;
        };

        
        PostAudioResponse result;
        

        Parameters parameters;
    };


    using PostServicePosttextRequestJob = CloudGemFramework::ServiceRequestJob<PostServicePosttextRequest>;
    
    class GetServiceStatusRequest
        : public CloudGemFramework::ServiceRequest
    {
    public:
        SERVICE_REQUEST(CloudGemSpeechRecognition, HttpMethod::HTTP_GET, "/service/status");

        struct Parameters
        {
            

            bool BuildRequest(CloudGemFramework::RequestBuilder& request);

            bool WriteJson(CloudGemFramework::JsonWriter& writer) const;
        };

        
        ServiceStatus result;
        

        Parameters parameters;
    };


    using GetServiceStatusRequestJob = CloudGemFramework::ServiceRequestJob<GetServiceStatusRequest>;
    
    class PostServicePostaudioRequest
        : public CloudGemFramework::ServiceRequest
    {
    public:
        SERVICE_REQUEST(CloudGemSpeechRecognition, HttpMethod::HTTP_POST, "/service/postaudio");

        struct Parameters
        {
            
            PostAudioRequest post_audio;
            

            bool BuildRequest(CloudGemFramework::RequestBuilder& request);

            bool WriteJson(CloudGemFramework::JsonWriter& writer) const;
        };

        
        PostAudioResponse result;
        

        Parameters parameters;
    };


    using PostServicePostaudioRequestJob = CloudGemFramework::ServiceRequestJob<PostServicePostaudioRequest>;
    


    // Notification bus for this component
    class CloudGemSpeechRecognitionNotifications
        : public AZ::ComponentBus
    {
    public:
        
        /**
         * Sent when the request is a success
         *
         * Params:
         *    jsonOutput:       The output receieved from the lambda call
         *    request:          The AWS Lambda request object
         */
        
        virtual void OnPostServicePosttextRequestSuccess(const PostAudioResponse response);
        

        /**
         * Sent when the request fails
         *
         * Params:
         *    error:           The output receieved from the lambda call,
         *                     could be function error or an issue with the request
         *    request:         The AWS Lambda request object
         */
        virtual void OnPostServicePosttextRequestError(const CloudGemFramework::Error error);
        
        /**
         * Sent when the request is a success
         *
         * Params:
         *    jsonOutput:       The output receieved from the lambda call
         *    request:          The AWS Lambda request object
         */
        
        virtual void OnGetServiceStatusRequestSuccess(const ServiceStatus response);
        

        /**
         * Sent when the request fails
         *
         * Params:
         *    error:           The output receieved from the lambda call,
         *                     could be function error or an issue with the request
         *    request:         The AWS Lambda request object
         */
        virtual void OnGetServiceStatusRequestError(const CloudGemFramework::Error error);
        
        /**
         * Sent when the request is a success
         *
         * Params:
         *    jsonOutput:       The output receieved from the lambda call
         *    request:          The AWS Lambda request object
         */
        
        virtual void OnPostServicePostaudioRequestSuccess(const PostAudioResponse response);
        

        /**
         * Sent when the request fails
         *
         * Params:
         *    error:           The output receieved from the lambda call,
         *                     could be function error or an issue with the request
         *    request:         The AWS Lambda request object
         */
        virtual void OnPostServicePostaudioRequestError(const CloudGemFramework::Error error);
        
    };

    using CloudGemSpeechRecognitionNotificationBus = AZ::EBus<CloudGemSpeechRecognitionNotifications>;

    class BehaviorCloudGemSpeechRecognitionNotificationBusHandler
        : public CloudGemSpeechRecognitionNotificationBus::Handler, public AZ::BehaviorEBusHandler
    {
    public:
        AZ_EBUS_BEHAVIOR_BINDER(BehaviorCloudGemSpeechRecognitionNotificationBusHandler, LmbrAWS_CodeGen_NotificationBus1_UUID, AZ::SystemAllocator
        
        , OnPostServicePosttextRequestSuccess
        , OnPostServicePosttextRequestError
        
        , OnGetServiceStatusRequestSuccess
        , OnGetServiceStatusRequestError
        
        , OnPostServicePostaudioRequestSuccess
        , OnPostServicePostaudioRequestError
        
        );
        
        
        void OnPostServicePosttextRequestSuccess(const PostAudioResponse response) override;
        
        void OnPostServicePosttextRequestError(const CloudGemFramework::Error error) override;
        
        
        void OnGetServiceStatusRequestSuccess(const ServiceStatus response) override;
        
        void OnGetServiceStatusRequestError(const CloudGemFramework::Error error) override;
        
        
        void OnPostServicePostaudioRequestSuccess(const PostAudioResponse response) override;
        
        void OnPostServicePostaudioRequestError(const CloudGemFramework::Error error) override;
        
    };
    class CloudGemSpeechRecognitionResponseHandler;

    // Request bus for this component
    class CloudGemSpeechRecognitionRequests
        : public AZ::ComponentBus
    {
    public:
        virtual ~CloudGemSpeechRecognitionRequests() {}
        
        
        virtual void PostServicePosttext(const PostTextRequest& post_text, CloudGemSpeechRecognitionResponseHandler* responseHandler);
        
        
        
        virtual void GetServiceStatus(CloudGemSpeechRecognitionResponseHandler* responseHandler);
        
        
        
        virtual void PostServicePostaudio(const PostAudioRequest& post_audio, CloudGemSpeechRecognitionResponseHandler* responseHandler);
        
        
    };

    using CloudGemSpeechRecognitionRequestBus = AZ::EBus<CloudGemSpeechRecognitionRequests>;

    // This class is used as a parameter for all requests and throws the response on the CloudGemSpeechRecognitionNotificationBus
    // Inherit from this to define custom behavior.
    class CloudGemSpeechRecognitionResponseHandler
    {
    public:
        AZ_TYPE_INFO(CloudGemSpeechRecognitionResponseHandler, LmbrAWS_CodeGen_ResponseHandler_UUID)
        AZ_CLASS_ALLOCATOR(CloudGemSpeechRecognitionResponseHandler, AZ::SystemAllocator, 0)

        virtual ~CloudGemSpeechRecognitionResponseHandler() {}
        
        virtual void HandlePostServicePosttextSuccess(PostServicePosttextRequestJob* job, AZ::EntityId entityId);
        virtual void HandlePostServicePosttextError(PostServicePosttextRequestJob* job, AZ::EntityId entityId);
        
        virtual void HandleGetServiceStatusSuccess(GetServiceStatusRequestJob* job, AZ::EntityId entityId);
        virtual void HandleGetServiceStatusError(GetServiceStatusRequestJob* job, AZ::EntityId entityId);
        
        virtual void HandlePostServicePostaudioSuccess(PostServicePostaudioRequestJob* job, AZ::EntityId entityId);
        virtual void HandlePostServicePostaudioError(PostServicePostaudioRequestJob* job, AZ::EntityId entityId);
        
    };

    class CloudGemSpeechRecognitionClientComponent
        : public AZ::Component
        , public CloudGemSpeechRecognitionRequestBus::Handler
    {
    public:
        AZ_COMPONENT(CloudGemSpeechRecognitionClientComponent, LmbrAWS_CodeGen_Component_UUID);
        virtual ~CloudGemSpeechRecognitionClientComponent() = default;

        AZStd::shared_ptr<CloudGemSpeechRecognitionResponseHandler> m_defaultResponseHandler;

        void Init() override;

        void Activate() override;

        void Deactivate() override;

        static void Reflect(AZ::ReflectContext* reflection)
        {
            
            
            PostTextRequest::Reflect(reflection);
            
            
            
            PostAudioResponse::Reflect(reflection);
            
            
            
            ServiceStatus::Reflect(reflection);
            
            
            
            PostAudioRequest::Reflect(reflection);
            
            

            AZ::SerializeContext* serializeContext = azrtti_cast<AZ::SerializeContext*>(reflection);
            if (serializeContext)
            {
                // we must include any fields we want to expose to the editor or lua in the serialize context
                serializeContext->Class<CloudGemSpeechRecognitionClientComponent>()
                    ->Version(1);

                AZ::EditContext* editContext = serializeContext->GetEditContext();
                if (editContext)
                {
                    editContext->Class<CloudGemSpeechRecognitionClientComponent>("CloudGemSpeechRecognitionClientComponent", "CloudGemSpeechRecognition Component")
                        ->ClassElement(AZ::Edit::ClassElements::EditorData, "")
                            ->Attribute(AZ::Edit::Attributes::Category, "Cloud Canvas Gems")
                            ->Attribute(AZ::Edit::Attributes::AppearsInAddComponentMenu, AZ_CRC("Game"));
                }
            }

            AZ::BehaviorContext* behaviorContext = azrtti_cast<AZ::BehaviorContext*>(reflection);
            if (behaviorContext)
            {
                behaviorContext->EBus<CloudGemSpeechRecognitionRequestBus>("CloudGemSpeechRecognitionRequestBus")
                    // one of these for each function
                    
                    ->Event("PostServicePosttext", &CloudGemSpeechRecognitionRequestBus::Events::PostServicePosttext)
                    
                    ->Event("GetServiceStatus", &CloudGemSpeechRecognitionRequestBus::Events::GetServiceStatus)
                    
                    ->Event("PostServicePostaudio", &CloudGemSpeechRecognitionRequestBus::Events::PostServicePostaudio)
                    
                    ;
                behaviorContext->EBus<CloudGemSpeechRecognitionNotificationBus>("CloudGemSpeechRecognitionNotificationBus")
                    ->Handler<BehaviorCloudGemSpeechRecognitionNotificationBusHandler>()
                ;
            }
        }

        // Functions from the swagger definitions
        
        
        void PostServicePosttext(const PostTextRequest& post_text, CloudGemSpeechRecognitionResponseHandler* responseHandler) override;
        
        
        
        void GetServiceStatus(CloudGemSpeechRecognitionResponseHandler* responseHandler) override;
        
        
        
        void PostServicePostaudio(const PostAudioRequest& post_audio, CloudGemSpeechRecognitionResponseHandler* responseHandler) override;
        
        
    };
} // ServiceAPI
} // CloudGemSpeechRecognition