########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

SUBFOLDERS = [
    'bootstrap'
    ]

def build(bld):

    bld.LumberyardApp(
        # Settings
        target              = 'AzTestRunner',
        vs_filter           = 'Tools/AzTestRunner',
        file_list           = 'aztestscanner.waf_files',
        platforms           = ['win', 'linux_x64', 'darwin_x64'],
        configurations      = ['test_all'],
        use                 = ['AzTest'],
        uselib              = ['GMOCK'],

        # Platform Specific
        win_file_list       = 'aztestscanner_win.waf_files',
        linux_file_list     = 'aztestscanner_linux.waf_files',
        darwin_file_list    = 'aztestscanner_osx.waf_files',
        darwin_rpath        = ['@executable_path', '@executable_path/rc', '@executable_path/qtlibs/lib'],
    )

    bld.recurse(SUBFOLDERS, mandatory=False)