########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################
def build(bld):

########################################################################################
# We need to build a /dev relative path, otherwise we will get a gem/code relative path
########################################################################################
    import os
    driver_node = bld.path.find_or_declare('Gems/ScriptCanvas/Code/Include/ScriptCanvas')
    gem_node = bld.path.find_or_declare('Gems/ScriptCanvasDiagnosticLibrary/Code/')
    script_canvas_dir = driver_node.path_from(gem_node)
########################################################################################

    AZ_CODEGEN_ARGS = az_code_gen = [{
                'files'   : ['Source/Log.h',
                             'Source/DrawText.h'
                             ],

                'scripts' : [os.path.join(script_canvas_dir, 'CodeGen/Drivers/ScriptCanvasNode.py')],
            }]

    bld.DefineGem(

        pch         = "Source/precompiled.cpp",

        platforms       = ['all'],
        configurations  = ['all'],
        features        = ['az_code_gen'],
        vs_filter       = 'Gems/ScriptCanvas',
        defines         = ['SCRIPTCANVAS', 'SCRIPTCANVAS_ERRORS_ENABLED', 'NOT_USE_CRY_MEMORY_MANAGER'],
        win_defines     = ['SCRIPTCANVAS_DIAGNOSTICS_CORE_EDITOR'],
        darwin_defines  = ['SCRIPTCANVAS_DIAGNOSTICS_CORE_EDITOR'],
        includes        = [ '.',
                            '..',
                            'Include',
                            'Source',
                            bld.Path('Code/Sandbox/Editor'),
                            bld.Path('Code/Sandbox/Editor/Include'),
                            bld.Path('Code/Sandbox/Plugins/EditorCommon'),
                            bld.Path('Code/Sandbox'),                            
                            bld.Path('Code/CryEngine') ],
        export_includes = ['.'],
        file_list = ['scriptcanvasdiagnosticlibrary_common.waf_files'],
        test_all_file_list = ['scriptcanvasdiagnosticlibrary_tests.waf_files'],
        
        android_file_list = ['scriptcanvasdiagnosticlibrary_game.waf_files'],
        appletv_file_list = ['scriptcanvasdiagnosticlibrary_game.waf_files'],
       
        ios_file_list = ['scriptcanvasdiagnosticlibrary_game.waf_files'],
        linux_file_list = ['scriptcanvasdiagnosticlibrary_game.waf_files'],
       
        
        darwin_file_list = ['scriptcanvasdiagnosticlibrary_editor.waf_files'],
        win_file_list = ['scriptcanvasdiagnosticlibrary_editor.waf_files'],

        # Suppressing level 1 warning C4351 on windows
        # new behavior: elements of array 'array' will be default initialized
        # https://msdn.microsoft.com/en-us/library/1ywe7hcy.aspx
        msvc_cxxflags = ['/wd4351', '/W3','/wd4251', '/wd4275'],

        az_code_gen = AZ_CODEGEN_ARGS,

         # Editor Gem configuration
        editor = dict(
            configurations  = ['debug', 'profile'],
            defines         = ['SCRIPTCANVASDIAGNOSTICSLIBRARY_EDITOR', 'NOT_USE_CRY_MEMORY_MANAGER'],
            win_defines     = ['SCRIPTCANVAS_DIAGNOSTICS_CORE_EDITOR'],
            darwin_defines  = ['SCRIPTCANVAS_DIAGNOSTICS_CORE_EDITOR'],
            features        = ['qt5', 'az_code_gen'],
            az_code_gen     = AZ_CODEGEN_ARGS,
            vs_filter       = 'Gems/ScriptCanvas',
            win_file_list       = ['scriptcanvasdiagnosticlibrary_common.waf_files', 'scriptcanvasdiagnosticlibrary_editor.waf_files'],
            win_use             = ['AzQtComponents','CryCommon','ScriptCanvas'],
            uselib          = ['QT5CORE',
                               'QT5QUICK',
                               'QT5QML',
                               'QT5GUI',
                               'QT5WIDGETS'],
            includes        = [ '.',
                                '..',
                                'Include',
                                'Source',
                                bld.Path('Code/CryEngine')
                                ],
            export_includes = ['.'],

        )
    )
