########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

import os
from waflib import Utils

SUBFOLDERS = [
    'Builders',
    'AssetBuilderSDK',
    'AssetBuilder'
]

def build(bld):

    bld.recurse(dirs=SUBFOLDERS) # mandatory - these folders are required

    defines         = ['RESOURCE_COMPILER',
                        'EXCLUDE_CINEMIZER_SDK',
                        'EXCLUDE_OCULUS_SDK',
                        'NOMINMAX',
                        'NOT_USE_CRY_MEMORY_MANAGER',
                        'UNICODE']

    console_defines  = defines + ['BATCH_MODE', 'UNIT_TEST']

    bld.CryQtApplication(

        # Settings
        target           = 'AssetProcessor',
        vs_filter        = 'Tools/AssetProcessor',
        file_list        = ['assetprocessor.waf_files', 'assetprocessor_gui.waf_files'],
        platforms        = ['win', 'darwin'],
        configurations   = ['debug_all', 'profile_all'],
        win_file_list    = ['assetprocessor_win.waf_files'],
        darwin_file_list = ['assetprocessor_gui_macos.waf_files'],
        disable_pch      = True,
        features         = ['qt5', 'link_running_program'],
        includes         = [bld.Path('Code/Tools/GemRegistry/include')],
        use             = ['AzToolsFramework',
                           'AzQtComponents',
                           'AssetBuilderSDK',
                           'ToolsCrashHandler'],
        uselib          = ['QTMAIN',
                           'QT5CORE',
                           'QT5GUI',
                           'QT5NETWORK',
                           'QT5SVG',
                           'QT5WIDGETS',
                           'QT5XML',
                           'BOOST',
                           'SQLITE'
                           ],
        defines         = defines,

        # Platform Specific
        win_copy_dependent_files = [ 'Bin64/d3dx11_43.dll',
                                     'Bin64/D3DCompiler_43.dll',
                                     'Bin64/d3dcompiler_46.dll',
                                     'Bin64/d3dcompiler_47.dll',
                                     'Bin64/libeay32.dll',
                                     'Bin64/LuaCompiler.exe',
                                     'Bin64/ffmpeg.exe',
                                     'Bin64/ssleay32.dll',
                                     'Bin64/xinput1_3.dll'],

        win_features    = ['generate_rc_file', 'crcfix'],
        win_includes    = ['native'],  # for the resource.h file
        win_lib         = ['shell32'],

        darwin_rpath      = ['@executable_path', '@executable_path/qtlibs/lib', '@executable_path/../Frameworks'],
        darwin_frameworks = ['CoreServices'],
        darwin_cxxflags   = [ '-x', 'objective-c++' ],
        darwin_xcassets   = 'Code/Tools/AssetProcessor/qml/Images.xcassets',
        darwin_x64_framework = ['Security'],
        darwin_lib        = ['bsm']
    )

    ###########################################################################################################################################
    
    bld.CryQtConsoleApplication(
        # Settings
        target          = 'AssetProcessorBatch',
        vs_filter       = 'Tools/AssetProcessor',
        file_list       = ['assetprocessor.waf_files', 'assetprocessor_unittest.waf_files'],
        win_file_list   = ['assetprocessor_win.waf_files'],
        darwin_file_list = ['assetprocessor_macos.waf_files'],
        platforms       = ['win', 'darwin'],
        configurations  = ['debug_all', 'profile_all'],
        disable_pch     = True,
        features        = ['qt5'],
        includes        = [bld.Path('Code/Tools/GemRegistry/include')],

        win_features    = ['generate_rc_file', 'crcfix'],
        win_includes    = ['native'],  # for the resource.h file
        use             = ['AzToolsFramework',
                           'AssetBuilderSDK'],
        uselib          = ['QT5CORE',
                           'QT5GUI',
                           'QT5NETWORK',
                           'QT5WIDGETS',
                           'SQLITE'],
        defines         = console_defines,

        # Platform Specific
        darwin_rpath    = ['@executable_path', '@executable_path/qtlibs/lib'],
        darwin_frameworks = ['CoreServices'],

        # ==============================
        # Testing
        # ==============================

        test_all_file_list = ['assetprocessor_test.waf_files'],
    )


def copy_asset_builder(pkg, executable_dest_node):
    output_folder_node = pkg.get_output_folders(pkg.platform, pkg.config)[0]
    pkg.install_files(executable_dest_node.abspath(), "AssetBuilder", cwd=output_folder_node, chmod=Utils.O755, postpone=False)

    rc_folder_node = output_folder_node.make_node('rc')
    rc_files = rc_folder_node.ant_glob("*")
    output_folder_node = output_folder_node.make_node('rc')
    resources_node = executable_dest_node.parent.make_node('Resources')
    rc_dest_node = executable_dest_node.make_node('rc')
    for file in rc_files:
        filename, file_extension = os.path.splitext(file.abspath())
        if file_extension in ['.ini', '.xml', '.txt']:
            # data files need to go into the Resources directory otherwise code signing fails 
            pkg.create_symlink_or_copy(file, resources_node.abspath(), postpone=False)
        else:
            # Need 0755 permissions as rc is an exeutable. 
            pkg.create_symlink_or_copy(file, rc_dest_node.abspath(), chmod=Utils.O755, postpone=False)


def package_darwin_x64(pkg):
    build(pkg) # Need to call this to generate our task_generator
    pkg.package_tool(
        target           = 'AssetProcessor',
        platforms        = ['darwin'],
        configurations   = ['debug', 'profile'],
        include_all_libs = True, 
        dir_resources    = ['qtlibs','Builders'],
        finalize_func    = copy_asset_builder,
    )

