########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

import os

SUBFOLDERS = [
    'Builders',
    'AssetBuilderSDK',
    'AssetBuilder'
]

def build(bld):

    bld.recurse(dirs=SUBFOLDERS) # mandatory - these folders are required

    defines         = ['RESOURCE_COMPILER',
                        'EXCLUDE_CINEMIZER_SDK',
                        'EXCLUDE_OCULUS_SDK',
                        'NOMINMAX',
                        'NOT_USE_CRY_MEMORY_MANAGER',
                        'UNICODE']

    console_defines  = defines + ['BATCH_MODE', 'UNIT_TEST']

    bld.CryQtApplication(

        # Settings
        target           = 'AssetProcessor',
        vs_filter        = 'Tools/AssetProcessor',
        file_list        = ['assetprocessor.waf_files', 'assetprocessor_gui.waf_files'],
        platforms        = ['win', 'darwin'],
        configurations   = ['debug_all', 'profile_all'],
        win_file_list    = ['assetprocessor_win.waf_files'],
        darwin_file_list = ['assetprocessor_macos.waf_files'],
        disable_pch      = True,
        features         = ['qt5', 'link_running_program'],
        includes         = [bld.Path('Code/Tools/GemRegistry/include')],
        use             = ['AzToolsFramework',
                           'AzQtComponents',
                           'AssetBuilderSDK',
                           'ToolsCrashHandler'],
        uselib          = ['QTMAIN',
                           'QT5CORE',
                           'QT5GUI',
                           'QT5NETWORK',
                           'QT5SVG',
                           'QT5WIDGETS',
                           'QT5XML',
                           'BOOST',
                           'SQLITE'
                           ],
        defines         = defines,

        # Platform Specific
        win_copy_dependent_files = [ 'Bin64/d3dx11_43.dll',
                                     'Bin64/D3DCompiler_43.dll',
                                     'Bin64/d3dcompiler_46.dll',
                                     'Bin64/d3dcompiler_47.dll',
                                     'Bin64/libeay32.dll',
                                     'Bin64/LuaCompiler.exe',
                                     'Bin64/ffmpeg.exe',
                                     'Bin64/ssleay32.dll',
                                     'Bin64/xinput1_3.dll'],

        win_features    = ['generate_rc_file', 'crcfix'],
        win_includes    = ['native'],  # for the resource.h file
        win_lib         = ['shell32'],

        darwin_rpath    = ['@executable_path', '@executable_path/qtlibs/lib'],
        darwin_frameworks = ['CoreServices'],
        darwin_cxxflags = [ '-x', 'objective-c++' ],
    )

    ###########################################################################################################################################
    
    bld.CryQtConsoleApplication(
        # Settings
        target          = 'AssetProcessorBatch',
        vs_filter       = 'Tools/AssetProcessor',
        file_list       = ['assetprocessor.waf_files', 'assetprocessor_unittest.waf_files'],
        win_file_list   = ['assetprocessor_win.waf_files'],
        darwin_file_list = ['assetprocessor_macos.waf_files'],
        platforms       = ['win', 'darwin'],
        configurations  = ['debug_all', 'profile_all'],
        disable_pch     = True,
        features        = ['qt5'],
        includes        = [bld.Path('Code/Tools/GemRegistry/include')],

        win_features    = ['generate_rc_file', 'crcfix'],
        win_includes    = ['native'],  # for the resource.h file
        use             = ['AzToolsFramework',
                           'AssetBuilderSDK'],
        uselib          = ['QT5CORE',
                           'QT5GUI',
                           'QT5NETWORK',
                           'QT5WIDGETS',
                           'SQLITE'],
        defines         = console_defines,

        # Platform Specific
        darwin_rpath    = ['@executable_path', '@executable_path/qtlibs/lib'],
        darwin_frameworks = ['CoreServices'],

        # ==============================
        # Testing
        # ==============================
        win_test_all_file_list = ['assetprocessor_test.waf_files'],

        #because gmock still crashes (unrelated to AP) in Darwin-Debug, we'll at least enable tests in profile_test.
        darwin_test_profile_file_list = ['assetprocessor_test.waf_files']

    )


