########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.CryDedicatedServer(
        target              = 'DedicatedLauncher',
        platforms           = ['win'],
        configurations      = ['all'],
        server_only         = True,
        use                 = ['CryRenderNULL',
                               'AzGameFramework'],
        includes            = [bld.Path('Code/Launcher')],

        debug_uselib        = ['AWS_GAMELIFT_SERVER_SHARED'],
        profile_uselib      = ['AWS_GAMELIFT_SERVER_SHARED'],
        performance_uselib  = ['AWS_GAMELIFT_SERVER_STATIC'],
        release_uselib      = ['AWS_GAMELIFT_SERVER_STATIC'],

        file_list           = 'launcher.waf_files',
        lib                 = 'Shell32',
    )
