########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################


SUBFOLDERS = [
    'Framework',
    'CryEngine',
    'Engine',
    'LauncherUnified',
    'Sandbox',
    'Tools',
    'UnitTestLauncher',
    'Lyzard',
    'GFXPrefabLab'
]

def build(bld):

    # Setting 'enable_legacy_terrain' to False will have two consequences:
    #   1- Editor Tools to edit/create Legacy Terrain won't be available at all (and completely compiled out).
    #   2- The Legacy Terrain Runtime won't be available at all (and completely compiled out).
    # This is useful for customers who don't need Terrain in their games or choose
    # to write their own terrain runtime.
    setattr(bld, 'enable_legacy_terrain', True)

    # do not add game projects here.  They will be added automatically based on what
    # game projects you have enabled in your user settings, from the list defined in projects.json
    bld.recurse(SUBFOLDERS, mandatory=False)
