########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################


SUBFOLDERS = [
    'Framework',
    'CryEngine',
    'Engine',
    'LauncherUnified',
    'Sandbox',
    'Tools',
    'UnitTestLauncher',
    'Lyzard',
    'GFXPrefabLab',
    'Viewers'
]

def build(bld):
    
    # Set whether to enable CryPhysics
    # Disabling cryphysics is a very experimental feature and it's not encouraged for production
    setattr(bld, 'enable_cry_physics', True)

    # do not add game projects here.  They will be added automatically based on what
    # game projects you have enabled in your user settings, from the list defined in projects.json
    bld.recurse(SUBFOLDERS, mandatory=False)
