########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):

    bld.CryEngineModule(

        # Settings
        target             = 'CryAISystem',
        vs_filter          = 'CryEngine',
        copyright_org      = 'Amazon-CryTek',
        file_list          = ['cryaisystem.waf_files'],
        pch                = 'StdAfx.cpp',
        platforms          = ['all'],
        configurations     = ['all'],
        use                = ['AzFramework'],
        use_required_gems  = True,

        # Platform Specific
       

        darwin_cxxflags     = ['-Wno-shadow'],

        ios_cxxflags        = ['-Wno-shadow'],

        appletv_cxxflags    = ['-Wno-shadow'],

        android_armv7_clang_cxxflags  = ['-Wno-shadow'],
        defines            = ['ENGINE_EXPORTS'],

        # Testing
        test_all_file_list = ['cryaisystem_test.waf_files'],
    )
