########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################


def build(bld):

    # ScriptEvents commmon code is in a static library.
    bld.CryEngineStaticLibrary(

        target          = 'ScriptEventsStatic',
        vs_filter       = 'Gems/ScriptEvents',

        #pch              = 'precompiled.cpp',
        win_features     = ['crcfix'],

        includes        = ['Include', 'Include/ScriptEvents', 'Source'],
        export_includes = ['.', 'Include', 'Include/ScriptCanvas'],

        use             = ['AzCore', 'AzFramework'],

        platforms       = ['all'],
        configurations  = ['all'],
        file_list       = ['scriptevents_common.waf_files'],
        disable_pch     = True
    )


    bld.DefineGem(

        pch                 = 'Source/precompiled.cpp',
        win_features        = ['crcfix'],
        includes            = ['Include', 'Include/ScriptEvents'],

        
        file_list           = ['scriptevents_common.waf_files', 'scriptevents.waf_files'],
        vs_filter           = 'Gems/ScriptEvents',

        use                 = ['ScriptEventsStatic'],

        test_all_file_list = ['scriptevents_tests.waf_files'],

        editor = dict(
            pch             = 'Source/precompiled.cpp',
            features        = ['qt5'],
            uselib          = ['QT5CORE','QT5GUI','QT5WIDGETS'],
            defines         = ['SCRIPTEVENTS_EDITOR',],
            includes        = [bld.Path('Code/Sandbox/Plugins/EditorCommon'),
                               bld.Path('Code/Sandbox/Editor'),
                               bld.Path('Code/Sandbox/Editor/Include')
                               ],
            
            export_includes = ['.'],
            vs_filter       = 'Gems/ScriptEvents',

            file_list       = ['scriptevents_common.waf_files', 'scriptevents_editor.waf_files'],
            use             = ['ScriptEventsStatic','EditorUI_QT','EditorCommon','EditorCore','AzToolsFramework'],
            configurations  = ['debug', 'profile'],

            win_features    = ['crcfix'],
        ),
    )
