########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.CryEngineModule(
        target              = 'GridMateTests',
        vs_filter           = 'Network',
        file_list           = 'gridmate_test.waf_files',
        platforms           = ['win'],
        configurations      = ['all'],
        test_only           = True,
        disable_pch         = True,
        use                 = ['AzTest', 'AzCore', 'GridMate'],
        uselib              = ['GMOCK', 'OPENSSL'],   

        # Compiler Specific
        msvc_cxxflags       = [
                               '/W4', # warning level
                              ],

        # Platform Specific
        win_features        = ['crcfix'],
        win_lib             = ['Ws2_32', 'Mswsock', 'gdi32'],
    )

