########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):
    _, configuration = bld.get_platform_and_configuration()

    # This is a client only gem but we need to build a minimal stub to be loaded
    if 'dedicated' in configuration:
        bld.DefineGem(
            file_list = ['sceneloggingexample_stub.waf_files'],
            disable_pch = True,
            disable_tests = True
        )
    else:
        bld.DefineGem(
            includes    = [ bld.Path('Code/CryEngine/CryCommon'),
                            bld.Path('Code/Tools')
                          ],
            use         = ['SceneCore'],
            features    = ['crcfix'],
            disable_pch = True
        )
