########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):

    #By default the engine builds the legacy terrain runtime.
    #Setting enableLegacyTerrainRuntime to false, will completely remove code and symbols
    #required by the legacy terrain runtime.
    #This is useful for customers who don't need Terrain in their games or choose
    #to write their own terrain runtime.
    enableLegacyTerrainRuntime = getattr(bld, 'enable_legacy_terrain', True)

    fileList = ['cry3dengine.waf_files']
    defines = []
    if enableLegacyTerrainRuntime:
        defines.append('LY_TERRAIN_LEGACY_RUNTIME')
        fileList.append('cry3dengine_terrain.waf_files')

    bld.CryEngineModule(

        # Settings
        target             = 'Cry3DEngine',
        vs_filter          = 'CryEngine',
        copyright_org      = 'Amazon-CryTek',
        file_list          = fileList,
        pch                = 'StdAfx.cpp',
        platforms          = ['all'],
        configurations     = ['all'],
        use                = [ 'AzFramework' ],
        win_features       = ['crcfix'],
        includes           = [bld.Path('Code/CryEngine/CryCommon'),
                              bld.ThirdPartyPath('mikkt')
                             ],
        defines            = defines,

        # Testing
        test_all_file_list = ['cry3dengine_test.waf_files'],
    )
