########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

import os

def build(bld):


    bld.BuilderPlugin(
        target             = 'TranslationBuilder',
        vs_filter          = 'Tools/AssetProcessor/Builders',
        file_list          = ['translationbuilder.waf_files'],
        platforms          = ['win', 'darwin'],
        configurations     = ['all'],
        exclude_monolithic = True,
        disable_pch        = True,
        
        # Necessary to add the uselib here to avoid linker errors on Uber builds.
        uselib          = ['QT5CORE',
                           'QT5GUI',
                           'QT5WIDGETS'],
        win_features        = ['crcfix'],
        includes           = ['..'], #so that we can specify the module name of TranslationBuilder in the include statements.
        test_all_file_list = ['translationbuilder_tests.waf_files'],
    )


