########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################
def build(bld):
    bld.DefineGem(
        Editor = dict(
            vs_filter       = 'Gems/ScriptCanvas',
            platforms       = ['win', 'darwin'],
            win_features    = ['crcfix'],
            autod_uselib    = ['QT5CORE','QT5GUI','QT5WIDGETS'],
            features        = ['qt5','az_code_gen'],
            configurations  = ['profile', 'debug', 'debug_test', 'profile_test'],
            includes        = [ '.', '..', 'Source'],
            defines         = ['SCRIPTCANVAS_EDITOR', 'SCRIPTCANVAS', 'SCRIPTCANVAS_ERRORS_ENABLED', 'ENABLE_EXTENDED_MATH_SUPPORT=0'],
            use             = ['ScriptCanvas', 'ScriptCanvasEditor', 'AssetBuilderSDK', 'GraphCanvasWidgets', 'AzToolsFramework'],
            file_list       = ['scriptcanvastestingeditor.waf_files'],
            test_all_file_list = ['scriptcanvastestingeditor_tests.waf_files'],
            disable_pch     = True,
        ),
    )