########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):
    # PhysX has global pointers for referencing the PhysX SDK. These pointers need to exist in a single memory
    # space so different Gems can get copies of them. Monolithic builds will use the static version of PhysX SDK libraries,
    # which results in a single memory space. Non-monolithic builds will use the dynamic version of PhysX SDK libraries,
    # which also works because different Gems will be using the shared library's memory space.
    if bld.is_build_monolithic():
        physx_sdk_lib = 'PHYSX_SDK'
    else:
        physx_sdk_lib = 'PHYSX_SDK_SHARED'

    bld.DefineGem(
        file_list         = ['physx.waf_files'],
        disable_tests     = (bld.env['PLATFORM'] != 'project_generator') and ('darwin' in bld.env['PLATFORM']),
        platforms         = ['all'],
        includes          = [bld.Path('Code/CryEngine/CryCommon')],
        test_all_includes = [bld.Path('Code/Framework/Tests')],
        pch               = "Source/PhysX_precompiled.cpp",
        use               = ['AzFramework',
                             'LmbrCentral'],
        uselib            = [physx_sdk_lib],
        test_all_use      = ['AzPhysicsTests'],
        win_features      = ['crcfix'],

        win_x64_clang_cxxflags = ['-Wno-return-type-c-linkage'],
        platform_roots = [bld.PlatformRoot('Source/Platform', export_includes=False)],

        editor = dict(
            file_list         = ['physx.waf_files','physx_editor.waf_files'],
            disable_tests     = (bld.env['PLATFORM'] != 'project_generator') and ('darwin' in bld.env['PLATFORM']),
            defines           = ['PHYSX_EDITOR','ENABLE_NON_COMPILED_CGF'],
            includes          = [bld.Path('Code/Tools'),
                                 bld.Path('Code/Sandbox/Editor'),
                                 bld.Path('Code/Sandbox/Editor/Include'),
                                 bld.Path('Code/Tools/CryCommonTools'),
                                 bld.Path('Code/CryEngine/CryCommon')
                                ],

            test_all_includes = [bld.Path('Code/Framework/Tests')],
            use               = ['AzFramework',
                                 'LmbrCentral',
                                 'EditorCommon',
                                 'SceneCore',
                                 'SceneData',
                                 'AssetBuilderSDK'],
            test_all_use      = ['AzPhysicsTests'],
            uselib            = ['QT5CORE', physx_sdk_lib],

            # Platform specific
            win_lib           = ['Ws2_32', 'Gdi32', 'Shell32', 'Ole32', 'Rpcrt4', 'Winmm'],
            win_features      = ['crcfix'],
            win_x64_clang_cxxflags = ['-Wno-return-type-c-linkage'],
            platform_roots = [bld.PlatformRoot('Source/Platform', export_includes=False)]
        ),
    )
