########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):
    bld.DefineGem(
        file_list         = ['physx.waf_files'],
        win_file_list     = ['physx_win.waf_files'],
        disable_tests     = (bld.env['PLATFORM'] != 'project_generator') and ('darwin' in bld.env['PLATFORM']),
        platforms         = ['all'],
        test_all_includes = [bld.Path('Code/Framework/Tests')],
        pch               = "Source/PhysX_precompiled.cpp",
        use               = ['LmbrCentral',
                             'AzFramework'],
        test_all_use      = ['AzPhysicsTests'],
        win_features      = ['crcfix'],
        win_defines       = ['PHYSX_WIN'],

        win_x64_clang_cxxflags = ['-Wno-return-type-c-linkage'],

        editor = dict(
            file_list         = ['physx.waf_files'],
            win_file_list     = ['physx_editor_win.waf_files', 'physx_win.waf_files'],
            disable_tests     = (bld.env['PLATFORM'] != 'project_generator') and ('darwin' in bld.env['PLATFORM']),
            defines           = ['PHYSX_EDITOR'],
            win_defines       = ['PHYSX_EDITOR_WIN', 'PHYSX_WIN'],
            includes          = [bld.Path('Code/Framework/AzToolsFramework'),
                                 bld.Path('Code/Tools')],
            test_all_includes = [bld.Path('Code/Framework/Tests')],
            use               = ['LmbrCentral',
                                 'AzFramework',
                                 'SceneCore',
                                 'SceneData'],
            test_all_use      = ['AzPhysicsTests'],
            uselib            = ['QT5CORE'],
            win_features      = ['crcfix'],

            win_x64_clang_cxxflags = ['-Wno-return-type-c-linkage'],
        ),
    )
