########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################


def build(bld):
    bld.CryEngineStaticLibrary(
        target                = 'PhysX.NumericalMethods',
        file_list             = ['numericalmethods.waf_files'],
        configurations        = ['all'],
        includes              = ['Include', 'Source'],
        export_includes       = ['Include'],
        use                   = ['AzFramework'],
        vs_filter             = 'Gems',
        pch                   = 'Source/NumericalMethods_precompiled.cpp',

        # Unit Tests
        # The name of the output file name has been changed because the default name PhysX.NumericalMethodsTests.dll
        # is blacklisted by the AzTestRunner by default (the pattern is intended to filter PhysX SDK binaries).
        create_test_driver    = True,
        test_vs_filter        = 'Gems',
        test_file_list        = ['numericalmethods_tests.waf_files'],
        test_includes         = ['Include','Source'],
        test_use              = ['AzTest'],
        test_output_file_name = 'NumericalMethodsTests',
    )
