########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
########################################################################################

def build(bld):

    bld.CryConsoleApplication(

        #==============================
        # Common Settings
        #==============================
        target = 'HLSLcc',
        vs_filter = 'Tools',
        file_list = 'hlslcc.waf_files',
        platforms       = ['win'],
        configurations  = ['debug', 'profile'],
        disable_pch = True,

        includes = [bld.Path('Code/Tools/HLSLCrossCompiler/include'),
                    bld.Path('Code/Tools/HLSLCrossCompiler/src'),
                    bld.Path('Code/Tools/HLSLCrossCompiler/src/cbstring'),
                    bld.Path('Code/Tools/HLSLCrossCompiler/offline/cjson')],

        output_folder = 'Tools/CrySCompileServer/Compiler/PCGL/V006',
        output_file_name = 'HLSLcc',
        win_defines = ['_CRT_SECURE_NO_WARNINGS', '_CONSOLE', 'WIN32'],
        win_lib = ['gdi32'],

        win_x64_clang_cxxflags = ['-Wno-deprecated-register'],
    )

