########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    kw_dict = dict(
        disable_pch             = True,
        file_list               = ['gamestatesamples.waf_files'],
        includes                = [bld.Path('Code/CryEngine/CryCommon')
                                  ],
        test_all_file_list      = ['gamestatesamples_tests.waf_files'],
        platform_roots          = [bld.PlatformRoot('Include/Platform', export_includes=True)]
    )

    bld.DefineGem(
        **kw_dict
    )
