########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):


    bld.CryStandAlonePlugin(

        platforms = ['win'],
        configurations = ['debug', 'debug_test', 'profile', 'profile_test'],

        #==============================
        # Settings
        #==============================
        target          = 'StaticDataMonitorPlugin',
        vs_filter       = 'StaticData/Plugins',
        file_list       = 'staticdatamonitor.waf_files',
        use	            = ['EditorCommon','EditorCore', 'AzToolsFramework'],
        features	    = 'qt5',

        test_all_file_list = ['staticdatamonitor_tests.waf_files'],
        autod_uselib    = [ 'QT5CORE',
                            'QT5GUI',
                            'QT5WIDGETS'],

        #==============================
        # Common
        #==============================
        includes = ['../Include'],


        # Monitor is only supported on windows
        win_defines = ['USE_MONITOR'],

        defines     = ['QT_NO_DEBUG',
                       'QT_LARGEFILE_SUPPORT',
                       'QT_DLL',
                       'QT_NO_EMIT',
                       'EDITOR_COMMON_IMPORTS',
                       'NOMINMAX']

    )


