########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################


def build(bld):

    bld.CryPlugin(

        # Settings
        target                  = 'EditorAnimation',
        vs_filter               = 'Sandbox/Plugins',
        copyright_org           = 'Amazon-CryTek',
        file_list               = 'editoranimation.waf_files',
        platforms               = ['win', 'darwin'],
        configurations          = ['all'],
        exclude_monolithic      = True,
        client_only             = True,
        features                = ['qt5'],
        includes                = [ bld.Path('Code/Tools')],
        use                     = ['EditorCommon',
                                   'SceneCore'],
        uselib                  = ['QT5CORE',
                                   'QT5GUI',
                                   'QT5WIDGETS'],

        win_x64_clang_cxxflags  = ['-Wno-inconsistent-dllimport'],

        # Testing
        test_all_file_list      = ['editoranimation_test.waf_files'],
    )
