########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################


def build(bld):

    bld.CryEngineModule(

        # Settings
        target               = 'CryAudioImplWwise',
        vs_filter            = 'CryEngine/Audio/Implementations',
        copyright_org        = 'Amazon-CryTek',
        file_list            = 'audioimplwwise.waf_files',
        platforms            = ['win', 'android', 'darwin', 'ios', 'appletv'],
        configurations       = ['debug', 'debug_test', 'profile', 'profile_test', 'performance', 'release'],
        pch                  = 'StdAfx.cpp',
        use                  = ['AzCore'],
        uselib               = ['WWISELTX'],
        includes             = ['.',
                                '../../Common'],

        # Complier Specific
        msvc_cxxflags        = ['/wd4819'],

        # Platform Specific
        win_lib              = ['Ole32', 'OleAut32', 'dxguid', 'ws2_32', 'XInput', 'Winmm', 'DInput8', 'DSound'],

       
       

       
       

        ios_lib              = ['AkAACDecoder'],
        ios_framework        = ['AVFoundation', 'AudioToolbox', 'CoreAudio'],

        appletv_lib          = ['AkAACDecoder'],
        appletv_framework    = ['AVFoundation', 'AudioToolbox', 'CoreAudio'],

        darwin_x64_lib       = ['AkAACDecoder'],
        darwin_x64_framework = ['AVFoundation', 'AudioToolbox', 'CoreAudio'],

        android_lib          = ['OpenSLES'],

        win_x64_clang_cxxflags = ['-Wno-deprecated-declarations'], # Wwise calls deprecated Windows functions

        # Testing
        test_all_file_list   = ['audioimplwwise_test.waf_files'],
    )
