
'''
Field keys array is used validate encrypted presigned posts generated by boto3.
'''
ENCRYPTED_FIELD_KEYS = ['x-amz-algorithm', 'x-amz-security-token', 'x-amz-date', 'key', 'x-amz-signature', 'x-amz-security-token', 'policy', 'x-amz-credential']


'''
Field keys array is used validate unencrypted presigned posts generated by boto3.
'''
UNENCRYPTED_FIELD_KEYS = ['x-amz-algorithm', 'x-amz-date', 'key', 'x-amz-signature', 'x-amz-security-token', 'policy', 'x-amz-credential']


'''
 Maximum number of unencrypted pre-signed posts that can be requested per call.
'''
MAXIMUM_NUMBER_OF_UNENCRYPTED_POSTS = 20


'''
 Maximum number of encrypted pre-signed posts that can be requested per call.
'''
MAXIMUM_NUMBER_OF_ENCRYPTED_POSTS = 20


'''
API versions for AWS services used. By default botocore will use the latest API version
when creating a client. This specification will keep code working
until all the code is moved on to a different API version.
'''
S3_API_VERSION = '2006-03-01'
LAMBDA_API_VERSION = '2015-03-31'


'''
Signature version for S3. Default signatures versions vary by region and this
will keep the signature consistent. Note that client must use the same signature
to successfully post.
'''
S3_SIGNATURE_VERSION = 's3v4'


'''
Defines the number of seconds the pre-signed url is valid for.
'''
PRESIGNED_POST_LIFETIME = 300


'''
Mime-type for jpeg images (ex. screenshots).
'''
MIME_TYPE_IMAGE_JPEG = 'image/jpeg'


'''
Mime-type for plain text files (ex. game logs).
'''
MIME_TYPE_TEXT_PLAIN = 'text/plain'


'''
Event version for event published by S3 source.
'''
S3_EVENT_VERSION = '2.0'
