########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):
    bld.DefineGem(
        defines      = ['WATER_GEM'],
        includes     = [bld.Path('Code/CryEngine')],
        win_features = ['crcfix'],
        editor = dict(
            platforms  = ['win', 'darwin'],
            defines    = ['WATER_GEM_EDITOR'],
            uselib     = ['QT5CORE',
                          'QT5GUI',
                          'QT5NETWORK', # this lib depends on EditorLib, which depends on NewsShared, which depends on Qt5Network
                          'QT5WIDGETS'],
            use        = ['AzQtComponents',
                          'EditorUI_QT',
                          'EditorCommon',
                          'EditorCore',
                          'EditorLib'],
            features   = ['qt5'],
            includes   = ['Include',
                          'Source',
                          bld.Path('Code/Sandbox'),
                          bld.Path('Code/Sandbox/Plugins/EditorCommon'),
                          bld.Path('Code/Sandbox/Editor'),
                          bld.Path('Code/Sandbox/Editor/Include'),
                          bld.Path('Code/CryEngine')],

            # For the macOS we require the AWS libs in order to link the editor
            # because there are implicit dependencies on LyMetrics/LyIdentity
            # and those libraries use AWS. Not including them here results in
            # a failure to build the gem due to missing symbols
            darwin_uselib = ['AWS_CPP_SDK_CORE',
                             'AWS_CPP_SDK_COGNITO_IDENTITY',
                             'AWS_CPP_SDK_MOBILEANALYTICS',
                             'AWS_CPP_SDK_IDENTITY_MANAGEMENT']
        ),
    )
