########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################


def build(bld):

    bld.CryEngineModule(

        # Settings
        target             = 'CryScriptSystem',
        vs_filter          = 'CryEngine',
        copyright_org      = 'Amazon-CryTek',
        file_list          = 'cryscriptsystem.waf_files',
        platforms          = ['all'],
        configurations     = ['all'],
        pch                = 'StdAfx.cpp',
        defines            = ['ENGINE_EXPORTS'],
        use                = ['AzFramework'],

        # Platform Specific
        win_lib            = ['Gdi32',
                              'shell32',
                              'wininet',
                              'Ole32' ],

        # Platform Specific
       
       

       

        darwin_cxxflags     = ['-Wno-shadow'],

        ios_cxxflags        = ['-Wno-shadow'],

        appletv_cxxflags    = ['-Wno-shadow'],

        android_armv7_clang_cxxflags  = ['-Wno-shadow'],

        # In order for the extern of lua_getDummyNode to work correctly, lua has to be linked in before AzCore.  Unfortunately,
        # we can't guarantee link order with the use system. However, we can trick the lua library into getting the symbol from AzCore
        # by linking against it a second time at the end of the command line where the 'lib' setting is added.
        android_lib        = ['AzCore'],

        # Testing
        test_all_file_list = ['cryscriptsystem_test.waf_files'],
    )
