########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.DefineGem(
        disable_pch             = True,
        darwin_disable_tests    = True,
        platforms               = ['all'],
        win_features            = ['crcfix'],
        includes                = [ bld.Path('Code/CryEngine'),
                                    bld.Path('Code/CryEngine/CryCommon')],
        win_test_file_list      = ['whitebox_tests_supported.waf_files'],

        platform_roots          = [bld.PlatformRoot('Source/Platform', export_includes=False)],

        Editor = dict(
            win_file_list           = ['whitebox_supported.waf_files', 'whitebox_editor_supported.waf_files'],
            darwin_file_list        = ['whitebox_unsupported.waf_files'],
            linux_file_list         = ['whitebox_unsupported.waf_files'],
            win_test_file_list      = ['whitebox_editor_tests_supported.waf_files'],
            darwin_disable_tests    = True,
            disable_pch             = True,
            use                     = ['EditorCommon'],
            uselib                  = ['OPENMESH'],
            defines                 = ['WHITE_BOX_EDITOR'],
            win_features            = ['crcfix'],
            includes                = [bld.Path('Code/Sandbox/Editor'),
                                       bld.Path('Code/Sandbox/Editor/Include'),
                                       bld.Path('Code/CryEngine'),
                                       bld.Path('Code/CryEngine/CryCommon')]
        )
    )
