########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):

    bld.CryEngineStaticLibrary(
        # Settings
        target              = 'AWSNativeSDKInit',
        vs_filter           = 'Tools/AWSNativeSDKInit',
        file_list           = 'aws_native_sdk_init.waf_files',
        platforms           = ['all'],
        configurations      = ['all'],
        use                 = ['AzCore'],
        uselib              = ['AWS_CPP_SDK_CORE'],
        includes            = ['include' ],
        disable_pch         = True,
        export_includes     = [ bld.Path('Code/Tools/AWSNativeSDKInit/include')],

        win_x64_clang_enable_rtti = True,
    )

    bld.CryEngineStaticLibrary(
        # Settings
        target              = 'AWSNativeSDKInit_Static',
        vs_filter           = 'Tools/AWSNativeSDKInit',
        file_list           = 'aws_native_sdk_init.waf_files',
        platforms           = ['all'],
        configurations      = ['all'],
        use                 = ['AzCore'],
        uselib              = ['AWS_CPP_SDK_CORE_STATIC'],
        includes            = ['include' ],
        disable_pch         = True,
        export_includes     = [ bld.Path('Code/Tools/AWSNativeSDKInit/include')],

        win_x64_clang_enable_rtti = True,
    )
