########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.CryEngineModule(
        #==============================
        # Settings
        #==============================
        target              = 'AzTestIntegBootstrap',
        vs_filter           = 'Tools/AzTestRunner',
        file_list           = 'aztestintegbootstrap.waf_files',
        platforms           = ['win'],
        configurations      = ['test_all'],

        includes            = [bld.Path('Code/CryEngine/CryCommon')],
        uselib              = ['BOOST'],
        use                 = ['AzGameFramework', 'AzTest'],
        
        #==============================
        # Testing
        #==============================
        test_all_file_list = ['aztestintegbootstrap_test.waf_files'],
    )