########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.CryLauncher(
        # Settings
        target           = 'AppleTVLauncher',
        file_list        = 'appletvlauncher.waf_files',
        platforms        = ['appletv'],
        exclude_test     = True,
        client_only      = True,
        use              = ['AzGameFramework',
                            'FREETYPE2',
                            'TOMCRYPT',
                            'TOMMATH'],
        includes         = [bld.Path('Code/CryEngine/CrySystem'),
                            bld.Path('Code/Launcher')],
        cxxflags         = ['-x', 'objective-c++'],
    )


def package(pkg):
    build(pkg) # Need to execute this to generate our task_generator...
    pkg.package_game(
        target          = '{}Launcher'.format(pkg.project),
        task_gen_name   = '{}AppleTVLauncher'.format(pkg.project),
        platforms       = ['appletv'],
        exclude_test    = True,
        client_only     = True,
    )
