########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):

    bld.DefineGem(
        Editor = dict(
            file_list       = ['slicefavorites.waf_files' ],
            test_all_file_list = ['slicefavorites_tests.waf_files'],
            win_features    = ['crcfix'],

            features        = ['qt5'],
            autod_uselib    = ['QT5CORE','QT5GUI','QT5WIDGETS'],
            includes        = [ 'Include' ],
      ),
    )
