########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):
    import lumberyard_sdks

    file_list = []
    if bld.env['PLATFORM'] == 'project_generator':
        file_list.append('cloudgemdefectreporter.waf_files')
        file_list.append('aws_unsupported.waf_files')
    else:
        if lumberyard_sdks.does_platform_support_aws_native_sdk(bld):
            file_list.append('cloudgemdefectreporter.waf_files')
        else:
            file_list.append('aws_unsupported.waf_files')

    if (type(bld.env['PLATFORM']) == str and not bld.env['PLATFORM'].startswith('win')) or (type(bld.env['PLATFORM']) == list and not any(platformname.startswith('win') for platformname in bld.env['PLATFORM'])):
        file_list.append('cloudgemdefectreporter_traceroute_null.waf_files')        
        file_list.append('cloudgemdefectreporter_nslookup_null.waf_files')
        file_list.append('cloudgemdefectreporter_dxdiag_null.waf_files')

    bld.DefineGem(

        file_list = file_list,
        win_file_list = 'cloudgemdefectreporter_windows.waf_files',

        platforms = ['all'],
        uselib = ['AWS_CPP_SDK_CORE'],

        use = ['CloudGemFramework.StaticLibrary'],

        clang_cxxflags = ['-Wno-invalid-noreturn'],
        restricted_script    = 'update_restricted_parameters',
    )
