#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#

def build(bld):
    import lumberyard_sdks

    file_list = []
    if lumberyard_sdks.does_platform_support_aws_native_sdk(bld):
        file_list.append('twitch.waf_files')
    else:
        file_list.append('lmbraws_unsupported.waf_files')


    bld.DefineGem(
        use         =   [   'HttpRequestor',
                            'LmbrAWS'
                        ],
        uselib      =   [   'TWITCHFSDK',
                            'AWS_CPP_SDK_CORE'
                        ],
        includes    =   [],
        
        file_list   = file_list,
        
        # Platform Roots
        platform_roots = [bld.PlatformRoot('Source/Platform', export_includes=False)],

        win_file_list = ['twitch_win.waf_files']
    )

