
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.48.0'
version_full = 'cc7e7c7cfa6389b54d3b5c2c95751c97eb531a96'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

