

def build(bld):

    bld.CryEngineModule(

        #==============================
        # Settings
        #==============================
        target      = 'NetworkFeatureTest',
        vs_filter   = 'Game/NetworkFeatureTest',
        file_list   = 'game.waf_files',
        platforms   = ['all'],
        configurations  = ['all'],
        pch         = 'StdAfx.cpp',
        use         = ['AzGameFramework'],
        use_gems    = True,

        #==============================
        # Common
        #==============================
        includes    = [ '.' ,
                        bld.Path('Code/CryEngine/CryCommon'),
                        bld.Path('Code/CryEngine/CryAction')],
                        
        #==============================
        # Testing
        #==============================
        test_all_file_list = 'game_tests.waf_files',

        #==============================
        # Windows
        #==============================
        win_lib    = ['gdi32'],

        #==============================
        # iOS
        # 'ios_output_file_name' must match both
        # 'executable_name' in 'project.json' and
        # 'Executable file' in '../Resources/IOSLauncher/Info.plist'
        #==============================
        ios_output_file_name = 'NetworkFeatureTestLauncher',
        ios_file_list = ['game_ios.waf_files'],

        #==============================
        # AppleTV
        # 'appletv_output_file_name' must match both
        # 'executable_name' in 'project.json' and
        # 'Executable file' in '../Resources/AppleTVLauncher/Info.plist'
        #==============================
        appletv_output_file_name = 'NetworkFeatureTestLauncher',
        appletv_file_list = ['game_appletv.waf_files'],

        #==============================
        # Darwin
        #==============================
        darwin_file_list = ['game_mac.waf_files'],
        
    )
