########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):

    bld.CryConsoleApplication(
        target         = 'ShaderCacheGen',
        vs_filter      = 'Tools',
        copyright_org  = 'Amazon-CryTek',
        file_list      = 'shader_cache_gen.waf_files',
        platforms      = ['win', 'darwin'],
        client_only         = True,
        exclude_monolithic  = True,
        use            = ['AzGameFramework'],
        defines        = ['_LAUNCHER', 'USE_CRY_NEW_AND_DELETE']
    )
