########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):

    remote_console_core = dict(
        target                  = 'RemoteConsoleCore',
        vs_filter               = 'Tools',
        copyright_org           = 'Amazon-CryTek',
        file_list               = 'Core/remoteconsolecore.waf_files',
        platforms               = ['all'],
        configurations          = ['all'],

        use                     = ['AzFramework'],
        defines                 = ['NOT_USE_CRY_MEMORY_MANAGER'],
        export_includes         = ['Core'],
    )

    for p0, p1, p2, p3 in bld.env['RESTRICTED_PLATFORMS']:
        remote_console_core['{}_file_list'.format(p3)] = 'Core/{0}/remoteconsolecore_{1}.waf_files'.format(p0, p1)

    bld.CryEngineStaticLibrary(**remote_console_core)
