/*
* All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
* its licensors.
*
* For complete copyright and license terms please see the LICENSE at the root of this
* distribution (the "License"). All use of this software is governed by the License,
* or, if provided, by the license below or the license accompanying this file. Do not
* remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*
*/
#pragma once

#if !defined(INCLUDE_WWISE_IMPL_PRODUCTION_CODE)
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_AUDIOSYSTEMIMPL_USE_SUSPEND 1
#else
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_AUDIOSYSTEMIMPL_USE_SUSPEND 0
#endif
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_COMMAND_QUEUE_MEMORY_POOL_SIZE 256 /* 256 KiB */
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_COMMAND_QUEUE_MEMORY_POOL_SIZE_DEFAULT_TEXT "256 (256 KiB)"
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_FILEIO_AKDEVICE_THREAD_AFFINITY_MASK 0
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_LOWER_ENGINE_DEFAULT_POOL_SIZE 16 << 10 /* 16 MiB */
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_LOWER_ENGINE_DEFAULT_POOL_SIZE_DEFAULT_TEXT "16384 (16 MiB)"
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_MONITOR_MEMORY_POOL_SIZE 256 /* 256 KiB */
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_MONITOR_MEMORY_POOL_SIZE_DEFAULT_TEXT "256 (256 KiB)"
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_MONITOR_QUEUE_MEMORY_POOL_SIZE 64 /* 64 KiB */
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_MONITOR_QUEUE_MEMORY_POOL_SIZE_DEFAULT_TEXT "64 (64 KiB)"
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_PREPARE_EVENT_MEMORY_POOL_SIZE 2 << 10 /* 2 MiB */
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_PREPARE_EVENT_MEMORY_POOL_SIZE_DEFAULT_TEXT "2048 (2 MiB)"
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_PRIMARY_POOL_SIZE 128 << 10 /* 128 MiB */
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_PRIMARY_POOL_SIZE_DEFAULT_TEXT "131072 (128 MiB)"
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_PROVIDE_IMPL_SECONDARY_POOL 0
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_SECONDARY_POOL_SIZE 0
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_SECONDARY_POOL_SIZE_DEFAULT_TEXT "0 (0 MiB)"
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_SOUND_ENGINE_DEFAULT_MEMORY_POOL_SIZE 8 << 10 /* 8 MiB */
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_SOUND_ENGINE_DEFAULT_MEMORY_POOL_SIZE_DEFAULT_TEXT "8192 (8 MiB)"
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_STREAMER_DEVICE_MEMORY_POOL_SIZE 2 << 10 /* 2 MiB */
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_STREAMER_DEVICE_MEMORY_POOL_SIZE_DEFAULT_TEXT "2048 (2 MiB)"
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_STREAMER_MANAGER_MEMORY_POOL_SIZE 64 /* 64 KiB */
#define AZ_TRAIT_CRYAUDIOIMPLWWISE_STREAMER_MANAGER_MEMORY_POOL_SIZE_DEFAULT_TEXT "64 (64 KiB)"
