# {BEGIN_LICENSE}
########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################
# {END_LICENSE}

from waf_branch_spec import LUMBERYARD_ENGINE_PATH

def recurse_engine_root(ctx):
    ctx.recurse(dirs=[LUMBERYARD_ENGINE_PATH])

options = recurse_engine_root
configure = recurse_engine_root
build = recurse_engine_root
package = recurse_engine_root
deploy = recurse_engine_root
run_unit_test = recurse_engine_root
