########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

from waflib.Build import BuildContext

SUBFOLDERS = [
    '../GridMate/GridMate'
    ]

def build(bld):

    bld.CryEngineStaticLibrary(
        target          = 'GridMateForTools',
        vs_filter       = 'Network',
        file_list       = ['../GridMate/GridMate/gridmate.waf_files'],
        platforms       = ['all'],
        configurations  = ['all'],
        disable_pch     = True,
        includes        = ['../GridMate'],
        use             = ['AzCore'],
        export_includes = ['../GridMate'],

        defines         = ['GRIDMATE_FOR_TOOLS'],

        msvc_cxxflags   = [
                           '/W4', # warning level
                          ],

        darwin_enable_rtti = True

    )
