########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):
    bld.DefineGem(
        # General
        disable_pch             = True,
        file_list               = ['savedata.waf_files'],
        
        # Testing
        test_all_file_list      = ['savedata_tests.waf_files'],

        # Platform Specific
        win_lib                 = ['Shell32', 'Ole32'],
        win_file_list           = ['savedata_win.waf_files'],
        ios_file_list           = ['savedata_ios.waf_files'],
        linux_file_list         = ['savedata_none.waf_files'],
        darwin_file_list        = ['savedata_darwin.waf_files'],
        appletv_file_list       = ['savedata_none.waf_files'],
        android_file_list       = ['savedata_android.waf_files'],
        restricted_script       = 'update_restricted_parameters',
    )
