def build(bld):

    bld.DefineGem(
        # Add custom build options here
        includes = [
            bld.Path('Code/CryEngine/CryAction'),
            bld.Path('Code/SDKs/civetweb/include'),
        ],
        
        win_file_list = ['metastream_win.waf_files'],
        
        win_defines = ['USE_WEBSOCKET'],

        additional_settings = bld.Settings(files = '../../../Code/SDKs/civetweb/src/CivetServer.cpp', disable_pch = True),
    )
