def build(bld):

    bld.DefineGem(
        # Add custom build options here
        includes = [
            bld.Path('Code/CryEngine/CryAction'),
            bld.ThirdPartyPath('civetweb', 'include'),
        ],
        disable_pch = True,

        win_file_list = ['metastream_win.waf_files'],
        win_defines = ['USE_WEBSOCKET'],

        win_x64_clang_cflags   = ['-Wno-deprecated-declarations'],
        win_x64_clang_cxxflags = ['-fexceptions'],
    )
