########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

import os

def build(bld):

    bld.BuilderPlugin(
        target         = 'LevelBuilder',
        vs_filter      = 'Tools/AssetProcessor/Builders',
        file_list      = ['levelbuilder.waf_files'],
        platforms      = ['win', 'darwin'],
        configurations = ['debug_all', 'profile_all'],
        test_all_use   = ['AzTestShared'],
        disable_pch    = True,
        
        test_all_file_list = ['levelbuilder_tests.waf_files'],
    )


