

def build(bld):
    import lumberyard_sdks

    file_list = []
    if bld.env['PLATFORM'] == 'project_generator':
        file_list.append('cloudgemmessageoftheday.waf_files')
        file_list.append('lmbraws_unsupported.waf_files')
    else:
        if lumberyard_sdks.does_platform_support_aws_native_sdk(bld):
            file_list.append('cloudgemmessageoftheday.waf_files')
        else:
            file_list.append('lmbraws_unsupported.waf_files')

    bld.DefineGem(
        # Add custom build options here
        platforms = ['all'],
        file_list = file_list,

        uselib = ['AWS_CPP_SDK_CORE', 'AWS_CPP_SDK_LAMBDA'],

       
    )
