########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):


    bld.CryStandAlonePlugin(
        #==============================
        # Settings
        #==============================
        target          = 'DynamicContentEditorPlugin',
        vs_filter       = 'CloudGemDynamicContent/Plugins',
        file_list       = 'dynamiccontentplugin.waf_files',
        platforms       = ['win', 'darwin'],
        configurations  = ['all'],
        exclude_monolithic = True,
        client_only     = True,
        defines         = ['DYNAMIC_CONTENT_EDITOR',
                           'EDITOR_COMMON_IMPORTS'],
        uselib          = ['AWS_CPP_SDK_ALL',
                           'BOOSTPYTHON',
                           'QTANGLE',
                           'QT5CORE',
                           'QT5GUI',
                           'QT5WIDGETS'],
        use             = ['AWS',
                           'MaglevControlPanel',
                           'AzQtComponents',
                           'EditorUI_QT',
                           'EditorCommon',
                           'EditorCore'] + bld.make_aws_library_task_list(['LyMetricsProducer']),
        features        = ['qt5',
                           'EmbeddedPython'],
        win_lib         = ['gdi32'],

        darwin_cxxflags = ['-Wno-unused-local-typedef',
                           '-Wno-deprecated-register'],
        darwin_x64_lib  = ['python2.7', 'bsm'],
        darwin_x64_framework = ['Security'],

        test_all_file_list = ['dynamiccontentplugin_test.waf_files'],

        includes        = [ bld.Path('Gems/CloudGemDynamicContent/Code/EditorPlugin'),
                            bld.Path('Code/CryEngine/CryAction'),
                            bld.Path('Code/CryEngine/CrySystem'),
                            bld.Path('Code/Sandbox/Plugins/EditorCommon'),
                            bld.Path('Code/Sandbox/Editor'),
                            bld.Path('Code/Sandbox/Editor/Include'),
                            bld.Path('Code/Sandbox/Plugins/MaglevControlPanel'),
                            bld.Path('Gems/AWS/Code/Include'),
                            bld.Path('Code/Tools')
                        ],
    )


