########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):

    bld.CryStandAlonePlugin(

        # Settings
        target          = 'ComponentEntityEditorPlugin',
        vs_filter       = 'Sandbox/Plugins',
        file_list       = 'componententityeditorplugin.waf_files',
        platforms       = ['win'],
        configurations  = ['debug', 'debug_test', 'profile', 'profile_test'],
        pch             = "stdafx.cpp",
        features        = ['qt5'],
        use             = ['EditorLib', 'AzQtComponents'],
        uselib          = ['QT5CORE',
                           'QT5QUICK',
                           'QT5QML',
                           'QT5GUI',
                           'QT5WIDGETS',
                           'QT5NETWORK', # this lib depends on EditorLib, which depends on NewsShared, which depends on Qt5Network
                           'AWS_CPP_SDK_IDENTITY_METRICS',
                           ],
        includes        = [ bld.Path('Code/Sandbox'),
                            bld.Path('Code/CryEngine') ],
        export_includes = ['.'],
        use_required_gems  = True,
        darwin_enable_rtti = True,

        # Testing
        test_all_file_list = ['componententityeditorplugin_test.waf_files'],
    )
