########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    driver_node = bld.path.find_or_declare('Gems/ScriptCanvas/Code/Include/ScriptCanvas/')
    gem_node = bld.path.find_or_declare('Gems/ScriptCanvasPhysics/Code')
    script_canvas_dir = driver_node.path_from(gem_node)

    bld.DefineGem(
        # Add custom build options here
        includes    = [bld.Path('Code/CryEngine/CryAction'),
                       bld.Path('Code/CryEngine/CryCommon')],  
        pch         = 'Source/ScriptCanvasPhysics_precompiled.cpp', 
        file_list   = ['ScriptCanvasPhysics.waf_files'],
        test_all_file_list = ['scriptcanvasphysics_tests.waf_files'],

        win_features    = ['crcfix'],
    )
