########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################


def build(bld):

    bld.CryEngineModule(
        target                      = 'SDL2Ext',
        vs_filter                   = 'SDL2Ext',
        file_list                   = ['sdlext.waf_files'],
        disable_pch                 = True,
        platforms                   = ['android'],
        configurations              = ['all'],
        export_includes             = [bld.Path('Code/Tools/SDLExtension/src/include')],
        use                         = ['SDL2_Android'],

        android_cflags              = [ '-fvisibility=default',
                                        '-Wno-implicit-function-declaration' ],
    )
