########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################


def build(bld):
    
    bld.recurse('Tests')

    bld.CryEngineStaticLibrary(
        # Settings
        target          = 'GridMate',
        vs_filter       = 'Network',
        file_list       = ['GridMate/gridmate.waf_files', 'GridMate/gridmate_ssl.waf_files'],
        platforms       = ['all'],
        configurations  = ['all'],
        disable_pch     = True,
        includes        = ['.'],
        use             = ['AzCore'],
        uselib          = ['OPENSSL'],
        export_includes = ['.'],
        clang_cxxflags  = ['-Wno-deprecated-declarations'],

        # Platform Roots
        platform_roots  = [bld.PlatformRoot('Platform', export_includes=True)],
    
        # Compiler Specific
        msvc_cxxflags   = [
                           '/W4', # warning level
                          ],

        # Platform Specific
        win_features      = ['crcfix'],

        darwin_enable_rtti = True
    )

    bld.CryEngineStaticLibrary(
        # Settings
        target          = 'GridMateForTools',
        vs_filter       = 'Network',
        file_list       = ['GridMate/gridmate.waf_files'],
        platforms       = ['all'],
        configurations  = ['all'],
        disable_pch     = True,
        includes        = ['.'],
        use             = ['AzCore'],
        export_includes = ['.'],
        
        # Platform Roots
        platform_roots  = [bld.PlatformRoot('Platform', export_includes=True)],
    
        defines         = ['GRIDMATE_FOR_TOOLS'],

        # Platform Specific
        msvc_cxxflags   = [
                           '/W4', # warning level
                          ],

        darwin_enable_rtti = True
    )
