########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):
    bld.DefineGem (
        includes            = [ bld.Path('Code/Tools') ],
        disable_pch         = True,

        editor              = dict(
            includes        = [ bld.Path('Code/Tools') ],
            use             = ['SceneCore',
                               'SceneData',
                               'FbxSceneBuilder',
                               'AssetBuilderSDK'],
            disable_pch     = True,
            features        = ['crcfix', 'qt5'],
            uselib          = ['QT5CORE', 'QT5GUI', 'QT5WIDGETS', 'MIKKT'],
            defines         = ['SCENE_PROCESSING_EDITOR']
            )
    )
