########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.CryStandAlonePlugin(

        # Settings
        target          = 'MaglevControlPanel',
        vs_filter       = 'Sandbox/Plugins',
        file_list       = 'maglevcontrolpanel.waf_files',
        platforms       = ['win'],
        configurations  = ['debug', 'debug_test', 'profile', 'profile_test'],
        use	            = ['AzFramework',
                           'EditorUI_QT',
                           'EditorCommon',
                           'EditorCore'] + 
                           bld.make_aws_library_task_list(['LyMetricsProducer', 'LyIdentity']),

        uselib          = ['QTANGLE',
                           'QT5CORE',
                           'QT5GUI',
                           'QT5WIDGETS',
                           'BOOSTPYTHON',
                           'AWS_CPP_SDK_CORE',
                           'AWS_CPP_SDK_COGNITO_IDENTITY',
                           'AWS_CPP_SDK_IDENTITY_MANAGEMENT',
                           'AWS_CPP_SDK_MOBILEANALYTICS'],
        features	    = ['qt5',
                           'EmbeddedPython'],
        includes        = ['.',
                           bld.Path('Code/Sandbox/Editor'),
                           bld.Path('Code/Sandbox/Editor/Include'),
                           bld.Path('Code/Sandbox/Plugins/EditorCommon'),
                           bld.Path('Code/CryEngine/CryCommon'),
                           bld.Path('Code/Sandbox/Plugins/EditorUI_QT'),
                           bld.Path('Code/CryEngine/CryAction')],

        defines         = ['QT_NO_DEBUG',
                           'QT_NO_EMIT',
                           'EDITOR_COMMON_IMPORTS'],
        darwin_use      = bld.make_aws_library_task_list(['LyMetricsProducer', 'LyMetricsShared', 'LyIdentity']),
        win_use         = bld.make_aws_library_task_list(['LyMetricsProducer', 'LyIdentity']),

        darwin_cxxflags = ['-Wno-unused-local-typedef'], # required for boost python
        darwin_x64_lib  = ['python2.7', 'curl'],

        # Testing
        test_all_file_list = ['maglevcontrolpanel_test.waf_files'],
    )


