########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.CryStandAlonePlugin(

        # Settings
        target          = 'MaglevControlPanel',
        vs_filter       = 'Sandbox/Plugins',
        file_list       = ['maglevcontrolpanel_common.waf_files'],
        platforms       = ['win', 'darwin'],
        configurations  = ['all'],
        exclude_monolithic = True,
        client_only     = True,
        use	            = ['AzFramework',
                           'EditorUI_QT',
                           'EditorCommon',
                           'EditorCore'] +
                           bld.make_aws_library_task_list(['LyMetricsProducer', 'LyIdentity']),

        uselib          = ['QTANGLE',
                           'QT5CORE',
                           'QT5GUI',
                           'QT5WIDGETS',
                           'PYBIND11',
                           'AWS_CPP_SDK_CORE',
                           'AWS_CPP_SDK_COGNITO_IDENTITY',
                           'AWS_CPP_SDK_IDENTITY_MANAGEMENT',
                           'AWS_CPP_SDK_MOBILEANALYTICS'],
        features	    = ['qt5',
                           'EmbeddedPython'],
        includes        = ['.',
                           bld.Path('Code/Sandbox/Editor'),
                           bld.Path('Code/Sandbox/Editor/Include'),
                           bld.Path('Code/Sandbox/Plugins/EditorCommon'),
                           bld.Path('Code/CryEngine/CryCommon'),
                           bld.Path('Code/Sandbox/Plugins/EditorUI_QT')
                           ],
        defines         = ['QT_NO_DEBUG',
                           'QT_NO_EMIT',
                           'EDITOR_COMMON_IMPORTS'],

        win_use         = bld.make_aws_library_task_list(['LyMetricsProducer', 'LyIdentity']),
        win_file_list    = ['maglevcontrolpanel_win.waf_files'],
        win_test_all_file_list = ['maglevcontrolpanel_test.waf_files'],
        win_uselib = ['PYTHON37'],

        darwin_file_list = ['maglevcontrolpanel_darwin.waf_files'],
        darwin_disable_tests = True
    )


