@ECHO OFF 

REM $Revision: #1 $

SETLOCAL
SET CMD_DIR=%~dp0
SET CMD_DIR=%CMD_DIR:~0,-1%

SET ROOT_DIR=%CMD_DIR%\..\..\..

SET PYTHON_DIR=%ROOT_DIR%\Tools\Python
IF EXIST "%PYTHON_DIR%" GOTO PYTHON_READY
ECHO Missing: %PYTHON_DIR%
GOTO :EOF
:PYTHON_READY
SET PYTHON=%PYTHON_DIR%\python.cmd

SET AWS_SDK_DIR=%ROOT_DIR%\Tools\AWSPythonSDK
IF EXIST "%AWS_SDK_DIR%"\append_PYTHONPATH.cmd GOTO AWS_SDK_READY
ECHO Missing: %AWS_SDK_DIR%
GOTO :EOF
:AWS_SDK_READY

SET PYTHONPATH=
CALL "%AWS_SDK_DIR%"\append_PYTHONPATH.cmd

"%PYTHON%" "%CMD_DIR%"\cleanup.py %*

