########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.CryLauncher(
        # Settings
        target           = 'IOSLauncher',
        file_list        = 'ioslauncher.waf_files',
        platforms        = ['ios'],
        configurations   = ['debug', 'profile', 'performance', 'release'],
        ios_launcher     = True,
        use              = ['AzGameFramework'],

        # Common
        includes        = [ bld.Path('Code/CryEngine/CrySystem'),
                            bld.Path('Code/Launcher') ],
        uselib          = [ 'TOMMATH', 'TOMCRYPT', 'FREETYPE2'],

        cxxflags        = [ '-x', 'objective-c++' ],
    )
