########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################
SUBFOLDERS = [
        'EditorPlugin'
    ]

def build(bld):

    import lumberyard_sdks

    aws_files = ['static_data_sdk.waf_files']

    file_list = ['static_data.waf_files']
	
    if lumberyard_sdks.should_project_include_aws_native_sdk(bld):
        file_list += aws_files

    bld.DefineGem(
        uselib          = ['AWS_CPP_SDK_CORE'],
        includes        = [bld.Path('Code/CryEngine/CryAction'),
                           bld.Path('Gems/StaticData/Code/EditorPlugin')],
        file_list       = file_list,
        pch             = '',

        shared_settings = ['awsgem.json']
    )

    bld.recurse(SUBFOLDERS)
