########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################
SUBFOLDERS = [
    ]

def build(bld):

    file_list = ['static_data.waf_files']

    bld.DefineGem(
        includes        = [bld.Path('Code/CryEngine/CryAction'),
                           'Editor',
                           '.'
        ],
        file_list       = file_list + ['staticdata_game.waf_files'],
        disable_pch     = True,

        editor = dict(

            platforms = ['win', 'darwin'],
            configurations = ['debug', 'debug_test', 'profile', 'profile_test'],
            file_list    = file_list + ['staticdata_editor.waf_files'],
            #==============================
            # Settings
            #==============================
            use	            = ['AzToolsFramework', 'AzFramework'],
            disable_pch = True
            )
    )

    bld.recurse(SUBFOLDERS)
