

def build(bld):
    bld.DefineGem(
        # Add custom build options here
        pch         = 'Source/StdAfx.cpp',
        features    = ['vera'],
        includes    = [bld.Path('Code/CryEngine/CryAction')],
        use         = ['Utils']
    )
