########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):

    kw = dict(
        # Settings
        target              = 'CryNetwork',
        vs_filter           = 'CryEngine',
        copyright_org       = 'Amazon-CryTek',
        file_list           = 'crynetwork.waf_files',
        platforms           = ['all'],
        configurations      = ['all'],
        pch                 = 'StdAfx.cpp',
        includes            = [bld.Path('Code/CryEngine/CryAction')],
        use                 = ['GridMate','AzFramework' ],
        defines             = ['ENGINE_EXPORTS', 'USE_CRY_NEW_AND_DELETE'],

        # Platform Specific
        win_defines         = [ '_HAS_EXCEPTIONS=0' ],


        win_x64_lib         = [ 'Ws2_32', 'mswsock', 'gdi32' ],
        win_x64_linkflags   = '/NODEFAULTLIB:libcmt.lib',

        restricted_script   = 'update_restricted_parameters',
        android_defines     = [],

        # Testing
        test_all_file_list  = ['crynetwork_test.waf_files'],
    )
    for p0, p1, p2, p3 in bld.env['RESTRICTED_PLATFORMS']:
        kw['{}_file_list'.format(p3)] = ['GridMate/{0}/crynetwork_{1}.waf_files'.format(p0, p1)]
    bld.CryEngineModule(**kw)
