########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.CryEngineSharedLibrary(
        # Settings
        target                  = 'AzToolsFrameworkTests',
        vs_filter               = 'AZ Framework/TestSuites',
        file_list               = 'aztoolsframeworktests.waf_files',
        platforms               = ['win', 'darwin'],
        configurations          = ['profile_test', 'debug_test'],
        use                     = ['AzTest', 'AzCore', 'AzToolsFramework', 'AzQtComponents'],
        uselib                  = ['QT5CORE',
                                   'QT5GUI',
                                   'QT5NETWORK',
                                   'QT5QML',
                                   'QT5WEBKITWIDGETS',
                                   'QT5WEBKIT',
                                   'QT5WIDGETS',
                                   'QT5WINEXTRAS',
                                   'QT5CONCURRENT',
                                   'QT5XML']
    )