########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):

        
    bld.CryEngineModule(

        # Settings
        target          = 'CryFont',
        vs_filter       = 'CryEngine',
        copyright_org   = 'Amazon-CryTek',
        file_list       = 'cryfont.waf_files',
        platforms       = ['all'],
        configurations  = ['all'],
        pch             = 'StdAfx.cpp',
        use             = ['AzCore'],

        # Platform Specific
        uselib              = ['FREETYPE2'],
        win_lib             = [  'Shell32' ],
        darwin_framework    = [ 'CoreServices', 'Carbon', 'ApplicationServices' ],

        # ==============================
        # Disable deprecated-register warning
        # raised when building with clang
        # ==============================
        darwin_cxxflags             = ['-Wno-deprecated-register'],
        ios_cxxflags                = ['-Wno-deprecated-register'],
        appletv_cxxflags            = ['-Wno-deprecated-register'],
        android_armv7_clang_cxxflags= ['-Wno-deprecated-register'],


        # Testing
        test_all_file_list = ['cryfont_test.waf_files'],

    )
