########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):	

    bld.CryPluginModule(
        # Settings
        target	                = 'PerforcePlugin',
        vs_filter	            = 'Sandbox/Plugins',
        copyright_org           = 'Amazon-CryTek',
        file_list	            = 'perforceplugin.waf_files',
        platforms               = ['win', 'darwin'],
        configurations          = ['all'],
        exclude_monolithic      = True,
        client_only             = True,
        pch                     = 'stdafx.cpp',
        use                     = ['EditorCommon', 'AzToolsFramework'],
        uselib                  = ['QT5CORE',
                                   'QT5WIDGETS',
                                   'QT5GUI',
                                   'QT5QML',
                                   'P4API',
                                   'OPENSSL'],
        features                = ['qt5'],

        # Platform Specific
        win_debug_all_linkflags = ['/NODEFAULTLIB:libcmtd.lib','/NODEFAULTLIB:libcd.lib'],
        win_ndebug_linkflags    = ['/NODEFAULTLIB:libcmt.lib','/NODEFAULTLIB:libc.lib'],
        win_lib                 = ['gdi32', 'Ws2_32'],

        # Testing
        test_all_file_list      = ['perforceplugin_test.waf_files'],
    )
