########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

SUBFOLDERS = [
    'AssetTaggingPlugin',
    'CryDesigner',
    'EditorAnimation',
    'EditorAudioControlsEditor',
    'EditorCommon',
    'EditorAssetImporter',
    'EditorModularBehaviorTree',
    'EditorUI_QT',
    'FBXPlugin',
    'FFMPEGPlugin',
    'GraphCanvasExample',
    'MaglevControlPanel',
    'MetricsPlugin',
    'ParticleEditorPlugin',
    'PerforcePlugin',
    'ComponentEntityEditorPlugin',
    'UiCanvasEditor',
    'DeploymentTool',
    'ProjectSettingsTool',
    'Legacy',
    #'_ExampleQMLViewPane',
    #'_ExampleQtViewPane',
    ]
    
# to compile the examples, uncomment them above and also add them to the all and editor_and_tools spec files
# in the _WAF_/specs folder at the root.  Add them next to the other plugins (so for example in all.json, whereever EditorUI_Qt appears)

def build(bld):
    # Recursive into all sub projects:
    for subfolder in SUBFOLDERS:
        bld.recurse(subfolder,
                mandatory=False)

