/*
* All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
* its licensors.
*
* For complete copyright and license terms please see the LICENSE at the root of this
* distribution (the "License"). All use of this software is governed by the License,
* or, if provided, by the license below or the license accompanying this file. Do not
* remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*
*/

#include "ActorFixture.h"
#include <AzCore/IO/SystemFile.h>
#include <AzFramework/StringFunc/StringFunc.h>
#include <MCore/Source/ReflectionSerializer.h>
#include <EMotionFX/Source/Actor.h>
#include <EMotionFX/Source/ActorInstance.h>
#include <EMotionFX/Source/Importer/Importer.h>
#include <EMotionFX/Source/EMotionFXManager.h>
#include <AzFramework/Physics/Utils.h>


namespace EMotionFX
{
    void ActorFixture::SetUp()
    {
        SystemComponentFixture::SetUp();

        /*const AZStd::string actorFilename = "C:\\absoluteFilename.actor";
        AZ::IO::SystemFile systemFile;
        if (systemFile.Open(actorFilename.c_str(), AZ::IO::SystemFile::SF_OPEN_READ_ONLY))
        {
            const size_t sizeInBytes = systemFile.Length();
            AZStd::vector<AZ::u8> dataToEncode;
            dataToEncode.resize(sizeInBytes);
            systemFile.Read(sizeInBytes, dataToEncode.begin());

            const AZStd::string base64EncodedData = AzFramework::StringFunc::Base64::Encode(dataToEncode.begin(), sizeInBytes);
            OutputDebugString(base64EncodedData.c_str());
        }*/

        // Simple Jack without meshes
        const AZStd::string base64ActorData = "QUNUUgEAAAcAAABEAAAAAgAAAAEAAAD//////////wcEAAAAAAAAAAAAAAAAAAAZAAAASmFja0JpbmRfWlVwX1NrZWxldG9uT25seQsAAACMIAAAAQAAAD8AAAABAAAAYdvVv1/b1b9e29W/X9vVP2Hb1T9h29U/AAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAgD8AAIA/AACAP///////////AQAAAAEAAAAAAIA/AAAAAAAAAAD//3//AAAAAAAAgD8AAAAA//9//wAAAAAAAAAAAACAP///f/8AAAAAAAAAAAAAAAAAAIA/CQAAAGphY2tfcm9vdAAAgIoAAICKAAAAAAAAgD+315Ele4pRJkL2gj8AAIA/AACAPwAAgD//////AAAAAAMAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPw0AAABCaXAwMV9fcGVsdmlzAAAAAAAAAAAAAAAAAACAP2kKzj0Y+Dq8nx8GvQAAgD8AAIA/AACAP/////8BAAAAAgAAAAEAAAAAAIA/AAAAAAAAAAD//3//AAAAAAAAgD8AAAAA//9//wAAAAAAAAAAAACAP///f/8AAAAAAAAAAAAAAAAAAIA/BwAAAGxfdXBMZWcAAAAAAAAAAAAAAAAAAIA/nQzOvRj4OryfHwa9AACAPwAAgD8AAIA//////wEAAAACAAAAAQAAAAAAgD8AAAAAAAAAAP//f/8AAAAAAACAPwAAAAD//3//AAAAAAAAAAAAAIA///9//wAAAAAAAAAAAAAAAAAAgD8HAAAAcl91cExlZ2phQqQBODA/I7I5v5jVTCSf8Q2lvHSTvMLtiD0AAIA/AACAPwAAgD//////AQAAAAEAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwYAAABzcGluZTEAAAAAAAAAAAAAAAAAAIA/zUzFquSFlrQcWmS+AACAPwAAgD8AAIA//////wIAAAAAAAAAAQAAAAAAgD8AAAAAAAAAAP//f/8AAAAAAACAPwAAAAD//3//AAAAAAAAAAAAAIA///9//wAAAAAAAAAAAAAAAAAAgD8LAAAAbF91cExlZ1JvbGwAAAAAAAAAAAAAAAAAAIA/PUpFq+SFFrUcWuS+AACAPwAAgD8AAIA//////wIAAAABAAAAAQAAAAAAgD8AAAAAAAAAAP//f/8AAAAAAACAPwAAAAD//3//AAAAAAAAAAAAAIA///9//wAAAAAAAAAAAAAAAAAAgD8HAAAAbF9sb0xlZwAAAAAAAAAAAAAAAAAAgD89SsWq5IWWtBxaZL4AAIA/AACAPwAAgD//////AwAAAAAAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwsAAAByX3VwTGVnUm9sbAAAAAAAAAAAAAAAAAAAgD/NTEWr5IUWtRxa5L4AAIA/AACAPwAAgD//////AwAAAAEAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwcAAAByX2xvTGVnCXHWPPIZDYqa1DsHi+l/P3sUriSZmRm+UrieJQAAgD8AAIA/AACAP/////8EAAAAAQAAAAEAAAAAAIA/AAAAAAAAAAD//3//AAAAAAAAgD8AAAAA//9//wAAAAAAAAAAAACAP///f/8AAAAAAAAAAAAAAAAAAIA/BgAAAHNwaW5lMgAAAAAAAAAAAAAAAAAAgD8UrkerB1sYtff75r4AAIA/AACAPwAAgD//////BgAAAAEAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwcAAABsX2Fua2xlAAAAAAAAAAAAAAAAAACAP82sR6sHWxi19/vmvgAAgD8AAIA/AACAP/////8IAAAAAQAAAAEAAAAAAIA/AAAAAAAAAAD//3//AAAAAAAAgD8AAAAA//9//wAAAAAAAAAAAACAP///f/8AAAAAAAAAAAAAAAAAAIA/BwAAAHJfYW5rbGUJcdY8YUPiCcCFG4iL6X8/rkdhJJmZGb7NzIymAACAPwAAgD8AAIA//////wkAAAADAAAAAQAAAAAAgD8AAAAAAAAAAP//f/8AAAAAAACAPwAAAAD//3//AAAAAAAAAAAAAIA///9//wAAAAAAAAAAAAAAAAAAgD8GAAAAc3BpbmUzAAAAAAAAAAAAAAAAAACAP7l2iC8Jxxm++pmJvQAAgD8AAIA/AACAP/////8KAAAAAAAAAAEAAAAAAIA/AAAAAAAAAAD//3//AAAAAAAAgD8AAAAA//9//wAAAAAAAAAAAACAP///f/8AAAAAAAAAAAAAAAAAAIA/BgAAAGxfYmFsbAAAAAAAAAAAAAAAAAAAgD+5dogvCccZvvqZib0AAIA/AACAPwAAgD//////CwAAAAAAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwYAAAByX2JhbGwqr6C9plKGCGFJVYj7NX8/zMzMJFyPQr6ZmZmmAACAPwAAgD8AAIA//////wwAAAABAAAAAQAAAAAAgD8AAAAAAAAAAP//f/8AAAAAAACAPwAAAAD//3//AAAAAAAAAAAAAIA///9//wAAAAAAAAAAAAAAAAAAgD8EAAAAbmVjaxUg6z4VIOs+76UJv++lCT+h36e9mP/svU/PK7wAAIA/AACAPwAAgD//////DAAAAAEAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwcAAABsX3NobGRy76UJv++lCb8VIOu+FSDrPqDfpz3j/+y9/c4rvAAAgD8AAIA/AACAP/////8MAAAAAQAAAAEAAAAAAIA/AAAAAAAAAAD//3//AAAAAAAAgD8AAAAA//9//wAAAAAAAAAAAACAP///f/8AAAAAAAAAAAAAAAAAAIA/BwAAAHJfc2hsZHIAAIAMAAAAAAAAAAAAAIA/93WcodnDwL3IdYo8AACAPwAAgD8AAIA//////w8AAAAAAAAAAQAAAAAAgD8AAAAAAAAAAP//f/8AAAAAAACAPwAAAAD//3//AAAAAAAAAAAAAIA///9//wAAAAAAAAAAAAAAAAAAgD8EAAAAaGVhZF+DbD+NO/sL1IsKDBXvwz7lOT88d4LtvYXjLb0AAIA///9/P///fz//////EAAAAAIAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwcAAABsX3VwQXJtFe/Dvl+DbCMV78MiX4NsP9I5P7x3gu09DeAtPQAAgD///38///9/P/////8RAAAAAgAAAAEAAAAAAIA/AAAAAAAAAAD//3//AAAAAAAAgD8AAAAA//9//wAAAAAAAAAAAACAP///f/8AAAAAAAAAAAAAAAAAAIA/BwAAAHJfdXBBcm0AAAAAAACAjAAAAAAAAIA/CtcjowrXI6ZJDAI+AACAPwAAgD8AAIA//////xMAAAAAAAAAAQAAAAAAgD8AAAAAAAAAAP//f/8AAAAAAACAPwAAAAD//3//AAAAAAAAAAAAAIA///9//wAAAAAAAAAAAAAAAAAAgD8LAAAAbF91cEFybVJvbGyB+QGl1tAxvljCZKReHHw/hetRJgAAAABJDII+AACAPwAAgD8AAIA//////xMAAAACAAAAAQAAAAAAgD8AAAAAAAAAAP//f/8AAAAAAACAPwAAAAD//3//AAAAAAAAAAAAAIA///9//wAAAAAAAAAAAAAAAAAAgD8HAAAAbF9sb0FybQAAgCPzBDUj8wQ1IwAAgD+uR+GkARamtr8NAj4AAIA/AACAPwAAgD//////FAAAAAAAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwsAAAByX3VwQXJtUm9sbKJ046TW0DE+TK0tpF4cfD/G4wmyBfeRtXcMgj4AAIA/AACAPwAAgD//////FAAAAAIAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwcAAAByX2xvQXJtAACgJAAAACMAAACjAACAP8zMTKUK1yMmi5INPgAAgD8AAIA/AACAP/////8WAAAAAAAAAAEAAAAAAIA/AAAAAAAAAAD//3//AAAAAAAAgD8AAAAA//9//wAAAAAAAAAAAACAP///f/8AAAAAAAAAAAAAAAAAAIA/CwAAAGxfbG9Bcm1Sb2xsWZepPQAAAADucACj6x5/P8zMTKWPwvWli5KNPgAAgD8AAIA/AACAP/////8WAAAABQAAAAEAAAAAAIA/AAAAAAAAAAD//3//AAAAAAAAgD8AAAAA//9//wAAAAAAAAAAAACAP///f/8AAAAAAAAAAAAAAAAAAIA/BgAAAGxfaGFuZI/DFLMAAAAkAACAIwAAgD+Icpo1i+htNraRDT4AAIA/AACAPwAAgD//////GAAAAAAAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwsAAAByX2xvQXJtUm9sbFWXqT1lqcAj7nAAI+sefz9HOHCzkClftJCSjT4AAIA/AACAPwAAgD//////GAAAAAUAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwYAAAByX2hhbmTj+iq/qU8Cv0jNI7zP+Qo/UNY7vfCk8rlAbhg9//9/PwAAgD///38//////xoAAAABAAAAAQAAAAAAgD8AAAAAAAAAAP//f/8AAAAAAACAPwAAAAD//3//AAAAAAAAAAAAAIA///9//wAAAAAAAAAAAAAAAAAAgD8IAAAAbF90aHVtYjH3lTS/WEkFvPgMor09TjQ/XuTPvPkOTDx7isU9AACAPwAAgD///38//////xoAAAABAAAAAQAAAAAAgD8AAAAAAAAAAP//f/8AAAAAAACAPwAAAAD//3//AAAAAAAAAAAAAIA///9//wAAAAAAAAAAAAAAAAAAgD8IAAAAbF9pbmRleDEdhzS/VcqsPaiN8bzODzQ/XeHHu2BwATyYTMY9AACAPwAAgD8AAIA//////xoAAAABAAAAAQAAAAAAgD8AAAAAAAAAAP//f/8AAAAAAACAPwAAAAD//3//AAAAAAAAAAAAAIA///9//wAAAAAAAAAAAAAAAAAAgD8GAAAAbF9taWQx7A00vzVUlT01VJU97A00P32IgDwpyse6/KwuPQAAgD8AAIA/AACAP/////8aAAAAAgAAAAEAAAAAAIA/AAAAAAAAAAD//3//AAAAAAAAgD8AAAAA//9//wAAAAAAAAAAAACAP///f/8AAAAAAAAAAAAAAAAAAIA/DAAAAGxfbWV0YWNhcnBhbPQENb/0BDWjAAAAAPQENT+84v265g90vDmTdT0AAIA/AACAPwAAgD//////GgAAAAAAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwoAAABsX2hhbmRQcm9w0PkKPzrNIzypTwK/4/oqP4bXOz3FxPG51GsYPf//fz8AAIA///9/P/////8cAAAAAQAAAAEAAAAAAIA/AAAAAAAAAAD//3//AAAAAAAAgD8AAAAA//9//wAAAAAAAAAAAACAP///f/8AAAAAAAAAAAAAAAAAAIA/CAAAAHJfdGh1bWIxPU40P/gMoj1bSQW895U0P33jzzzOCUw8N4vFPQAAgD8AAIA///9/P/////8cAAAAAQAAAAEAAAAAAIA/AAAAAAAAAAD//3//AAAAAAAAgD8AAAAA//9//wAAAAAAAAAAAACAP///f/8AAAAAAAAAAAAAAAAAAIA/CAAAAHJfaW5kZXgxzQ80P6mN8TxVyqw9Hoc0P9zdxzs1awE8VE3GPQAAgD8AAIA/AACAP/////8cAAAAAQAAAAEAAAAAAIA/AAAAAAAAAAD//3//AAAAAAAAgD8AAAAA//9//wAAAAAAAAAAAACAP///f/8AAAAAAAAAAAAAAAAAAIA/BgAAAHJfbWlkMewNND81VJW9NVSVPewNND/IhYC8q2bHus2oLj0AAIA/AACAPwAAgD//////HAAAAAIAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwwAAAByX21ldGFjYXJwYWwAAAAA9AQ1v/QENT+3wwcl2BL+OgIEdLzCjnU9AACAPwAAgD8AAIA//////xwAAAAAAAAAAQAAAAAAgD8AAAAAAAAAAP//f/8AAAAAAACAPwAAAAD//3//AAAAAAAAAAAAAIA///9//wAAAAAAAAAAAAAAAAAAgD8KAAAAcl9oYW5kUHJvcAAAEKUAADilAABsJQAAgD8K1yMlPMUivQrXoyYAAIA/AACAPwAAgD//////HQAAAAEAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwgAAABsX3RodW1iMgAAMKUAAIAkAAAApAAAgD8K1yMl2U5JvY/C9SUAAIA/AACAPwAAgD//////HgAAAAEAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwgAAABsX2luZGV4MgAAAAAAAAAlAABAJAAAgD8K16Okt9M9vbgeBScAAIA/AACAPwAAgD//////HwAAAAEAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwYAAABsX21pZDIwpP08Aze0PZ5Rbz3JcX4/vG09vEDwSL3YG5A7AACAPwAAgD8AAIA//////yAAAAABAAAAAQAAAAAAgD8AAAAAAAAAAP//f/8AAAAAAACAPwAAAAD//3//AAAAAAAAAAAAAIA///9//wAAAAAAAAAAAAAAAAAAgD8HAAAAbF9yaW5nMUq7oz1km/w9QIgHPjnxej+c8Q086eA6vS4ZgLkAAIA///9/P///fz//////IAAAAAEAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwgAAABsX3Bpbmt5MQAAoKQAAISlAAD4JAAAgD+bz9qyecQiPZ4ei7UAAIA/AACAPwAAgD//////IgAAAAEAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwgAAAByX3RodW1iMgAAwCQAALCkAAAgpQAAgD9Cloi1TlFJPSzo7zUAAIA/AACAPwAAgD//////IwAAAAEAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwgAAAByX2luZGV4MgAAAAAAAOCkAADApAAAgD8lmn+1ZtY9Pc6b2zUAAIA/AACAPwAAgD//////JAAAAAEAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwYAAAByX21pZDIwpP08Aze0PZ5Rbz3JcX4/XGs9PCf2SD2j+I+7AACAPwAAgD8AAIA//////yUAAAABAAAAAQAAAAAAgD8AAAAAAAAAAP//f/8AAAAAAACAPwAAAAD//3//AAAAAAAAAAAAAIA///9//wAAAAAAAAAAAAAAAAAAgD8HAAAAcl9yaW5nMUq7oz1km/w9QIgHPjnxej/98w28z+Y6PW9MgjkAAIA///9/P///fz//////JQAAAAEAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwgAAAByX3Bpbmt5MQAAQKUAABilAAA8JQAAgD+ZmRkntRjyvI/C9SYAAIA/AACAPwAAgD//////JwAAAAAAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwgAAABsX3RodW1iMwAA4KQAAIAkAAAApAAAgD+4HoUmYJIFva5H4ScAAIA/AACAPwAAgD//////KAAAAAAAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwgAAABsX2luZGV4MwAAgCMAAAAjAAAApAAAgD+4HhUpsIYFvSlcjycAAIA/AACAPwAAgD//////KQAAAAAAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwYAAABsX21pZDMAAAAAAAAAowAAgKIAAIA/CtejpZTDJL2PwvWlAACAPwAAgD8AAIA//////yoAAAABAAAAAQAAAAAAgD8AAAAAAAAAAP//f/8AAAAAAACAPwAAAAD//3//AAAAAAAAAAAAAIA///9//wAAAAAAAAAAAAAAAAAAgD8HAAAAbF9yaW5nMgAAQKQAAAAhAAAAAAAAgD8K1yOl92cLvY/C9SUAAIA/AACAPwAAgD//////KwAAAAEAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwgAAABsX3Bpbmt5MgAAgKMAAHClAAAkJQAAgD9SzY21ghzyPExkeDYAAIA/AACAPwAAgD//////LAAAAAAAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwgAAAByX3RodW1iMwAAoCQAAGCkAAAQpQAAgD9Go+6095IFPY7tXjMAAIA/AACAPwAAgD//////LQAAAAAAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwgAAAByX2luZGV4MwAAQCQAAICkAAAQpQAAgD8HxOKwEocFPae2dzUAAIA/AACAPwAAgD//////LgAAAAAAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwYAAAByX21pZDMAAIAjAABgowAAwKMAAIA/rtn3s/PEJD11q4o1AACAPwAAgD8AAIA//////y8AAAABAAAAAQAAAAAAgD8AAAAAAAAAAP//f/8AAAAAAACAPwAAAAD//3//AAAAAAAAAAAAAIA///9//wAAAAAAAAAAAAAAAAAAgD8HAAAAcl9yaW5nMgAAgCMAACgjAACQowAAgD856ouyWmoLPVnDrTUAAIA/AACAPwAAgD//////MAAAAAEAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwgAAAByX3Bpbmt5MgAAAAAAAICiAAAAAAAAgD/MzEwlScsHvSlcDycAAIA/AACAPwAAgD//////NAAAAAAAAAABAAAAAACAPwAAAAAAAAAA//9//wAAAAAAAIA/AAAAAP//f/8AAAAAAAAAAAAAgD///3//AAAAAAAAAAAAAAAAAACAPwcAAABsX3JpbmczAABApAAAzKMAAEAjAACAP+tROKYEu8K8j8J1JgAAgD8AAIA/AACAP/////81AAAAAAAAAAEAAAAAAIA/AAAAAAAAAAD//3//AAAAAAAAgD8AAAAA//9//wAAAAAAAAAAAACAP///f/8AAAAAAAAAAAAAAAAAAIA/CAAAAGxfcGlua3kzAACAIwAAAAAAAKCjAACAP7MhUbGdywc9DUu/tAAAgD8AAIA/AACAP/////85AAAAAAAAAAEAAAAAAIA/AAAAAAAAAAD//3//AAAAAAAAgD8AAAAA//9//wAAAAAAAAAAAACAP///f/8AAAAAAAAAAAAAAAAAAIA/BwAAAHJfcmluZzMAAAAkAAAAIgAA4KMAAIA/YPJ3s/S5wjxCqLszAACAPwAAgD8AAIA//////zoAAAAAAAAAAQAAAAAAgD8AAAAAAAAAAP//f/8AAAAAAACAPwAAAAD//3//AAAAAAAAAAAAAIA///9//wAAAAAAAAAAAAAAAAAAgD8IAAAAcl9waW5reTMOAAAABAAAAAEAAAAAAAAADQAAABQAAAABAAAAAAAAAAEAAAABAAAAAAAAAAAAAAADAAAAYwAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAAAAAAAAAAACAPwAAyEIAAIA/AACAPwAAwD8BAEYABwAAAERlZmF1bHQQAAAACAAAAAEAAAAAAAAAAAAAAAEAAAAAEgAAABUBAAABAAAAEQEAAAAAAAADiARHSd/LXL5DTZVRNPTAzKQoyNSKL3wDbVMWj0cOS0GYamElBvCbQMj1W6DGAU3/FDTfW07Vvg/T5m+bMxpIHT0F/HDJ/hllqF+ppEd1YbDJ+poAAMjqCNtUAnyW0zJh2ExYor9wdxbTjRTI1JJXNQFu6zd83GBOEK8SlibAdjstWF4jfgYDqqs/XEdaZp681fpNs1PJAABIHT0F/AIyYP09MlcLp15AmTWb6WAAyANztTkBTf8UNN9bTtW+D9Pmb5szGkgdPQX8cMn+GWWoX6mkR3VhsMn6mgAAAMgfu/hpAU3/FDTfW07Vvg/T5m+bMxpIHT0F/HDJ/hllqF+ppEd1YbDJ+poAAAAAAA==";

        AZStd::vector<AZ::u8> data;
        AzFramework::StringFunc::Base64::Decode(data, base64ActorData.c_str(), base64ActorData.size());

        m_actor = EMotionFX::GetImporter().LoadActor(data.begin(), data.size());
        m_actorInstance = ActorInstance::Create(m_actor);

        AZ::SerializeContext* serializeContext = nullptr;
        AZ::ComponentApplicationBus::BroadcastResult(serializeContext, &AZ::ComponentApplicationBus::Events::GetSerializeContext);
        if (serializeContext)
        {
            Physics::ReflectionUtils::ReflectPhysicsApi(serializeContext);
        }
    }

    void ActorFixture::TearDown()
    {
        if (m_actorInstance)
        {
            m_actorInstance->Destroy();
            m_actorInstance = nullptr;
        }

        if (m_actor)
        {
            m_actor->Destroy();
            m_actor = nullptr;
        }

        SystemComponentFixture::TearDown();
    }

    AZStd::string ActorFixture::SerializePhysicsSetup(const Actor* actor) const
    {
        if (!actor)
        {
            return AZStd::string();
        }

        return MCore::ReflectionSerializer::Serialize(actor->GetPhysicsSetup().get()).GetValue();
    }

    AZStd::vector<AZStd::string> ActorFixture::GetTestJointNames() const
    {
         return { "Bip01__pelvis", "l_upLeg", "l_loLeg", "l_ankle" };
    }
}