########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

from waflib import Logs

def build(bld):
    if not bld.is_option_true('enable_legacy_terrain_editor'):
        Logs.error("The <Legacy Terrain> Gem requires the terrain editor tools to be enabled.")
        raise Exception("The <Legacy Terrain> Gem requires the terrain editor tools to be enabled.")
    bld.DefineGem(
        includes          = ['.',
                             'Include',
                             bld.Path('Code/CryEngine/CryCommon')],
        win_features      = ['crcfix'],    
        use_required_gems = True,

        editor = dict(
            platforms   = ['win', 'darwin'],
            features    = ['qt5', 'crcfix'],
            uselib      = [
                           'QT5CORE',
                           'QT5GUI',
                           'QT5WIDGETS',
                           'QT5NETWORK' # this lib depends on EditorLib, which depends on NewsShared, which depends on Qt5Network
                           ],
            defines     = ['LEGACY_TERRAIN_EDITOR'],
            includes    = ['.', 
                           'Include',
                           bld.Path('Code/CryEngine/CryCommon'),
                           bld.Path('Code/Sandbox/Plugins/EditorCommon'),
                           bld.Path('Code/Sandbox/Editor'),
                           bld.Path('Code/Sandbox/Editor/Include'),
                           ],
            use         = ['EditorCommon',
                           'EditorLib', 
                           'AzToolsFramework'],
            use_required_gems = True,
        ),
    )
