########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.CryLauncher(
        # Settings
        target           = 'MacLauncher',
        file_list        = 'maclauncher.waf_files',
        platforms        = ['darwin'],
        configurations   = ['debug', 'debug_test', 'profile', 'profile_test', 'performance', 'release'],
        mac_launcher     = True,
        includes         = [bld.Path('Code/CryEngine/CrySystem'),
                            bld.Path('Code/Launcher')],
        use              = ['AzGameFramework',
                            'TOMCRYPT',
                            'TOMMATH'],
        rpath            = [ "@executable_path/" ],

        cxxflags = [ '-x', 'objective-c++' ],
    )


def package_darwin_x64(pkg):
    build(pkg) # Need to execute this to generate our task_generator...
    pkg.package_game(
        target           = pkg.project + 'Launcher',
        task_gen_name    = pkg.project + 'MacLauncher',
        platforms        = ['darwin'],
        configurations   = ['debug', 'profile', 'performance', 'release'],
        assets_path      = pkg.Path('Cache/' + pkg.project + '/osx_gl'),
        include_spec_dependencies = True,
    )
