########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    kw = dict(

        #==============================
        # Settings
        #==============================
        target      = 'StarterGame',
        vs_filter   = 'Game/StarterGame',
        file_list   = 'game.waf_files',
        platforms   = ['all'],
        configurations  = ['all'],
        pch         = 'StdAfx.cpp',
        use         = ['AzGameFramework'],
        use_gems    = True,

        #==============================
        # Common
        #==============================
        includes    = [ '.' ,
                        bld.Path('Code/CryEngine/CryCommon'),
                        bld.Path('Code/CryEngine/CryAction')],

        #==============================
        # Windows
        #==============================
        win_lib    = ['gdi32'],

        #==============================
        # iOS
        # 'ios_output_file_name' must match both
        # 'executable_name' in 'project.json' and
        # 'Executable file' in '../Resources/IOSLauncher/Info.plist'
        #==============================
        ios_output_file_name = 'StarterGameLauncher',
        ios_file_list = ['game_ios.waf_files'],

        #==============================
        # AppleTV
        # 'appletv_output_file_name' must match both
        # 'executable_name' in 'project.json' and
        # 'Executable file' in '../Resources/AppleTVLauncher/Info.plist'
        #==============================
        appletv_output_file_name = 'StarterGameLauncher',
        appletv_file_list = ['game_appletv.waf_files'],

        #==============================
        # Darwin
        #==============================
        darwin_file_list = ['game_mac.waf_files'],
		
        #==============================
        # Testing
        #==============================
        test_all_file_list = ['game_tests.waf_files'],
    )

    for p0, p1, p2, p3 in bld.env['RESTRICTED_PLATFORMS']:
        kw['{}_file_list'.format(p3)] = ['Core/{0}/game_{1}.waf_files'.format(p0, p1)]

    bld.CryEngineModule(**kw)
