########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):

    bld.CryPluginModule(

        # Settings
        target              = 'AssetTaggingTools',
        vs_filter           = 'Sandbox/Plugins/Tools',
        copyright_org       = 'Amazon-CryTek',
        file_list           = 'assettagging.waf_files',
        platforms           = ['win', 'darwin'],
        configurations      = ['all'],
        exclude_monolithic  = True,
        client_only         = True,
        pch                 = 'stdafx.cpp',
        use                 = ['DBAPI'],
        uselib              = ['SQLITE'],
        output_sub_folder   = '', # prevent this DLL from ending up in EditorPlugins
        defines	            = ['ASSETTAGGING_EXPORTS', '_WINDOWS', '_WINDLL'],

        # Testing
        test_all_file_list = ['assettagging_test.waf_files'],
    )
