########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):
    bld.DefineGem(
        includes = ['Include', 'Source'],
        editor = dict(
            defines = ['ROADS_RIVERS_EDITOR'],
            features = ['qt5', 'ExternalLyIdentity', 'ExternalLyMetrics'],
            use = ['AzToolsFramework', 'AzQtComponents'],
            includes = [
                        bld.Path('Code/CryEngine/CryCommon'),
                        bld.Path('Code/Sandbox/Plugins/EditorCommon'),
                        bld.Path('Code/Sandbox'),
                        bld.Path('Code/Sandbox/Editor'),
                        bld.Path('Code/Sandbox/Editor/Include'),
                        ],

            uselib = ['QT5CORE', 'QT5QUICK', 'QT5QML','QT5GUI', 'QT5WIDGETS'],
        ),
    )
