########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.DefineGem(
        includes    = [ bld.Path('Code/CryEngine/CryAction')],
        disable_tests = (not 'win' in bld.env['PLATFORM']) or ('darwin' in bld.env['PLATFORM']),

        # To enable multi-touch simulation, uncomment this line.
        # defines = [ 'SIMULATE_MULTI_TOUCH' ],

        #==============================
        # Testing
        #==============================
        test_all_file_list = ['gestures_test.waf_files'],
    )