########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################


def build(bld):
    
    from waflib import Utils
    host_platform = Utils.unversioned_sys_platform()
    
    if host_platform == 'linux':
        # For linux platforms, build this module as a static library
        build_func           = 'CryEngineStaticLibrary'
        build_defines        = ['SCENE_DATA_STATIC']
        build_export_defines = ['SCENE_CORE_STATIC']
        build_features       = ['qt5', 'crcfix']
    else:
        # For all other platforms, build this module as a shared library
        build_func           = 'CryEngineModule'
        build_defines        = ['SCENE_DATA_EXPORTS']
        build_export_defines = []
        build_features       = ['qt5','crcfix', 'link_running_program']

    # Create a file list that is needed for the exported symbols in the dylib in a non-monolithic build
    darwinExportedSymbolFileList=[]
    if not bld.is_build_monolithic():
        darwinExportedSymbolFileList.append('SceneData_darwin.waf_files');

    kw = dict(

        # Settings
        target                      = 'SceneData',
        vs_filter                   = 'Tools/SceneAPI',
        disable_pch                 = True,
        file_list                   = ['SceneData.waf_files'],
        platforms                   = ['win', 'darwin', 'linux'],
        client_only                 = True,
        exclude_monolithic          = True,
        includes                    = [ bld.Path('Code/Tools') ],
        use                         = ['SceneCore',
                                       'AzCore',
                                       'AzFramework',
                                       'AzToolsFramework',
                                       'GFxFramework'],
        uselib                      = ['QT5CORE',
                                       'QT5WIDGETS',
                                       'QT5GUI'],
        defines                     = build_defines,
        export_defines              = build_export_defines,
        features                    = build_features,
        output_sub_folder_copy      = 'rc',

        # platform specific
        darwin_file_list            = darwinExportedSymbolFileList,

        # Testing
        test_all_file_list          = 'SceneData_testing.waf_files',
    )

    getattr(bld, build_func)(**kw)


