########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

SUBFOLDERS = [
        'EditorPlugin'
    ]

def build(bld):

    import lumberyard_sdks

    file_list = []
    if bld.env['PLATFORM'] == 'project_generator':
        file_list.append('cloudgemdynamiccontent.waf_files')
        file_list.append('lmbraws_unsupported.waf_files')
        file_list.append('cloudgemdynamiccontent_sdk.waf_files')
    else:
        if lumberyard_sdks.does_platform_support_aws_native_sdk(bld):
            file_list.append('cloudgemdynamiccontent.waf_files')
        else:
            file_list.append('lmbraws_unsupported.waf_files')

        aws_files = ['cloudgemdynamiccontent_sdk.waf_files']
        aws_use = []

        if lumberyard_sdks.should_project_include_aws_native_sdk(bld):
            file_list += aws_files

    bld.DefineGem(
        uselib          = ['AWS_CPP_SDK_CORE'],
        includes        = [bld.Path('Code/CryEngine/CryAction'),
                           bld.Path('Code/CryEngine/CrySystem')
        ],
        file_list   = file_list,
        pch     = '',
        platforms = ['all'],
        disable_pch = True,
        win_lib    = ['gdi32'],

        use = ['CloudCanvasCommon.StaticLibrary'],

        restricted_script = 'update_restricted_parameters',
    )

    bld.recurse(SUBFOLDERS)