########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):
    bld.DefineGem(
        file_list         = ['physxcharacters.waf_files'],
        disable_tests     = (bld.env['PLATFORM'] != 'project_generator') and ('darwin' in bld.env['PLATFORM']),
        platforms         = ['all'],
        includes          = [bld.Path('Gems/PhysX/Code/Include')],
        test_all_includes = [bld.Path('Code/Framework/Tests')],
        pch               = "Source/PhysXCharacters_precompiled.cpp",
        use               = ['LmbrCentral',
                             'AzFramework'],
        uselib            = ['PHYSX_SDK'],
        test_all_use      = ['AzPhysicsTests'],
        win_features      = ['crcfix'],
        
        editor            = dict(
            file_list         = ['physxcharacters.waf_files','physxcharacters_editor.waf_files'],
            disable_tests     = (bld.env['PLATFORM'] != 'project_generator') and ('darwin' in bld.env['PLATFORM']),
            defines           = ['PHYSX_CHARACTERS_EDITOR'],
            includes          = [bld.Path('Code/Framework/AzToolsFramework'),
                                 bld.Path('Code/Tools'),
                                 bld.Path('Code/Sandbox/Editor')],
            test_all_includes = [bld.Path('Code/Framework/Tests')],
            use               = ['LmbrCentral',
                                 'AzFramework',
                                 'SceneCore', 
                                 'SceneData'],
            test_all_use      = ['AzPhysicsTests'],
            uselib            = ['QT5CORE','PHYSX_SDK'],
            win_features      = ['crcfix']
        )
    )
