########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.DefineGem(
        includes     = [bld.Path('Code/CryEngine/CryAction')],
        win_features = ['crcfix'],

        editor       = dict(


            platforms   = ['win', 'darwin'],
            features    = ['qt5', 'ExternalLyIdentity', 'ExternalLyMetrics'],

            use         = ['AzToolsFramework', 'AzQtComponents'] + bld.make_aws_library_task_list(['LyMetricsProducer', 'LyIdentity']),
            includes    = ['include',
                           'Source',
                           bld.Path('Code/Sandbox'),
                           bld.Path('Code/Sandbox/Editor'),
                           bld.Path('Code/Sandbox/Editor/Include'),
                           bld.Path('Code/Sandbox/Plugins/EditorCommon'),
                           bld.Path('Code/CryEngine/CryAction'),
                           bld.Path('Code/CryEngine'),
                           ],
            uselib      =['QT5CORE',
                          'QT5QUICK',
                          'QT5QML',
                          'QT5GUI',
                          'QT5WIDGETS'],
            defines     =['LMBR_CENTRAL_EDITOR'],

            darwin_uselib   =['AWS_CPP_SDK_CORE'],

            shared_settings = ['awsgem.json'],
            win_uselib      =['XTP'],
            win_features    =['crcfix'],
            win_defines     = ['METRICS_SYSTEM_COMPONENT_ENABLED']
        ),
    )
		