########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################


def build(bld):
    define_enable_cry_physics = ''
    if hasattr(bld, 'enable_cry_physics'):
        define_enable_cry_physics = 'ENABLE_CRY_PHYSICS=%i' % bld.enable_cry_physics
    
    bld.DefineGem(
        includes        = [bld.Path('Code/CryEngine/CryCommon')],
        export_includes = ['include'],
        win_features    = ['crcfix'],
        defines         = [define_enable_cry_physics],
        export_defines  = [define_enable_cry_physics],
        platform_roots = [bld.PlatformRoot('Platform', export_includes=False)],

        editor       = dict(

            
            platforms   = ['win', 'darwin', 'linux'],
            features    = ['qt5', 'ExternalLyIdentity', 'ExternalLyMetrics'],
            platform_roots = [bld.PlatformRoot('Platform', export_includes=False)],
            use         = ['AzToolsFramework', 'AzQtComponents', 'AssetBuilderSDK'] + bld.make_aws_library_task_list(['LyMetricsProducer', 'LyMetricsShared', 'LyIdentity']),
            includes    = ['include',
                           'Source',
                           bld.Path('Code/Sandbox'),
                           bld.Path('Code/Sandbox/Editor'),
                           bld.Path('Code/Sandbox/Editor/Include'),
                           bld.Path('Code/Sandbox/Plugins/EditorCommon'),
                           bld.Path('Code/CryEngine/CryCommon'),
                           bld.Path('Code/CryEngine')
                           ],
            uselib      = ['QT5CORE',
                           'QT5QUICK',
                           'QT5QML',
                           'QT5GUI',
                           'QT5WIDGETS'],

            defines        = ['LMBR_CENTRAL_EDITOR', 'METRICS_SYSTEM_COMPONENT_ENABLED', define_enable_cry_physics, 'LMBR_CENTRAL_EDITOR_EXPORTS'],
            export_defines = [define_enable_cry_physics],

            darwin_uselib = ['AWS_CPP_SDK_CORE',
                             'AWS_CPP_SDK_COGNITO_IDENTITY',
                             'AWS_CPP_SDK_STS',
                             'AWS_CPP_SDK_IDENTITY_MANAGEMENT',
                             'AWS_CPP_SDK_MOBILEANALYTICS'],

            linux_uselib  = ['AWS_CPP_SDK_CORE',
                             'AWS_CPP_SDK_COGNITO_IDENTITY',
                             'AWS_CPP_SDK_STS',
                             'AWS_CPP_SDK_IDENTITY_MANAGEMENT',
                             'AWS_CPP_SDK_MOBILEANALYTICS'],

            win_features  = ['crcfix']
        )
    )
