########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.CryStandAlonePlugin(
        #==============================
        # Settings
        #==============================
        target                      = 'MetricsPlugin',
        vs_filter                   = 'Sandbox/Plugins',
        file_list                   = 'metricsplugin.waf_files',
        platforms                   = ['win', 'darwin'],
        configurations              = ['debug', 'debug_test', 'profile', 'profile_test'],
        use                         = 'EditorCommon',

        #==============================
        # Common
        #==============================
        includes                    = [ '.',
                                        bld.Path('Code/Sandbox/Editor'),
                                        bld.Path('Code/CryEngine'),
                                        bld.Path('Code/Sandbox/Editor/Include'),
                                        bld.Path('Code/Sandbox/Plugins/EditorCommon')],

        #==============================
        # Testing
        #==============================
        test_all_file_list = ['metricsplugin_test.waf_files'],
    )
