########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################


def build(bld):
    
    platform_filter = ['win', 'darwin']
    if bld.should_build_experimental_targets():
        platform_filter.append('linux')
    
    bld.CryConsoleApplication(
        target          = 'AssetBuilder',
        vs_filter       = 'Tools/AssetProcessor',
        file_list       = 'asset_builder.waf_files',
        platforms       = ['win', 'darwin', 'linux'],
        exclude_monolithic = True,
        client_only     = True,
        use             = ['AssetBuilderSDK'],
        uselib          = ['QT5CORE',
                           'QT5GUI',
                           'QT5WIDGETS',
                           'QT5XML'],
        disable_pch     = True,
        darwin_rpath    = ['@executable_path/qtlibs/lib',
                           '@executable_path/../Frameworks',
                           '@executable_path'],
        linux_rpath     = ['@executable_path/qtlibs/lib', '@executable_path'],
        win_features    = ['crcfix'],
        features        = ['link_running_program'],

        # Compiler Specific
        msvc_cxxflags       = ['/W4'],

        win_file_list   = ['asset_builder_win.waf_files'],
        darwin_file_list = ['asset_builder_darwin.waf_files'],
        linux_file_list  = ['asset_builder_linux.waf_files']
    )


