########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):
    bld.DefineGem(
        # Add custom build options here
		use	        	= [ 'AzGameFramework', 'EMotionFXStaticLib'],
		
        includes    	= [ bld.Path('Code/CryEngine/CryAction'),
							bld.Path('Gems/LmbrCentral/Code/Source'),
							bld.Path('Gems/LyShine/Code/Source'),
							bld.Path('Gems/TextureAtlas/Code/Include'),
							bld.Path('Gems/Camera/Code/Source'),
							bld.Path('Gems/EMotionFX/Code'),
							bld.Path('Gems/EMotionFX/Code/Source'),
							],
		
		editor = dict(
			defines		= [ 'STARTER_GAME_EDITOR' ],
			use	        = [ 'AzToolsFramework', 'EMotionFXStaticLib', 'SceneCore', 'SceneData' ],
			uselib		= [ 'QT5CORE',
							'QT5GUI',
							'QT5WIDGETS',
							],
			includes	= [ './Include',
							bld.Path('Code/CryEngine/CryAction'),
							bld.Path('Gems/LmbrCentral/Code/Source'),
							bld.Path('Gems/LyShine/Code/Source'),
							bld.Path('Gems/TextureAtlas/Code/Include'),
							bld.Path('Gems/Camera/Code/Source'),
							bld.Path('Gems/EMotionFX/Code'),
							bld.Path('Gems/EMotionFX/Code/Source'),
							bld.Path('Code/Sandbox/Plugins/EditorCommon'),
							bld.Path('Code/Sandbox/Editor'),
							bld.Path('Code/Sandbox/Editor/Include'),
							],
		)
    )
