#############################################################################
## Crytek Source File
## Copyright (C) 2013, Crytek Studios
##
## Creator: Christopher Bolte
## Date: Oct 31, 2013
## Description: WAF  based build system
#############################################################################

def build(bld):

    bld.CryFileContainer(
        target      = 'HWScripts',
        vs_filter   = 'CryEngine/Shaders',
        file_list   = 'hwscripts.waf_files',
        platforms   = ['all'],
        configurations  = ['all'],
    )