/*
* All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
* its licensors.
*
* For complete copyright and license terms please see the LICENSE at the root of this
* distribution (the "License"). All use of this software is governed by the License,
* or, if provided, by the license below or the license accompanying this file. Do not
* remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*
*/
#ifndef CRYINCLUDE_EDITOR_HYPERGRAPH_HYPERGRAPHCONSTANTS_H
#define CRYINCLUDE_EDITOR_HYPERGRAPH_HYPERGRAPHCONSTANTS_H


enum
{
    ID_GRAPHVIEW_RENAME = 1,
    ID_GRAPHVIEW_ADD_SELECTED_ENTITY,
    ID_GRAPHVIEW_ADD_DEFAULT_ENTITY,
    ID_GRAPHVIEW_TARGET_SELECTED_ENTITY,
    ID_GRAPHVIEW_TARGET_GRAPH_ENTITY,
    ID_GRAPHVIEW_TARGET_GRAPH_ENTITY2,
    ID_GRAPHVIEW_TARGET_UNSELECT_ENTITY,
    //ID_GRAPHVIEW_BLACKBOX_SELECTED_ENTITY,
    ID_GRAPHVIEW_ADD_COMMENT,
    ID_GRAPHVIEW_ADD_COMMENTBOX,
    ID_GRAPHVIEW_FIT_TOVIEW,
    ID_GRAPHVIEW_SELECT_ENTITY,
    ID_GRAPHVIEW_SELECT_AND_GOTO_ENTITY,
    ID_GRAPHVIEW_SPLINES,
    ID_GRAPHVIEW_EDGES_ON_TOP_OF_NODES,
    ID_GRAPHVIEW_ADD_TRACKEVENT,
    ID_GRAPHVIEW_ADD_STARTNODE,
    ID_GRAPHVIEW_ADD_BREAKPOINT,
    ID_GRAPHVIEW_REMOVE_BREAKPOINT,
    ID_GRAPHVIEW_REMOVE_BREAKPOINTS_FOR_NODE,
    ID_GRAPHVIEW_REMOVE_ALL_BREAKPOINTS,
    ID_BREAKPOINT_ENABLE,
    ID_TRACEPOINT_ENABLE,
    ID_INPUTS_SHOW_ALL,
    ID_INPUTS_HIDE_ALL,
    ID_OUTPUTS_SHOW_ALL,
    ID_OUTPUTS_HIDE_ALL,
    ID_INPUTS_DISABLE_LINKS,
    ID_INPUTS_ENABLE_LINKS,
    ID_OUTPUTS_DISABLE_LINKS,
    ID_OUTPUTS_ENABLE_LINKS,
    ID_INPUTS_DELETE_LINKS,
    ID_OUTPUTS_DELETE_LINKS,
    ID_INPUTS_CUT_LINKS,
    ID_INPUTS_COPY_LINKS,
    ID_INPUTS_PASTE_LINKS,
    ID_OUTPUTS_CUT_LINKS,
    ID_OUTPUTS_COPY_LINKS,
    ID_OUTPUTS_PASTE_LINKS,
};

#define BASE_NEW_NODE_CMD 10000
#define BASE_INPUTS_CMD 20000
#define BASE_OUTPUTS_CMD 21000

#endif