########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):
    bld.DefineGem(
        # General
        target      = "PythonAssetBuilder",
        includes    = ['Include'],
        disable_pch = True,

        # builder module
        Editor = dict(
            disable_pch    = True,
            features       = ['crcfix'],
            file_list      = ['pythonassetbuilder_editor.waf_files'],
            test_file_list = ['pythonassetbuilder_editor_tests.waf_files'],
            use            = ['AssetBuilderSDK', 'EditorPythonBindings.Editor'],
            msvc_cxxflags  = ['/EHsc'],
            clang_cxxflags = ['-fexceptions'],
            enable_rtti    = True
        )
    )
