########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

import os
def build(bld):

    defines = ['UNICODE']

    parameters = dict(
        target          = 'AssetBuilderSDK',
        vs_filter       = 'Tools/AssetProcessor',
        file_list       = ['assetbuilder.waf_files'],
        platforms       = ['win', 'darwin'],
        configurations  = ['all'],
        exclude_monolithic = True,
        disable_pch     = True,
        use             = ['AzToolsFramework'],
        export_includes = ['.'],
        defines         = defines,

        # Compiler Specific
        msvc_cxxflags       = ['/W4'],
    )
    for p0, p1, p2, p3 in bld.env['RESTRICTED_PLATFORMS']:
        parameters['{}_file_list'.format(p1)] = ['AssetBuilderSDK/{0}/assetbuildersdk_{1}.waf_files'.format(p0, p1)]

    bld.CryEngineStaticLibrary(**parameters)

