########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

import os

def build(bld):

    bld.CryQtApplication(
        # Settings
        target                      = 'GridHub',
        vs_filter                   = 'Tools',
        file_list                   = ['gridhub.waf_files'],
        platforms                   = ['win','darwin'],
        client_only                 = True,
        exclude_monolithic          = True,
        disable_pch                 = True,
        features                    = ['qt5'],
        use                         = ['AzCore',
                                       'GridMateForTools'],
        uselib                      = ['QTANGLE',
                                       'QTMAIN',
                                       'QT5CORE',
                                       'QT5GUI',
                                       'QT5OPENGL',
                                       'QT5NETWORK',
                                       'QT5SVG',
                                       'QT5WIDGETS',
                                       'D3D_COMPILER_47'],
        defines                     = ['GRIDMATE_FOR_TOOLS'],

        # Platform Specific
        darwin_rpath        = ["@executable_path", "@executable_path/../../..", "@executable_path/qtlibs/lib", "@executable_path/../../../qtlibs/lib"],
        darwin_file_list    = ['gridhub_darwin.waf_files'],
        darwin_xcassets     = 'Code/Tools/GridHub/GridHub/Images.xcassets',
        win_lib             = [ 'shell32','ole32','uuid','shlwapi' ]
    )


def package_darwin_x64(pkg):
    build(pkg) # Need to call this to generate our task_generator
    pkg.package_tool(
        target           = 'GridHub',
        platforms        = ['darwin'],
        configurations   = ['debug', 'profile'],
        include_all_libs = True,
        dir_resources    = ['qtlibs'],
    )
