########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################


def build(bld):

    bld.CryEngineStaticLibrary(
        # Settings
        target           = 'AzTest',
        vs_filter        = 'AZ Framework',
        file_list        = ['aztest.waf_files'],
        platforms        = ['win', 'darwin_x64', 'android_armv7_gcc', 'android_armv7_clang',
	],
        configurations   = ['test_all'],
        disable_pch      = True,
        use              = ['AzCore',
                            'GMOCK'],
        includes         = ['..'],
        export_includes  = ['..'],
        
        uselib           = ['GMOCK'],
        win_file_list               = ['aztest_win.waf_files'],
        darwin_file_list            = ['aztest_osx.waf_files'],
        android_armv7_gcc_file_list = ['aztest_android.waf_files'],
    )
