########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################


def build(bld):

    tsk = bld.CryDedicatedServer(
        target                = 'LinuxLauncher',
        platforms             = ['linux_x64'],
        exclude_test          = True,
        server_only           = True,
        file_list             = 'linuxlauncher.waf_files',
        includes              = [bld.Path('Code/CryEngine/CrySystem'),
                                 bld.Path('Code/Launcher')],
        lib                   = ['uuid'],
        create_linux_launcher = True,
        use                   = ['AzGameFramework'],
    )
