# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

import os, shutil

from waflib.Build import BuildContext

def build(bld):

    if isinstance(bld, BuildContext) and hasattr(bld, 'read_aar'):
        bld.read_aar(
            name = 'billing',
            group = 'com.android.billingclient',
            version = '1.0'
        )

    bld.DefineGem(
        # Add custom build options here
        includes        = [bld.Path('Code/CryEngine/CryCommon'),
                           bld.Path('Code/CryEngine/CryAction')
                          ],
        file_list       = ['inapppurchases.waf_files'],
        use             = ['AzCore'],

        # Platform Specific
        platform_roots  = [{'root': 'Source/Platform', 'export_includes': False}]
    )