########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):
    bld.DefineGem(
        includes            = [],
        platforms           = ['win', 'darwin'],
        configurations      = ['debug', 'debug_test', 'profile', 'profile_test'],
        disable_pch         = True,
        file_list           = ['customassetexample.waf_files'],
        test_all_file_list  = ['customassetexample_tests.waf_files'],

        editor = dict(
            includes           = [],
            use                = ['AssetBuilderSDK', 'AzCore'],
            disable_pch        = True,
            features           = ['crcfix'],
            defines            = ['CUSTOM_ASSET_EXAMPLE_EDITOR'],
            file_list          = ['customassetexample_editor.waf_files'],
            test_all_file_list = ['customassetexample_tests_editor.waf_files']
        )
    )
