########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################
import waflib.Tools.compiler_cxx

import sys, os

SUBFOLDERS = [
    'AZCodeGenerator',
    'AzCodeGeneratorUnitTests'
]


def options(opt):
    opt.load('compiler_cxx')


def configure(cfg):
    cfg.recurse(SUBFOLDERS)


def build(bld):
    # If Clang doesn't exist, skip building AzCodeGenerator
    try:
        tp_content = bld.tp.content
        tp_root = tp_content.get('3rdPartyRoot')
        clang_base_source = tp_content.get('SDKs').get('Clang').get('base_source')
        clang_path = os.path.join(tp_root, clang_base_source)
        if not os.path.exists(clang_path):
            return
    except:
        pass
    # Recursive into all sub projects
    bld.recurse(SUBFOLDERS)
