########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################


def build(bld):

    bld.CryPlugin(

        # Settings
        target                      = 'EditorAssetImporter',
        vs_filter                   = 'Sandbox/Plugins',
        file_list                   = 'editorassetimporter.waf_files',
        platforms                   = ['win', 'darwin'],
        configurations              = ['debug', 'debug_test', 'profile', 'profile_test'],
        includes                    = [bld.Path('Code/Tools'),
                                       bld.Path('Code/Framework/AzToolsFramework')],
        pch                         = 'StdAfx.cpp',
        use                         = ['EditorCommon',
                                       'EditorLib',
                                       'AzToolsFramework',
                                       'AzQtComponents',
                                       'SceneCore',
                                       'SceneData',
                                       'SceneUI',
                                       'FbxSceneBuilder',
                                       'GFxFramework'],
        uselib                      = ['QT5CORE',
                                       'QT5GUI',
                                       'QT5WIDGETS',
                                       'QT5NETWORK', # this lib depends on EditorLib, which depends on NewsShared, which depends on Qt5Network
                                       'AWS_CPP_SDK_IDENTITY_METRICS'],
        features                    = ['qt5'],


        # Testing
        test_all_file_list          = 'editorassetimporter_testing.waf_files',

    )
