########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################


def build(bld): 

    bld.CryEngineModule(
        target                      = 'SceneUI',
        vs_filter                   = 'Tools/SceneAPI',
        disable_pch                 = True,
        file_list                   = 'SceneUI.waf_files',
        platforms                   = ['win', 'darwin'],
        client_only                 = True,
        exclude_monolithic          = True,
        test_all_file_list          = 'SceneUI_testing.waf_files',
        includes                    = [ bld.Path('Code/Tools') ],
        use                         = ['SceneCore', 'SceneData', 'AzCore', 'AzFramework', 'AzToolsFramework', 'AzQtComponents'],
        defines                     = [ 'SCENE_UI_EXPORTS' ],
        features                    = ['qt5', 'crcfix'],
        uselib                      = ['QT5CORE', 'QT5GUI', 'QT5WIDGETS']
    )
