########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

SUBFOLDERS =    [
    'DedicatedLauncher',
    'LinuxLauncher',
    'MacLauncher',
    'WindowsLauncher',
    
    
    'AndroidLauncher',
    'IOSLauncher',
    'AppleTVLauncher'
    ]

def build(bld):
    # Recursive into all sub projects - its okay if no wscript exists for them at the moment.
    for subfolder in SUBFOLDERS:
        bld.recurse(subfolder, mandatory = False)

