/*
* All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
* its licensors.
*
* For complete copyright and license terms please see the LICENSE at the root of this
* distribution (the "License"). All use of this software is governed by the License,
* or, if provided, by the license below or the license accompanying this file. Do not
* remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*
*/
/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////
// THIS CODE IS AUTOGENERATED, DO NOT MODIFY
/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////
#pragma once
#include <AzCore/Component/Component.h>
#include <AzCore/Component/Entity.h>
#include <AzCore/Component/ComponentBus.h>
#include <AzCore/EBus/EBus.h>
#include <AzCore/Memory/SystemAllocator.h>
#include <AzCore/RTTI/BehaviorContext.h>
#include <AzCore/Serialization/EditContext.h>
#include <AzCore/Serialization/SerializeContext.h>
#include <AzCore/std/smart_ptr/make_shared.h>
#include <AzCore/std/smart_ptr/shared_ptr.h>
#include <AzCore/std/string/conversions.h>

#if defined (PLATFORM_SUPPORTS_AWS_NATIVE_SDK)
#include <aws/core/http/HttpRequest.h>
#include <aws/core/http/HttpResponse.h>
#endif // (PLATFORM_SUPPORTS_AWS_NATIVE_SDK)

#include <CloudGemFramework/ServiceRequestJob.h>


#include "CloudGemComputeFarm_precompiled.h"



namespace CloudGemComputeFarm {
namespace ServiceAPI {
    
    extern const char* LmbrAWS_CodeGen_Component_UUID;
    
    extern const char* LmbrAWS_CodeGen_ResponseHandler_UUID;
    
    extern const char* LmbrAWS_CodeGen_NotificationBus1_UUID;
    
    extern const char* LmbrAWS_CodeGen_RequestBus1_UUID;
    
    extern const char* LmbrAWS_CodeGen_ExampleData_UUID;
    
    extern const char* LmbrAWS_CodeGen_ServiceStatus_UUID;
    

    // redefs
    

    bool WriteJson(CloudGemFramework::JsonWriter& writer, const int& item);

    bool WriteJson(CloudGemFramework::JsonWriter& writer, const AZStd::string& item);

    bool WriteJson(CloudGemFramework::JsonWriter& writer, const double& item);

    
    
    struct ExampleData
    {

        AZ_TYPE_INFO(ExampleData, LmbrAWS_CodeGen_ExampleData_UUID)
        AZ_CLASS_ALLOCATOR(ExampleData, AZ::SystemAllocator, 0)

        
        int ExamplePropertyB;
        
        AZStd::string ExamplePropertyA;
        

        bool OnJsonKey(const char* key, CloudGemFramework::JsonReader& reader);

        static void Reflect(AZ::ReflectContext* reflection);
    };

    bool WriteJson(CloudGemFramework::JsonWriter& writer, const ExampleData& item);
    
    
    
    struct ServiceStatus
    {

        AZ_TYPE_INFO(ServiceStatus, LmbrAWS_CodeGen_ServiceStatus_UUID)
        AZ_CLASS_ALLOCATOR(ServiceStatus, AZ::SystemAllocator, 0)

        
        AZStd::string status;
        

        bool OnJsonKey(const char* key, CloudGemFramework::JsonReader& reader);

        static void Reflect(AZ::ReflectContext* reflection);
    };

    bool WriteJson(CloudGemFramework::JsonWriter& writer, const ServiceStatus& item);
    
    


    // Service RequestJobs
    CLOUD_GEM_SERVICE(CloudGemComputeFarm);


    
    class PostExampleRequest
        : public CloudGemFramework::ServiceRequest
    {
    public:
        SERVICE_REQUEST(CloudGemComputeFarm, HttpMethod::HTTP_POST, "/example");

        struct Parameters
        {
            
            ExampleData data;
            

            bool BuildRequest(CloudGemFramework::RequestBuilder& request);

            bool WriteJson(CloudGemFramework::JsonWriter& writer) const;
        };

        
        ExampleData result;
        

        Parameters parameters;
    };


    using PostExampleRequestJob = CloudGemFramework::ServiceRequestJob<PostExampleRequest>;
    
    class GetExampleRequest
        : public CloudGemFramework::ServiceRequest
    {
    public:
        SERVICE_REQUEST(CloudGemComputeFarm, HttpMethod::HTTP_GET, "/example");

        struct Parameters
        {
            

            bool BuildRequest(CloudGemFramework::RequestBuilder& request);

            bool WriteJson(CloudGemFramework::JsonWriter& writer) const;
        };

        
        ExampleData result;
        

        Parameters parameters;
    };


    using GetExampleRequestJob = CloudGemFramework::ServiceRequestJob<GetExampleRequest>;
    
    class GetServiceStatusRequest
        : public CloudGemFramework::ServiceRequest
    {
    public:
        SERVICE_REQUEST(CloudGemComputeFarm, HttpMethod::HTTP_GET, "/service/status");

        struct Parameters
        {
            

            bool BuildRequest(CloudGemFramework::RequestBuilder& request);

            bool WriteJson(CloudGemFramework::JsonWriter& writer) const;
        };

        
        ServiceStatus result;
        

        Parameters parameters;
    };


    using GetServiceStatusRequestJob = CloudGemFramework::ServiceRequestJob<GetServiceStatusRequest>;
    


    // Notification bus for this component
    class CloudGemComputeFarmNotifications
        : public AZ::ComponentBus
    {
    public:
        
        /**
         * Sent when the request is a success
         *
         * Params:
         *    jsonOutput:       The output receieved from the lambda call
         *    request:          The AWS Lambda request object
         */
        
        virtual void OnPostExampleRequestSuccess(const ExampleData response);
        

        /**
         * Sent when the request fails
         *
         * Params:
         *    error:           The output receieved from the lambda call,
         *                     could be function error or an issue with the request
         *    request:         The AWS Lambda request object
         */
        virtual void OnPostExampleRequestError(const CloudGemFramework::Error error);
        
        /**
         * Sent when the request is a success
         *
         * Params:
         *    jsonOutput:       The output receieved from the lambda call
         *    request:          The AWS Lambda request object
         */
        
        virtual void OnGetExampleRequestSuccess(const ExampleData response);
        

        /**
         * Sent when the request fails
         *
         * Params:
         *    error:           The output receieved from the lambda call,
         *                     could be function error or an issue with the request
         *    request:         The AWS Lambda request object
         */
        virtual void OnGetExampleRequestError(const CloudGemFramework::Error error);
        
        /**
         * Sent when the request is a success
         *
         * Params:
         *    jsonOutput:       The output receieved from the lambda call
         *    request:          The AWS Lambda request object
         */
        
        virtual void OnGetServiceStatusRequestSuccess(const ServiceStatus response);
        

        /**
         * Sent when the request fails
         *
         * Params:
         *    error:           The output receieved from the lambda call,
         *                     could be function error or an issue with the request
         *    request:         The AWS Lambda request object
         */
        virtual void OnGetServiceStatusRequestError(const CloudGemFramework::Error error);
        
    };

    using CloudGemComputeFarmNotificationBus = AZ::EBus<CloudGemComputeFarmNotifications>;

    class BehaviorCloudGemComputeFarmNotificationBusHandler
        : public CloudGemComputeFarmNotificationBus::Handler, public AZ::BehaviorEBusHandler
    {
    public:
        AZ_EBUS_BEHAVIOR_BINDER(BehaviorCloudGemComputeFarmNotificationBusHandler, LmbrAWS_CodeGen_NotificationBus1_UUID, AZ::SystemAllocator
        
        , OnPostExampleRequestSuccess
        , OnPostExampleRequestError
        
        , OnGetExampleRequestSuccess
        , OnGetExampleRequestError
        
        , OnGetServiceStatusRequestSuccess
        , OnGetServiceStatusRequestError
        
        );
        
        
        void OnPostExampleRequestSuccess(const ExampleData response) override;
        
        void OnPostExampleRequestError(const CloudGemFramework::Error error) override;
        
        
        void OnGetExampleRequestSuccess(const ExampleData response) override;
        
        void OnGetExampleRequestError(const CloudGemFramework::Error error) override;
        
        
        void OnGetServiceStatusRequestSuccess(const ServiceStatus response) override;
        
        void OnGetServiceStatusRequestError(const CloudGemFramework::Error error) override;
        
    };
    class CloudGemComputeFarmResponseHandler;

    // Request bus for this component
    class CloudGemComputeFarmRequests
        : public AZ::ComponentBus
    {
    public:
        virtual ~CloudGemComputeFarmRequests() {}
        
        
        virtual void PostExample(const ExampleData& data, CloudGemComputeFarmResponseHandler* responseHandler);
        
        
        
        virtual void GetExample(CloudGemComputeFarmResponseHandler* responseHandler);
        
        
        
        virtual void GetServiceStatus(CloudGemComputeFarmResponseHandler* responseHandler);
        
        
    };

    using CloudGemComputeFarmRequestBus = AZ::EBus<CloudGemComputeFarmRequests>;

    // This class is used as a parameter for all requests and throws the response on the CloudGemComputeFarmNotificationBus
    // Inherit from this to define custom behavior.
    class CloudGemComputeFarmResponseHandler
    {
    public:
        AZ_TYPE_INFO(CloudGemComputeFarmResponseHandler, LmbrAWS_CodeGen_ResponseHandler_UUID)
        AZ_CLASS_ALLOCATOR(CloudGemComputeFarmResponseHandler, AZ::SystemAllocator, 0)

        virtual ~CloudGemComputeFarmResponseHandler() {}
        
        virtual void HandlePostExampleSuccess(PostExampleRequestJob* job, AZ::EntityId entityId);
        virtual void HandlePostExampleError(PostExampleRequestJob* job, AZ::EntityId entityId);
        
        virtual void HandleGetExampleSuccess(GetExampleRequestJob* job, AZ::EntityId entityId);
        virtual void HandleGetExampleError(GetExampleRequestJob* job, AZ::EntityId entityId);
        
        virtual void HandleGetServiceStatusSuccess(GetServiceStatusRequestJob* job, AZ::EntityId entityId);
        virtual void HandleGetServiceStatusError(GetServiceStatusRequestJob* job, AZ::EntityId entityId);
        
    };

    class CloudGemComputeFarmClientComponent
        : public AZ::Component
        , public CloudGemComputeFarmRequestBus::Handler
    {
    public:
        AZ_COMPONENT(CloudGemComputeFarmClientComponent, LmbrAWS_CodeGen_Component_UUID);
        virtual ~CloudGemComputeFarmClientComponent() = default;

        AZStd::shared_ptr<CloudGemComputeFarmResponseHandler> m_defaultResponseHandler;

        void Init() override;

        void Activate() override;

        void Deactivate() override;

        static void Reflect(AZ::ReflectContext* reflection)
        {
            
            
            ExampleData::Reflect(reflection);
            
            
            
            ServiceStatus::Reflect(reflection);
            
            

            AZ::SerializeContext* serializeContext = azrtti_cast<AZ::SerializeContext*>(reflection);
            if (serializeContext)
            {
                // we must include any fields we want to expose to the editor or lua in the serialize context
                serializeContext->Class<CloudGemComputeFarmClientComponent>()
                    ->Version(1);

                AZ::EditContext* editContext = serializeContext->GetEditContext();
                if (editContext)
                {
                    editContext->Class<CloudGemComputeFarmClientComponent>("CloudGemComputeFarmClientComponent", "CloudGemComputeFarm Component")
                        ->ClassElement(AZ::Edit::ClassElements::EditorData, "")
                            ->Attribute(AZ::Edit::Attributes::Category, "Cloud Canvas Gems")
                            ->Attribute(AZ::Edit::Attributes::AppearsInAddComponentMenu, AZ_CRC("Game"));
                }
            }

            AZ::BehaviorContext* behaviorContext = azrtti_cast<AZ::BehaviorContext*>(reflection);
            if (behaviorContext)
            {
                behaviorContext->EBus<CloudGemComputeFarmRequestBus>("CloudGemComputeFarmRequestBus")
                    // one of these for each function
                    
                    ->Event("PostExample", &CloudGemComputeFarmRequestBus::Events::PostExample)
                    
                    ->Event("GetExample", &CloudGemComputeFarmRequestBus::Events::GetExample)
                    
                    ->Event("GetServiceStatus", &CloudGemComputeFarmRequestBus::Events::GetServiceStatus)
                    
                    ;
                behaviorContext->EBus<CloudGemComputeFarmNotificationBus>("CloudGemComputeFarmNotificationBus")
                    ->Handler<BehaviorCloudGemComputeFarmNotificationBusHandler>()
                ;
            }
        }

        // Functions from the swagger definitions
        
        
        void PostExample(const ExampleData& data, CloudGemComputeFarmResponseHandler* responseHandler) override;
        
        
        
        void GetExample(CloudGemComputeFarmResponseHandler* responseHandler) override;
        
        
        
        void GetServiceStatus(CloudGemComputeFarmResponseHandler* responseHandler) override;
        
        
    };
} // ServiceAPI
} // CloudGemComputeFarm