########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    bld.CryEngineSharedLibrary(
        # Settings
        target                  = 'AzPhysicsTests',
        vs_filter               = 'AZ Framework/TestSuites',
        file_list               = 'azphysicstests.waf_files',
        platforms               = ['win'],
        configurations          = ['all'],
        test_only               = True,
        use                     = ['AzTest', 'AzToolsFramework'],
        msvc_cxxflags           = ['/W4'],
        
        # This test dll does not have any actual source files defined. Prevent it from trying to generate an rc file
        inject_copyright        = False
    )

