########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):

    bld.CryStandAlonePlugin(

        # Settings
        target                  = 'FBXPlugin',
        vs_filter               = 'Sandbox/Plugins',
        copyright_org           = 'Amazon-CryTek',
        file_list               = 'fbxplugin.waf_files',
        platforms               = ['win', 'darwin'],
        configurations          = ['debug', 'debug_test', 'profile', 'profile_test'],
        pch                     = 'StdAfx.cpp',
        use                     = ['EditorCommon'],
        uselib                  = ['QT5CORE',
                                   'QT5GUI',
                                   'QT5WIDGETS',
                                   'FBXSDK'],

        # Platform Specific
        win_lib                 = ['Wininet'],

        darwin_enable_rtti = True,

        win_x64_clang_cxxflags  = ['-Wno-null-dereference'],

        # Testing
        test_all_file_list      = ['fbxplugin_test.waf_files'],
    )
