########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################


def build(bld):
    bld.DefineGem(
        editor = dict(
            # Settings
            file_list                   = ['imageprocessing.waf_files'],
            pch                         = 'Source/ImageProcessing_precompiled.cpp',
            use                         = ['AzToolsFramework',
                                           'AzQtComponents',
                                           'AssetBuilderSDK'],
    
            includes                    = ['include',
                                           'Source',
                                           bld.Path('Code/CryEngine/CryCommon'),
                                           bld.ThirdPartyPath('squish')],
            
            defines                     = ['NDEBUG'],   #use NDEBUG to remove asserts in squishccr plugin in debug version
    
            uselib                      = ['QT5CORE',
                                           'QT5GUI',
                                           'QT5WIDGETS',
                                           'TIFF',
                                           'PVR_TEX_TOOL',
                                           'ETC2COMP',
                                           'ASTCENC'],
            
            platforms                   = ['win', 'darwin'],
            
            # Platform Roots
            platform_roots              = [bld.PlatformRoot('Source/Platform', export_includes=False)],
            
            # Windows
            win_defines                 = ['_WIN64'],
    
            # Testing
            test_all_file_list          = ['imageprocessing_tests.waf_files'],
        )
    )

