########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    defines = []
    
    bld.CryEngineStaticLibrary(
        # Settings
        target          = 'AzCoreTestCommon',
        vs_filter       = 'AZ Framework',
        file_list       = ['azcore_test.waf_files'],
        disable_pch     = True,
        test_only       = True,
        includes        = ['..'],
        export_includes = ['..'],
        use             = ['GMOCK', 'UNWIND'],
        
        # Platform Roots
        platform_roots = [bld.PlatformRoot('../Platform', export_includes=True)]
    )

    bld.CryEngineStaticLibrary(
        # Settings
        target          = 'AzCore',
        vs_filter       = 'AZ Framework',
        file_list       = ['azcore.waf_files', 'std/azstd.waf_files'],
        platforms       = ['all'],
        configurations  = ['all'],
        disable_pch     = True,
        includes        = ['..'],
        export_includes = ['..'],
        use             = ['RAPIDJSON',
                           'RAPIDXML',
                           'LUA',
                           'ZSTD',
                           'LZ4',
                           'ZLIB',
                           'RAD_TELEMETRY',
                           'UNWIND'],
        test_all_use    = ['GMOCK',
                           'AzCoreTestCommon'],
        defines         = list(defines),
        export_defines  = list(defines),
        features        = ['internal_telemetry'],

        # Platform Roots
        platform_roots  = [bld.PlatformRoot('../Platform', export_includes=True)],
    
        # Test Specific
        create_test_driver  = True,
        test_vs_filter      = 'AZ Framework/TestSuites',
        test_file_list      = ['../Tests/azcoretests.waf_files'],
        test_includes       = ['../Tests'],
        test_use            = ['BENCHMARK', 'AzTestShared'],
        test_platforms      = ['win', 'darwin'],
        test_platform_roots = [bld.PlatformRoot('../Tests/Platform', export_includes=False)],
    )

    bld.CryEngineStaticLibrary(
        target                  = 'AzTestShared',
        vs_filter               = 'AZ Framework',
        file_list               = '../Tests/aztestshared.waf_files',
        platforms               = ['win', 'darwin'],
        configurations          = ['all'],
        test_only               = True,
        use                     = ['AzCore'],
        includes                = ['../Tests'],
        export_includes         = ['../Tests'],
        msvc_cxxflags           = ['/W4'],
    )
