########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    defines = []

    bld.CryEngineStaticLibrary(
        # Settings
        target          = 'AzCore',
        vs_filter       = 'AZ Framework',
        file_list       = ['azcore.waf_files', 'std/azstd.waf_files'],
        platforms       = ['all'],
        configurations  = ['all'],
        disable_pch     = True,
        includes        = ['..'],
        export_includes = ['..'],
        use             = ['RAPIDJSON',
                           'RAPIDXML',
                           'LUA',
                           'ZSTD',
                           'LZ4',
                           'ZLIB',
                           'RAD_TELEMETRY',
                           'UNWIND'],
        defines         = list(defines),
        export_defines  = list(defines),
        features        = ['internal_telemetry'],

        # Platform Roots
        platform_roots  = [bld.PlatformRoot('../Platform', export_includes=True)],
    
        # Testing
        test_all_file_list  = ['azcore_test.waf_files'],

    )
