########################################################################################
#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates, or
# a third party where indicated.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

SUBFOLDERS = [
    "Physics"
]

def build(bld):

    bld.CryEngineSharedLibrary(
        # Settings
        target              = 'FrameworkTests',
        vs_filter           = 'AZ Framework/TestSuites',
        file_list           = 'frameworktests.waf_files',
        platforms           = ['win', 'darwin'],
        configurations      = ['all'],
        test_only           = True,
        use                 = ['AzTest', 'AzToolsFramework', 'AzTestShared'],
        uselib              = ['QT5CORE',
                               'QT5GUI',
                               'QT5WIDGETS'],
        test_all_use        = ['AzTestShared'],
        # Platform Roots
        platform_roots      = [bld.PlatformRoot('Platform', export_includes=False)],
        
        # Platform Specific
        msvc_cxxflags       = ['/W4'],
    )
    
    bld.CryConsoleApplication(

        # Settings
        target          = 'ProcessLaunchTest',
        file_list       = ['process_launch_test.waf_files'],
        platforms       = ['win', 'darwin'],
        exclude_monolithic  = True,
        test_only       = True,
        vs_filter       = 'AZ Framework/TestSuites',
        use             = ['AzCore','AzFramework'],

        test_all_file_list = ['process_launch_test_tests.waf_files'],
                
        # Platform Specific
        darwin_rpath    = ['@executable_path']
    )

    bld.recurse(SUBFOLDERS)
