########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):

    import lumberyard_sdks

    aws_files = ['aws_sdk.waf_files']


    file_list = ['aws.waf_files']
    if lumberyard_sdks.should_project_include_aws_native_sdk(bld):
        file_list += aws_files

    bld.DefineGem(
        includes    = [ '.' , 
                        '..', 
                        bld.Path('Code/CryEngine/CryAction'),
                        bld.Path('Code/CryEngine/CryCommon')],
        uselib      = ['AWS_CPP_SDK_ALL'],
        use         = ['CloudGemFrameworkStaticLibrary'],
        file_list   = file_list,

        # warning added in clang 6.0 / ndk r17, the issue stems from an object in AWS that has virtual functions
        # but no virtual destructor in the base class
        android_cxxflags = ['-Wno-delete-non-virtual-dtor'],
    )
