########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
#
# Original file Copyright Crytek GMBH or its affiliates, used under license.
#
########################################################################################

def build(bld):

    kw = dict(
        # Settings
        target                  = 'CrySystem',
        vs_filter               = 'CryEngine',
        copyright_org           = 'Amazon-CryTek',
        file_list               = 'crysystem.waf_files',
        platforms               = ['all'],
        configurations          = ['all'],
        pch                     = 'StdAfx.cpp',
        use                     = ['AzFramework',
                                   'GridMate',
                                   'CrashHandler',
                                   'RemoteConsoleCore'],
        uselib                  = ['LZ4',
                                   'TIFF',
                                   'TOMCRYPT',
                                   'TOMMATH',
                                   'EXPAT',
                                   'ZLIB',
                                   'MD5'],
        includes                = [bld.Path('Code/Tools/GemRegistry/include') ],
        features                = ['link_running_program'],
        defines                 = ['ENGINE_EXPORTS', 'USE_CRY_NEW_AND_DELETE'],

        # Platform Specific
        win_defines             = ['EXCLUDE_CINEMIZER_SDK'],
        win_file_list           = 'platformos_pc.waf_files',
        win_linkflags           = '/NODEFAULTLIB:libcmt.lib',
        win_lib                 = ['wininet', 'Shell32', 'Ole32', 'Gdi32', 'ws2_32'],

        darwin_file_list        = 'platformos_pc.waf_files',
        darwin_lib              = ['ncurses'],

        linux_file_list         = 'platformos_pc.waf_files',
        linux_lib               = [ 'tomcrypt', 'tommath', 'm' ],

        restricted_script       = 'update_restricted_parameters',

        android_file_list       = [ 'platformos_pc.waf_files', 'crysystem_android.waf_files' ],

        ios_file_list           = [ 'platformos_pc.waf_files', 'crysystem_ios.waf_files' ],

        appletv_file_list       = 'platformos_pc.waf_files',

        win_x64_clang_cxxflags  = ['-Wno-deprecated-declarations'],

        # Testing
        test_all_file_list      = ['crysystem_test.waf_files'],
    )
    for p0, p1, p2, p3 in bld.env['RESTRICTED_PLATFORMS']:
        kw['{}_file_list'.format(p3)] = [
            '{0}/crysystem_{1}.waf_files'.format(p0, p1),
            '{0}/platformos_{1}.waf_files'.format(p0, p1)
        ]
    bld.CryEngineModule(**kw)
